package com.ca.arcserve.edge.app.base.webservice.sync.arcserve.impl.common.keyschema;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2011.02.15 at 12:33:50 CST 
//

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="Tables">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="Table" maxOccurs="unbounded">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="Columns">
*                               &lt;complexType>
*                                 &lt;complexContent>
*                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                                     &lt;sequence>
*                                       &lt;element name="Column" maxOccurs="unbounded">
*                                         &lt;complexType>
*                                           &lt;complexContent>
*                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                                               &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                               &lt;attribute name="DataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                               &lt;attribute name="IsKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                               &lt;attribute name="IsIdentity" type="{http://www.w3.org/2001/XMLSchema}string" />
*                                             &lt;/restriction>
*                                           &lt;/complexContent>
*                                         &lt;/complexType>
*                                       &lt;/element>
*                                     &lt;/sequence>
*                                   &lt;/restriction>
*                                 &lt;/complexContent>
*                               &lt;/complexType>
*                             &lt;/element>
*                           &lt;/sequence>
*                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "tables"
})
@XmlRootElement(name = "KeySchema")
public class KeySchema {

 @XmlElement(name = "Tables", required = true)
 protected KeySchema.Tables tables;

 /**
  * Gets the value of the tables property.
  * 
  * @return
  *     possible object is
  *     {@link KeySchema.Tables }
  *     
  */
 public KeySchema.Tables getTables() {
     return tables;
 }

 /**
  * Sets the value of the tables property.
  * 
  * @param value
  *     allowed object is
  *     {@link KeySchema.Tables }
  *     
  */
 public void setTables(KeySchema.Tables value) {
     this.tables = value;
 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="Table" maxOccurs="unbounded">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="Columns">
  *                     &lt;complexType>
  *                       &lt;complexContent>
  *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                           &lt;sequence>
  *                             &lt;element name="Column" maxOccurs="unbounded">
  *                               &lt;complexType>
  *                                 &lt;complexContent>
  *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                                     &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                     &lt;attribute name="DataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                     &lt;attribute name="IsKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                     &lt;attribute name="IsIdentity" type="{http://www.w3.org/2001/XMLSchema}string" />
  *                                   &lt;/restriction>
  *                                 &lt;/complexContent>
  *                               &lt;/complexType>
  *                             &lt;/element>
  *                           &lt;/sequence>
  *                         &lt;/restriction>
  *                       &lt;/complexContent>
  *                     &lt;/complexType>
  *                   &lt;/element>
  *                 &lt;/sequence>
  *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "table"
 })
 public static class Tables {

     @XmlElement(name = "Table", required = true)
     protected List<KeySchema.Tables.Table> table;

     /**
      * Gets the value of the table property.
      * 
      * <p>
      * This accessor method returns a reference to the live list,
      * not a snapshot. Therefore any modification you make to the
      * returned list will be present inside the JAXB object.
      * This is why there is not a <CODE>set</CODE> method for the table property.
      * 
      * <p>
      * For example, to add a new item, do as follows:
      * <pre>
      *    getTable().add(newItem);
      * </pre>
      * 
      * 
      * <p>
      * Objects of the following type(s) are allowed in the list
      * {@link KeySchema.Tables.Table }
      * 
      * 
      */
     public List<KeySchema.Tables.Table> getTable() {
         if (table == null) {
             table = new ArrayList<KeySchema.Tables.Table>();
         }
         return this.table;
     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="Columns">
      *           &lt;complexType>
      *             &lt;complexContent>
      *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *                 &lt;sequence>
      *                   &lt;element name="Column" maxOccurs="unbounded">
      *                     &lt;complexType>
      *                       &lt;complexContent>
      *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                           &lt;attribute name="DataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                           &lt;attribute name="IsKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                           &lt;attribute name="IsIdentity" type="{http://www.w3.org/2001/XMLSchema}string" />
      *                         &lt;/restriction>
      *                       &lt;/complexContent>
      *                     &lt;/complexType>
      *                   &lt;/element>
      *                 &lt;/sequence>
      *               &lt;/restriction>
      *             &lt;/complexContent>
      *           &lt;/complexType>
      *         &lt;/element>
      *       &lt;/sequence>
      *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "columns"
     })
     public static class Table {

         @XmlElement(name = "Columns", required = true)
         protected KeySchema.Tables.Table.Columns columns;
         @XmlAttribute(name = "Name", required = true)
         protected String name;

         /**
          * Gets the value of the columns property.
          * 
          * @return
          *     possible object is
          *     {@link KeySchema.Tables.Table.Columns }
          *     
          */
         public KeySchema.Tables.Table.Columns getColumns() {
             return columns;
         }

         /**
          * Sets the value of the columns property.
          * 
          * @param value
          *     allowed object is
          *     {@link KeySchema.Tables.Table.Columns }
          *     
          */
         public void setColumns(KeySchema.Tables.Table.Columns value) {
             this.columns = value;
         }

         /**
          * Gets the value of the name property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getName() {
             return name;
         }

         /**
          * Sets the value of the name property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setName(String value) {
             this.name = value;
         }


         /**
          * <p>Java class for anonymous complex type.
          * 
          * <p>The following schema fragment specifies the expected content contained within this class.
          * 
          * <pre>
          * &lt;complexType>
          *   &lt;complexContent>
          *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
          *       &lt;sequence>
          *         &lt;element name="Column" maxOccurs="unbounded">
          *           &lt;complexType>
          *             &lt;complexContent>
          *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
          *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
          *                 &lt;attribute name="DataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
          *                 &lt;attribute name="IsKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
          *                 &lt;attribute name="IsIdentity" type="{http://www.w3.org/2001/XMLSchema}string" />
          *               &lt;/restriction>
          *             &lt;/complexContent>
          *           &lt;/complexType>
          *         &lt;/element>
          *       &lt;/sequence>
          *     &lt;/restriction>
          *   &lt;/complexContent>
          * &lt;/complexType>
          * </pre>
          * 
          * 
          */
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {
             "column"
         })
         public static class Columns {

             @XmlElement(name = "Column", required = true)
             protected List<KeySchema.Tables.Table.Columns.Column> column;

             /**
              * Gets the value of the column property.
              * 
              * <p>
              * This accessor method returns a reference to the live list,
              * not a snapshot. Therefore any modification you make to the
              * returned list will be present inside the JAXB object.
              * This is why there is not a <CODE>set</CODE> method for the column property.
              * 
              * <p>
              * For example, to add a new item, do as follows:
              * <pre>
              *    getColumn().add(newItem);
              * </pre>
              * 
              * 
              * <p>
              * Objects of the following type(s) are allowed in the list
              * {@link KeySchema.Tables.Table.Columns.Column }
              * 
              * 
              */
             public List<KeySchema.Tables.Table.Columns.Column> getColumn() {
                 if (column == null) {
                     column = new ArrayList<KeySchema.Tables.Table.Columns.Column>();
                 }
                 return this.column;
             }


             /**
              * <p>Java class for anonymous complex type.
              * 
              * <p>The following schema fragment specifies the expected content contained within this class.
              * 
              * <pre>
              * &lt;complexType>
              *   &lt;complexContent>
              *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
              *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
              *       &lt;attribute name="DataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
              *       &lt;attribute name="IsKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
              *       &lt;attribute name="IsIdentity" type="{http://www.w3.org/2001/XMLSchema}string" />
              *     &lt;/restriction>
              *   &lt;/complexContent>
              * &lt;/complexType>
              * </pre>
              * 
              * 
              */
             @XmlAccessorType(XmlAccessType.FIELD)
             @XmlType(name = "")
             public static class Column {

                 @XmlAttribute(name = "Name", required = true)
                 protected String name;
                 @XmlAttribute(name = "DataType", required = true)
                 protected String dataType;
                 @XmlAttribute(name = "IsKey", required = true)
                 protected String isKey;
                 @XmlAttribute(name = "IsIdentity")
                 protected String isIdentity;

                 /**
                  * Gets the value of the name property.
                  * 
                  * @return
                  *     possible object is
                  *     {@link String }
                  *     
                  */
                 public String getName() {
                     return name;
                 }

                 /**
                  * Sets the value of the name property.
                  * 
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *     
                  */
                 public void setName(String value) {
                     this.name = value;
                 }

                 /**
                  * Gets the value of the dataType property.
                  * 
                  * @return
                  *     possible object is
                  *     {@link String }
                  *     
                  */
                 public String getDataType() {
                     return dataType;
                 }

                 /**
                  * Sets the value of the dataType property.
                  * 
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *     
                  */
                 public void setDataType(String value) {
                     this.dataType = value;
                 }

                 /**
                  * Gets the value of the isKey property.
                  * 
                  * @return
                  *     possible object is
                  *     {@link String }
                  *     
                  */
                 public String getIsKey() {
                     return isKey;
                 }

                 /**
                  * Sets the value of the isKey property.
                  * 
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *     
                  */
                 public void setIsKey(String value) {
                     this.isKey = value;
                 }

                 /**
                  * Gets the value of the isIdentity property.
                  * 
                  * @return
                  *     possible object is
                  *     {@link String }
                  *     
                  */
                 public String getIsIdentity() {
                     return isIdentity;
                 }

                 /**
                  * Sets the value of the isIdentity property.
                  * 
                  * @param value
                  *     allowed object is
                  *     {@link String }
                  *     
                  */
                 public void setIsIdentity(String value) {
                     this.isIdentity = value;
                 }

             }

         }

     }

 }

}

