//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.08 at 03:04:03 ÏÂÎç CST 
//


package com.ca.arcserve.edge.app.base.webservice.d2ddatasync;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BackupDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BackupDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RootItem" type="{}RootItem" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="BackupType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CompressType" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DataSizeKB" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="TransferDataSizeKB" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="CatalogSizeB" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BackupDetail", propOrder = {
    "rootItem"
})
public class BackupDetail {

    @XmlElement(name = "RootItem")
    protected List<RootItem> rootItem;
    @XmlAttribute(name = "ID")
    protected BigInteger id;
    @XmlAttribute(name = "JobID")
    protected BigInteger jobId;
    @XmlAttribute(name = "SessGuid")
    protected String sessGuid;
    @XmlAttribute(name = "BackupType")
    protected String backupType;
    @XmlAttribute(name = "CompressType")
    protected Integer compressType;
    @XmlAttribute(name = "DataSizeKB")
    protected Long dataSizeKB;
    @XmlAttribute(name = "TransferDataSizeKB")
    protected String transferDataSizeKB;
    @XmlAttribute(name = "ProtectedDataSizeB")
    protected String protectedDataSizeB;
    @XmlAttribute(name = "CatalogSizeB")
    protected Long catalogSizeB;
    @XmlAttribute(name = "EncryptType")
    protected Integer encryptType;
    @XmlAttribute(name = "EncryptPasswordHash")
    protected String encryptPasswordHash;
    @XmlAttribute(name = "TotalRawDataSizeWritten")
    protected Long totalRawDataSizeWritten;
    @XmlAttribute(name = "syntheticRawSizeRead")
    protected Long syntheticRawSizeRead;
	@XmlAttribute(name = "ntfsVolumeSizeByBitMap")
    protected Long ntfsVolumeSizeByBitMap;
    @XmlAttribute(name = "VirtualDiskProvisionSize")   
    protected Long virtualDiskProvisionSize;
    @XmlAttribute(name = "BackupDest")
    protected String backupDest;
    @XmlAttribute(name = "BMRFlag")
    protected Integer bMRFlag;
    @XmlAttribute(name = "NodeName")
    protected String nodeName;
    @XmlAttribute(name = "CatalogStatus")
    protected Integer catalogStatus;
    @XmlAttribute(name = "SessionTime")
    protected String sessionTime;
    @XmlAttribute(name = "SessionDate")
    protected String sessionDate;
    @XmlAttribute(name = "TargetDataStoreName")
    protected String targetDataStoreName;
    @XmlAttribute(name = "PolicyName")
    protected String policyName;
    @XmlAttribute(name = "TargetRPS")
    protected String targetRps;

    /**
     * Gets the value of the rootItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rootItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRootItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RootItem }
     * 
     * 
     */
    public List<RootItem> getRootItem() {
        if (rootItem == null) {
            rootItem = new ArrayList<RootItem>();
        }
        return this.rootItem;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }
    
    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJobID() {
        return jobId;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJobID(BigInteger value) {
        this.jobId = value;
    }
    
    public String getSessGuid() {
        return sessGuid;
    }

    public void setSessGuid(String value) {
        this.sessGuid = value;
    }
    
    /**
     * Gets the value of the backupType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupType() {
        return backupType;
    }

    /**
     * Sets the value of the backupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupType(String value) {
        this.backupType = value;
    }

    /**
     * Gets the value of the compressType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getCompressType() {
        return compressType;
    }

    /**
     * Sets the value of the compressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompressType(Integer value) {
        this.compressType = value;
    }

    /**
     * Gets the value of the dataSizeKB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataSizeKB() {
        return dataSizeKB;
    }

    /**
     * Sets the value of the dataSizeKB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataSizeKB(Long value) {
        this.dataSizeKB = value;
    }

    /**
     * Gets the value of the transferDataSizeKB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public String getTransferDataSizeKB() {
        return transferDataSizeKB;
    }

    /**
     * Sets the value of the transferDataSizeKB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTransferDataSizeKB(String value) {
        this.transferDataSizeKB = value;
    }

    /**
     * Sets the value of the protectedDataSizeB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProtectedDataSizeB(String value) {
        this.protectedDataSizeB = value;
    }

    /**
     * Gets the value of the protectedDataSizeB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public String getProtectedDataSizeB() {
        return protectedDataSizeB;
    }
    
    /**
     * Gets the value of the catalogSizeB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCatalogSizeB() {
        return catalogSizeB;
    }

    /**
     * Sets the value of the catalogSizeB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCatalogSizeB(Long value) {
        this.catalogSizeB = value;
    }
    
    
    public Integer getEncryptType() {
        return encryptType;
    }

    
    public void setEncryptType(Integer value) {
        this.encryptType = value;
    }
    
    public String getEncryptPasswordHash() {
        return encryptPasswordHash;
    }

    
    public void setEncryptPasswordHash(String value) {
        this.encryptPasswordHash = value;
    }
    
    public Long getTotalRawDataSizeWritten() {
        return totalRawDataSizeWritten;
    }
    
    public void setTotalRawDataSizeWritten(Long value) {
        this.totalRawDataSizeWritten = value;
    }
    
    public Long getSyntheticRawSizeRead() {
		return syntheticRawSizeRead;
	}

	public void setSyntheticRawSizeRead(Long syntheticRawSizeRead) {
		this.syntheticRawSizeRead = syntheticRawSizeRead;
	}

	public Long getNtfsVolumeSizeByBitMap() {
		return ntfsVolumeSizeByBitMap;
	}

	public void setNtfsVolumeSizeByBitMap(Long ntfsVolumeSizeByBitMap) {
		this.ntfsVolumeSizeByBitMap = ntfsVolumeSizeByBitMap;
	}
	
	public Long getVirtualDiskProvisionSize() {
		return virtualDiskProvisionSize;
	}

	public void setVirtualDiskProvisionSize(Long virtualDiskProvisionSize) {
		this.virtualDiskProvisionSize = virtualDiskProvisionSize;
	}
    
    public String getBackupDest() {
        return backupDest;
    }

    
    public void setBackupDest(String value) {
        this.backupDest = value;
    }
    
    /**
     * Gets the value of the bMRFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBMRFlag() {
        return bMRFlag;
    }

    /**
     * Sets the value of the bMRFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBMRFlag(Integer value) {
        this.bMRFlag = value;
    }

	public String getNodeName() {
		return nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getTargetDataStoreName() {
		return targetDataStoreName;
	}

	public void setTargetDataStoreName(String targetDataStoreName) {
		this.targetDataStoreName = targetDataStoreName;
	}

	public String getPolicyName() {
		return policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	public String getTargetRps() {
		return targetRps;
	}

	public void setTargetRps(String targetRps) {
		this.targetRps = targetRps;
	}
	
	
}
