//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.08 at 03:04:03 ÏÂÎç CST 
//


package com.ca.arcserve.edge.app.base.webservice.d2ddatasync;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BackupRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BackupRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BackupInfo" type="{}BackupInfo"/>
 *         &lt;element name="RpsJobInfo" type="{}RpsJobInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BackupRecord", propOrder = {
    "operation",
    "uniqueID",
    "backupInfo",
    "rpsJobHistoryData",
    "sessionInfo"
})
public class BackupRecord {

    @XmlElement(name = "Operation", required = true)
    protected String operation;
    @XmlElement(name = "UniqueID", required = true)
    protected String uniqueID;
    @XmlElement(name = "BackupInfo")
    protected BackupInfo backupInfo;
    @XmlElement(name = "RPSJobHistoryData")
    protected RpsJobInfo rpsJobHistoryData;
    @XmlElement(name = "SessionInfo")
    protected List<SessionInfo> sessionInfo;
    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the uniqueID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueID() {
        return uniqueID;
    }

    /**
     * Sets the value of the uniqueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueID(String value) {
        this.uniqueID = value;
    }
    
    /**
     * Gets the value of the backupInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BackupInfo }
     *     
     */
    public BackupInfo getBackupInfo() {
        return backupInfo;
    }

    /**
     * Sets the value of the backupInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackupInfo }
     *     
     */
    public void setBackupInfo(BackupInfo value) {
        this.backupInfo = value;
    }
    
	public RpsJobInfo getRpsJobHistoryData() {
		return rpsJobHistoryData;
	}

	public void setRpsJobHistoryData(RpsJobInfo rpsJobHistoryData) {
		this.rpsJobHistoryData = rpsJobHistoryData;
	}

	public List<SessionInfo> getSessionInfo() {
		return sessionInfo;
	}

	public void setSessionInfo(List<SessionInfo> sessionInfo) {
		this.sessionInfo = sessionInfo;
	}
}
