//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.08 at 03:04:03 ÏÂÎç CST 
//


package com.ca.arcserve.edge.app.base.webservice.d2ddatasync;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BackupCache }
     * 
     */
    public BackupCache createBackupCache() {
        return new BackupCache();
    }

    /**
     * Create an instance of {@link BackupRecord }
     * 
     */
    public BackupRecord createBackupRecord() {
        return new BackupRecord();
    }

    /**
     * Create an instance of {@link TimeStamp }
     * 
     */
    public TimeStamp createTimeStamp() {
        return new TimeStamp();
    }

    /**
     * Create an instance of {@link BackupDetail }
     * 
     */
    public BackupDetail createBackupDetail() {
        return new BackupDetail();
    }

    /**
     * Create an instance of {@link ServerInfo }
     * 
     */
    public ServerInfo createServerInfo() {
        return new ServerInfo();
    }

    /**
     * Create an instance of {@link BackupInfo }
     * 
     */
    public BackupInfo createBackupInfo() {
        return new BackupInfo();
    }

    /**
     * Create an instance of {@link RootItem }
     * 
     */
    public RootItem createRootItem() {
        return new RootItem();
    }
    
    /**
     * Create an instance of {@link RpsJobInfo.GDDInfo }
     * 
     */
    public RpsJobInfo.GDDInfo createBackupCacheBackupRecordRpsJobInfoGDDInfo() {
        return new RpsJobInfo.GDDInfo();
    }
    
    /**
     * Create an instance of {@link RpsJobInfo.SessionInfo }
     * 
     */
    public RpsJobInfo.SessionInfo createBackupCacheBackupRecordRpsJobInfoSessionInfo() {
        return new RpsJobInfo.SessionInfo();
    }

    /**
     * Create an instance of {@link RpsJobInfo.SessionInfo.Session }
     * 
     */
    public RpsJobInfo.SessionInfo.Session createBackupCacheBackupRecordRpsJobInfoSessionInfoSession() {
        return new RpsJobInfo.SessionInfo.Session();
    }

    /**
     * Create an instance of {@link RpsJobInfo }
     * 
     */
    public RpsJobInfo createBackupCacheBackupRecordRpsJobInfo() {
        return new RpsJobInfo();
    }
}
