//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.08 at 03:04:03 ÏÂÎç CST 
//


package com.ca.arcserve.edge.app.base.webservice.d2ddatasync;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RootItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RootItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MountPoints" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VolumeDataSizeB" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="SubSessNo" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CatalogFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IsBootVolume" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IsSystemVolume" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RootItem")
public class RootItem {

    @XmlAttribute(name = "Type")
    protected String type;
    @XmlAttribute(name = "DisplayName")
    protected String displayName;
    @XmlAttribute(name = "MountPoints")
    protected String mountPoints;
    @XmlAttribute(name = "GUID")
    protected String guid;
    @XmlAttribute(name = "VolumeDataSizeB")
    protected Long volumeDataSizeB;
    @XmlAttribute(name = "SubSessNo")
    protected BigInteger subSessNo;
    @XmlAttribute(name = "CatalogFile")
    protected String catalogFile;
    @XmlAttribute(name = "IsBootVolume")
    protected String isBootVolume;
    @XmlAttribute(name = "IsSystemVolume")
    protected String isSystemVolume;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the mountPoints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMountPoints() {
        return mountPoints;
    }

    /**
     * Sets the value of the mountPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMountPoints(String value) {
        this.mountPoints = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGUID() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGUID(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the volumeDataSizeB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVolumeDataSizeB() {
        return volumeDataSizeB;
    }

    /**
     * Sets the value of the volumeDataSizeB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVolumeDataSizeB(Long value) {
        this.volumeDataSizeB = value;
    }

    /**
     * Gets the value of the subSessNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubSessNo() {
        return subSessNo;
    }

    /**
     * Sets the value of the subSessNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubSessNo(BigInteger value) {
        this.subSessNo = value;
    }

    /**
     * Gets the value of the catalogFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogFile() {
        return catalogFile;
    }

    /**
     * Sets the value of the catalogFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogFile(String value) {
        this.catalogFile = value;
    }

    /**
     * Gets the value of the isBootVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsBootVolume() {
        return isBootVolume;
    }

    /**
     * Sets the value of the isBootVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsBootVolume(String value) {
        this.isBootVolume = value;
    }

    /**
     * Gets the value of the isSystemVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSystemVolume() {
        return isSystemVolume;
    }

    /**
     * Sets the value of the isSystemVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSystemVolume(String value) {
        this.isSystemVolume = value;
    }

}
