package com.ca.arcflash.webservice.replication;

import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

import com.ca.arcflash.common.DataFormatUtil;
import com.ca.arcflash.jobscript.replication.Protocol;

public class ReplicationMessage {
	
	public static final long AFRES_AFREPC = 0x00004000; //16384

	public static final long AFRES_AFREPC_JOB_START               = (AFRES_AFREPC + 0);
	public static final long AFRES_AFREPC_SRC_DES                 = (AFRES_AFREPC + 1);
	public static final long AFRES_AFREPC_JOB_FINISHED            = (AFRES_AFREPC + 2);
	public static final long AFRES_AFREPC_JOB_FAILED              = (AFRES_AFREPC + 3);
	public static final long AFRES_AFREPC_JOB_CANCELED            = (AFRES_AFREPC + 4);
	public static final long AFRES_AFREPC_JOB_SUMMARY             = (AFRES_AFREPC + 5);
	public static final long AFRES_AFREPC_SESS_SKIP               = (AFRES_AFREPC + 6);
	public static final long AFRES_AFREPC_SOCK_CONN_SUCC          = (AFRES_AFREPC + 7);
	public static final long AFRES_AFREPC_SHAR_CONN_SUCC          = (AFRES_AFREPC + 8);
	public static final long AFRES_AFREPC_SOCK_CONN_FAILED        = (AFRES_AFREPC + 9);
	public static final long AFRES_AFREPC_SHAR_CONN_FAILED        = (AFRES_AFREPC + 10);
	public static final long AFRES_AFREPC_SOCK_FAIL_AUTH          = (AFRES_AFREPC + 11);
	public static final long AFRES_AFREPC_SRC_INFO                = (AFRES_AFREPC + 12);
	public static final long AFRES_AFREPC_SOCK_VHD_CMPRS_VOL      = (AFRES_AFREPC + 13);
	public static final long AFRES_AFREPC_SHAR_VHD_CMPRS_VOL      = (AFRES_AFREPC + 14);
	public static final long AFRES_AFREPC_SRC_LOCK_FAILED         = (AFRES_AFREPC + 15);
	public static final long AFRES_AFREPC_DEST_NO_FREE_SPACE      = (AFRES_AFREPC + 16);
	public static final long AFRES_AFREPC_SRV_STOPPING            = (AFRES_AFREPC + 17);
	public static final long AFRES_AFREPC_NETWORK_ERROR           = (AFRES_AFREPC + 18);
	public static final long AFRES_AFREPC_DATA_TRANSFER_ERROR          = (AFRES_AFREPC + 19);
	public static final long AFRES_AFREPC_REMOTE_DEST_CONN_FAILED  = (AFRES_AFREPC + 20);
	public static final long AFRES_AFREPC_JOB_SKIPPED             = (AFRES_AFREPC + 21);
	public static final long AFRES_AFREPC_WINDOWS_ERROR           = (AFRES_AFREPC + 22);
	
	public static final String REPLICATION_RET_MSG = "REPLICATION_RET_MSG";
	public static final String REPLICATION_VMWARE_MSG = "REPLICATION_VMWARE_MSG";
	public static final String REPLICAION_THROUGHPUT_MB = "REPLICAION_THROUGHPUT_MB";
	public static final String REPLICAION_THROUGHPUT_GB = "REPLICAION_THROUGHPUT_GB";
	public static final String REPLICAION_TIME_HOUR = "REPLICAION_TIME_HOUR";
	public static final String REPLICAION_TIME_MIN = "REPLICAION_TIME_MIN";
	public static final String REPLICAION_TIME_SEC = "REPLICAION_TIME_SEC";
	
	public static final String AFRES_AFREPC_PREX = "AFRES_AFREPC_";
	public static final String SKIP_ONE_REPLICAION = "SKIP_ONE_REPLICAION";
	public static final String REPLICAIION_PAUSED = "REPLICAIION_PAUSED";
	public static final String REPLICAIION_PLAN_PAUSED = "REPLICAIION_PLAN_PAUSED";
	public static final String REPLICAION_BEGIN = "REPLICAION_BEGIN";
	public static final String REPLICAION_NO_SESSIONS = "REPLICAION_NO_SESSIONS";
	public static final String REPLICAION_NOT_FULL_MACHINE_SESSION = "REPLICAION_NOT_FULL_MACHINE_SESSION";
	public static final String REPLICATION_SESSION = "REPLICATION_SESSION";
	public static final String REPLICATION_SESSIONS = "REPLICATION_SESSIONS";
	public static final String REPLICATION_SESSION_BEGIN = "REPLICATION_SESSION_BEGIN";
	public static final String REPLICATION_SESSION_BEGIN_SC = "REPLICATION_SESSION_BEGIN_SC";
	public static final String REPLICATION_ONE_SESSION = "REPLICATION_ONE_SESSION";
	public static final String REPLICATION_TAKE_SHAPSHOT = "REPLICATION_TAKE_SHAPSHOT";
	public static final String REPLICATION_CREATE_VM = "REPLICATION_CREATE_VM";
	public static final String REPLICATION_UPLOAD_META_DATA = "REPLICATION_UPLOAD_META_DATA";
	public static final String REPLICATION_UPLOAD_META_DATA_FAILED="REPLICATION_UPLOAD_META_DATA_FAILED";
	public static final String REPLICATION_NO_BOOTVOLUME = "REPLICATION_NO_BOOTVOLUME";
	public static final String REPLICATION_NO_D2DVOLUME = "REPLICATION_NO_D2DVOLUME";
	public static final String REPLICATION_NO_SYSTEMVOLUME = "REPLICATION_NO_SYSTEMVOLUME";
	public static final String REPLICATION_VM_STATE = "REPLICATION_VM_STATE";
	public static final String REPLICATION_COMPLETE = "REPLICATION_COMPLETE";
	public static final String REPLICATION_NO_BACKUP_CONF = "REPLICATION_NO_BACKUP_CONF";
	public static final String REPLICATION_FAIL_OPEN_REMOTE = "REPLICATION_FAIL_OPEN_REMOTE";
	public static final String REPLICATION_FAIL_GET_CONN = "REPLICATION_FAIL_GET_CONN";
	public static final String REPLICATION_GET_NEXT_SESSION="REPLICATION_GET_NEXT_SESSION";
	public static final String REPLICATION_CONVERSION_MODULE_FAIL="REPLICATION_CONVERSION_MODULE_FAIL";
	public static final String REPLICATION_CONVER_HYPERV_FAIL_UNEXPECTED = "REPLICATION_CONVER_HYPERV_FAIL_UNEXPECTED";
	public static final String REPLICATION_CONVER_ESX_FAIL_UNEXPECTED = "REPLICATION_CONVER_ESX_FAIL_UNEXPECTED";
	public static final String REPLICATION_FAIL_COMMON_FAILURE = "REPLICATION_FAIL_COMMON_FAILURE";
	public static final String REPLICATION_CONVERT_DISK_IMAGE_START = "REPLICATION_CONVERT_DISK_IMAGE_START";
	public static final String REPLICATION_CONVERT_DISK_IMAGE_COMPLETED = "REPLICATION_CONVERT_DISK_IMAGE_COMPLETED";
	public static final String REPLICATION_CONVERT_DISK_IMAGE_FAILED = "REPLICATION_CONVERT_DISK_IMAGE_FAILED";
	public static final String REPLICATION_CONVERT_NOT_SUFFICIENT_PERMISSION = "REPLICATION_CONVERT_NOT_SUFFICIENT_PERMISSION";
	public static final String REPLICATION_CONVERT_RESOURCE_POOL_NOT_EXIST = "REPLICATION_CONVERT_RESOURCE_POOL_NOT_EXIST";
	public static final String REPLICATION_CONVERT_FAIL_UPDATE_RESOURCE_POOL = "REPLICATION_CONVERT_FAIL_UPDATE_RESOURCE_POOL";
	public static final String REPLICATION_DEST_DOES_EXIST="REPLICATION_DEST_DOES_EXIST";
	
	public static final String REPLICATION_CREATE_BOOTABLESHAPSHOT_SUCCESS = "REPLICATION_CREATE_BOOTABLESHAPSHOT_SUCCESS";
	public static final String REPLICATION_CREATE_BOOTABLESHAPSHOT_FAIL = "REPLICATION_CREATE_BOOTABLESHAPSHOT_FAIL";
	public static final String REPLICATION_CREATE_BOOTABLESHAPSHOT_FAIL_JOB_SCRIPT_NOT_FOUND = "REPLICATION_CREATE_BOOTABLESHAPSHOT_FAIL_JOB_SCRIPT_NOT_FOUND";
	public static final String REPLICATION_MONITEE_INVALID_VDDK = "REPLICATION_MONITEE_INVALID_VDDK";
	public static final String REPLICATION_MONITOR_INVALID_VDDK = "REPLICATION_MONITOR_INVALID_VDDK";
	public static final String REPLICATION_FAIL_FOR_LICENSE_FAIL = "REPLICATION_FAIL_FOR_LICENSE_FAIL";
	public static final String REPLICATION_FAIL_LICENSE_NOT_CONNECT_EDGE = "REPLICATION_FAIL_LICENSE_NOT_CONNECT_EDGE";
	public static final String REPLICATION_FAIL_LICENSE_EDGE_ERROR = "REPLICATION_FAIL_LICENSE_EDGE_ERROR";
	public static final String REPLICATION_FAIL_LICENSE_NO_VSTORAGE_API = "REPLICATION_FAIL_LICENSE_NO_VSTORAGE_API";
	public static final String REPLICATION_FAIL_DATASTORE_CHANGE = "REPLICATION_FAIL_DATASTORE_CHANGE";
	public static final String REPLICATION_FAIL_IN_CHECK_VSTORAGE_LICENSE="REPLICATION_FAIL_IN_CHECK_VSTORAGE_LICENSE";
	public static final String REPLICATION_FAIL_FOR_UEFI="REPLICATION_FAIL_FOR_UEFI";
	public static final String REPLICATION_HYPERV_FAIL_FOR_UEFI="REPLICATION_HYPERV_FAIL_FOR_UEFI";
	public static final String REPLICATION_HYPERV_VM_UEFI="REPLICATION_HYPERV_VM_UEFI";
	
	public static final String REPLICATION_DEST_TYPE_HYPERV = "REPLICATION_DEST_TYPE_HYPERV";
	public static final String REPLICATION_DEST_TYPE_VMWARE_ESX = "REPLICATION_DEST_TYPE_VMWARE_ESX";
	public static final String REPLICATION_DEST_TYPE_VIRTUAL_CENTER = "REPLICATION_DEST_TYPE_VIRTUAL_CENTER";
	public static final String REPLICATION_DEST_TYPE_UNKNOWN = "REPLICATION_DEST_TYPE_UNKNOWN";
	
	public static final String REPLICATION_BACKUP_TO_SHARE_FOLDER = "REPLICATION_BACKUP_TO_SHARE_FOLDER";
	public static final String REPLICATION_BACKUP_TO_RPS = "REPLICATION_BACKUP_TO_RPS";
	public static final String REPLICATION_DEST_MONITOR_AS_PROXY = "REPLICATION_DEST_MONITOR_AS_PROXY";
	public static final String REPLICATION_DEST_MONITOR_NOT_AS_PROXY = "REPLICATION_DEST_MONITOR_NOT_AS_PROXY";

	public static final String VIRTUAL_CONVERSION_STARTED = "VIRTUAL_CONVERSION_STARTED";
	public static final String VIRTUAL_CONVERSION_FINISHED = "VIRTUAL_CONVERSION_FINISHED";
	public static final String VIRTUAL_CONVERSION_FAILED_GENERAL = "VIRTUAL_CONVERSION_FAILED_GENERAL";
	public static final String VIRTUAL_CONVERSION_FAILED_FOR_POWERON = "VIRTUAL_CONVERSION_FAILED_FOR_POWERON";
	public static final String VIRTUAL_CONVERSION_FAILED_FOR_NOSESSION = "VIRTUAL_CONVERSION_FAILED_FOR_NOSESSION";
	public static final String VIRTUAL_CONVERSION_FAILED_FOR_UNKNOWN_SMARTCOPY = "VIRTUAL_CONVERSION_FAILED_FOR_UNKNOWN_SMARTCOPY";
	public static final String VIRTUAL_CONVERSION_FAILED_SNAPSHOT = "VIRTUAL_CONVERSION_FAILED_SNAPSHOT";
	public static final String VIRTUAL_CONVERSION_PROVISION_POINT_START = "VIRTUAL_CONVERSION_PROVISION_POINT_START";
	public static final String VIRTUAL_CONVERSION_PROVISION_POINT_SMART_START="VIRTUAL_CONVERSION_PROVISION_POINT_SMART_START";
	public static final String VIRTUAL_CONVERSION_PROVISION_POINT_FINISH="VIRTUAL_CONVERSION_PROVISION_POINT_FINISH";
	public static final String VIRTUAL_CONVERSION_PROVISION_POINT_SMART_FINISH="VIRTUAL_CONVERSION_PROVISION_POINT_SMART_FINISH";
	
	public static final String REPLICATION_NO_SYSTEM_OR_BOOT_VOLUME = "REPLICATION_NO_SYSTEM_OR_BOOT_VOLUME";
	public static final String REPLICATION_SKIP_COPIED_SESSION = "REPLICATION_SKIP_COPIED_SESSION";
	public static final String REPLICATION_ADD_COPY_SESSION = "REPLICATION_ADD_COPY_SESSION";
	public static final String REPLICATION_OFFLINE_COPY_SESSION_CHAIN = "REPLICATION_OFFLINE_COPY_SESSION_CHAIN";
	public static final String REPLICATION_NO_BACKUP_SESSION = "REPLICATION_NO_BACKUP_SESSION";
	public static final String REPLICATION_FAIL_TO_GET_SOURCE_GUEST_OS = "REPLICATION_FAIL_TO_GET_SOURCE_GUEST_OS";
	public static final String REPLICATION_SMART_COPY_METHOD_UNKNOWN = "REPLICATION_SMART_COPY_METHOD_UNKNOWN";
	public static final String REPLICATION_CHECK_DESTINATIONSIZE_ERROR = "REPLICATION_CHECK_DESTINATIONSIZE_ERROR";
	public static final String REPLICATION_IS_CANCELED = "REPLICATION_IS_CANCELED";
	public static final String REPLICATION_SYSTEM_OR_BOOT_VOLUME_ON_DYNAMIC_DISK = "REPLICATION_SYSTEM_OR_BOOT_VOLUME_ON_DYNAMIC_DISK";
	public static final String AFRES_AFREPC_16389 = "AFRES_AFREPC_16389";
	public static final String AFRES_AFREPC_16388 = "AFRES_AFREPC_16388";
	public static final String AFRES_AFREPC_SKIP_VSB_FOR_FAILOVER = "AFRES_AFREPC_SKIP_VSB_FOR_FAILOVER";
	public static final String REPLICATION_FAILED_LOCK_SESSIONS = "REPLICATION_FAILED_LOCK_SESSIONS";
	public static final String REPLICATION_FAILED_LOCK_SESSIONS_WITH_DETAILS = "REPLICATION_FAILED_LOCK_SESSIONS_WITH_DETAILS";
	public static final String REPLICATION_FAILED_LOCK_SESSIONS_REASON_MERGE = "REPLICATION_FAILED_LOCK_SESSIONS_REASON_MERGE";
	public static final String REPLICATION_SESSIONS_ADRCONFIGURE = "REPLICATION_SESSIONS_ADRCONFIGURE";
	public static final String REPLICATION_SESSIONS_NO_ADRCONFIGURE = "REPLICATION_SESSIONS_NO_ADRCONFIGURE";
	public static final String REPLICATION_VM_NAME_PREEXIST = "REPLICATION_VM_NAME_PREEXIST";
	public static final String REPLICATION_FAILED_ADD_DISK="REPLICATION_FAILED_ADD_DISK";
	public static final String REPLICATION_FAILED_TAKE_SNAPSHOT="REPLICATION_FAILED_TAKE_SNAPSHOT";
	public static final String REPLICATION_FAILED_SAVE_SNAPSHOT_INFO="REPLICATION_FAILED_SAVE_SNAPSHOT_INFO";
	public static final String REPLICATION_FAILED_REPLICATION_SESSION="REPLICATION_FAILED_REPLICATION_SESSION";
	public static final String REPLICATION_EXCEPTION_REPLICATION_SESSION="REPLICATION_EXCEPTION_REPLICATION_SESSION";
	public static final String REPLICATION_FAILED_CREATE_JOBSCRIPT="REPLICATION_FAILED_CREATE_JOBSCRIPT";
	public static final String REPLICATION_SYSTEM_BOOT_VOLUME_ON_DIFF_DISK="REPLICATION_SYSTEM_BOOT_VOLUME_ON_DIFF_DISK";
	public static final String REPLICATION_HOT_ADD_MODE_FAIL="REPLICATION_HOT_ADD_MODE_FAIL";
	public static final String REPLICATION_FAIL_AUTHENTICATE_MONITOR="REPLICATION_FAIL_AUTHENTICATE_MONITOR";
	public static final String REPLICATION_SESSION_PASSWORD_FILE_DAMAGE="REPLICATION_SESSION_PASSWORD_FILE_DAMAGE";
	public static final String REPLICATION_EXITS_INCREMENTAL_NOTFINISH="REPLICATION_EXITS_INCREMENTAL_NOTFINISH";
	public static final String REPLICATION_SUBMIT_INCREMENTAL_BACKUP = "REPLICATION_SUBMIT_INCREMENTAL_BACKUP";
	public static final String REPLICATION_CONVERSION_PAUSED = "REPLICATION_CONVERSION_PAUSED";
	public static final String REPLICATION_CONVERSION_RESUMED = "REPLICATION_CONVERSION_RESUMED"; 
	public static final String REPLICATION_REPORT_MONITOR="REPLICATION_REPORT_MONITOR";
	public static final String REPLICATION_FAILED_CREATE_BITMAP= "REPLICATION_FAILED_CREATE_BITMAP";
	public static final String REPLICATION_CONVERSION_BEGIN_TO_CANCEL = "REPLICATION_CONVERSION_BEGIN_TO_CANCEL";
	public static final String REPLICATION_CONVERSION_CANCEL_FAILED = "REPLICATION_CONVERSION_CANCEL_FAILED";
	public static final String REPLICATION_CONVERSION_CANCEL_BEFORE_UNDEPLOY = "REPLICATION_CONVERSION_CANCEL_BEFORE_UNDEPLOY";
	public static final String REPLICATION_CONVERSION_DELETE_HYPERV_SNAPSHOT = "REPLICATION_CONVERSION_DELETE_HYPERV_SNAPSHOT";
	public static final String REPLICATION_CONVERSION_FAIL_TO_CONNECT_HOST = "REPLICATION_CONVERSION_FAIL_TO_CONNECT_HOST";
	public static final String REPLICATION_CONVERSION_FAIL_TO_GET_DISK_SIG = "REPLICATION_CONVERSION_FAIL_TO_GET_DISK_SIG";
	public static final String REPLICATION_CONVERSION_FAIL_TO_CONNECT_HYPERV = "REPLICATION_CONVERSION_FAIL_TO_CONNECT_HYPERV";
	public static final String REPLICATION_CONVERSION_FAIL_TO_GET_SNAPSHOT = "REPLICATION_CONVERSION_FAIL_TO_GET_SNAPSHOT";
	
	public static final String REPLICATION_DESTINATION="REPLICATION_DESTINATION";
	public static final String REPLICATION_DESTINATION_VOLUME="REPLICATION_DESTINATION_VOLUME";
	public static final String REPLICATION_DESTINATION_TRESHOLD = "REPLICATION_DESTINATION_TRESHOLD";
	public static final String REPLICATION_DEST_TOTAL_SPACE="REPLICATION_DEST_TOTAL_SPACE";
	public static final String REPLICATION_DEST_FREE_SPACE="REPLICATION_DEST_FREE_SPACE";
	public static final String REPLICATION_DEST_EXCEED_LIMIT = "REPLICATION_DEST_EXCEED_LIMIT";
	public static final String REPLICATION_DEST_BLOCK_SIZE="REPLICATION_DEST_BLOCK_SIZE";
	public static final String REPLICATION_BOOT_VOLUME_ON_DYNAMIC_DISK="REPLICATION_BOOT_VOLUME_ON_DYNAMIC_DISK";
	
	public static final String REPLICATION_FIND_EXISTING_VM="REPLICATION_FIND_EXISTING_VM";
	public static final String REPLICATION_CREATE_NEW_VM="REPLICATION_CREATE_NEW_VM";
	
	public static final String REPLICATION_FAIL_DELETE_SNAPSHOT="REPLICATION_FAIL_DELETE_SNAPSHOT";
	
	public static final String REPLICATION_FAIL_UPDATE_HOTADD_MBR="REPLICATION_FAIL_UPDATE_HOTADD_MBR";
	public static final String REPLICATION_BACKUP_FOR_SMART_COPY="REPLICATION_BACKUP_FOR_SMART_COPY";
	public static final String REPLICATION_HYPERV_EXIT_CODE="REPLICATION_HYPERV_EXIT_CODE";
	
	public static final String REPLICATION_HAERT_BEAT_TIMEOUT_SECONDS = "REPLICATION_HAERT_BEAT_TIMEOUT_SECONDS";
	public static final String REPLICATION_HAERT_BEAT_TIMEOUT_NAME = "REPLICATION_HAERT_BEAT_TIMEOUT_NAME";
	public static final String HEART_BEAT_FREQUENCY = "HEART_BEAT_FREQUENCY";
	
	public static final String REPLICATION_DOWNLOAD_FAIL = "REPLICATION_DOWNLOAD_FAIL";
	public static final String VDDK_ENFORCED_NBD = "VDDK_ENFORCED_NBD";
	
	private static final String REPLICATION_MONITORSERVICE_ERROR_PREX="REPLICATION_MONITORSERVICE_ERROR_";
	
	public static final String REPLICATION_FAILTO_PREPAREFORMANUALCONVERSION = "REPLICATION_FAILTO_PREPAREFORMANUALCONVERSION";
	public static final String REPLICATION_FAILTO_CREATEVSSSNAPSHOT = "REPLICATION_FAILTO_CREATEVSSSNAPSHOT";
	public static final String REPLICATION_FAILTO_GETSESSIONVOLUMESFROMVSSSNAPSHOT = "REPLICATION_FAILTO_GETSESSIONVOLUMESFROMVSSSNAPSHOT";
	public static final String REPLICATION_FAILED_WITH_UNKNONWREASON = "REPLICATION_FAILED_WITH_UNKNONWREASON";
	public static final String REPLICATION_CANCELLED_DUETO_RHASYNC = "REPLICATION_CANCELLED_DUETO_RHASYNC";
	public static final String REPLICATION_CANCELLED_DUETO_UNKNOWNRHASTATE = "REPLICATION_CANCELLED_DUETO_UNKNOWNRHASTATE";
	public static final String REPLICATION_CANCELLED_DUETO_GETTINGRHASTATEFAILED = "REPLICATION_CANCELLED_DUETO_GETTINGRHASTATEFAILED";
	public static final String REPLICATION_RHASENARIO_IS_RUNNING="REPLICATION_RHASENARIO_IS_RUNNING";
	public static final String REPLICATION_RHASENARIO_IS_STOPPED="REPLICATION_RHASENARIO_IS_STOPPED";
	public static final String REPLICATION_RHASENARIO_IS_SYNCHRONIZING="REPLICATION_RHASENARIO_IS_SYNCHRONIZING";
	public static final String REPLICATION_RHASENARIO_STATEIS_UNKNOWN="REPLICATION_RHASENARIO_STATEIS_UNKNOWN";

	public static final String REPLICATION_FAILTO_ACCESS_SESSION = "REPLICATION_FAILTO_ACCESS_SESSION";
	public static final String REPLICATION_FAILTO_PARSE_ADRCONFIGURE = "REPLICATION_FAILTO_PARSE_ADRCONFIGURE";
	
	public static final String REPLICATION_FAILTO_VALIDATE_ADMIN_ACCOUNT = "REPLICATION_FAILTO_VALIDATE_ADMIN_ACCOUNT";
	public static final String REPLICATION_FAILTO_VALIDATE_ADMIN_ACCOUNT_WITH_EDGEHOST = "REPLICATION_FAILTO_VALIDATE_ADMIN_ACCOUNT_WITH_EDGEHOST";
	public static final String REPLICATION_FAILTO_VAIIDATE_SESSION_PASSWORD = "REPLICATION_FAILTO_VAIIDATE_SESSION_PASSWORD";
	
	public static final String REPLICAION_LICENSE_RVCM_FAILTO_CHECK_MACHINETYPE = "REPLICAION_LICENSE_RVCM_FAILTO_CHECK_MACHINETYPE";
	public static final String REPLICATION_FAIL_GET_SESSIONS = "REPLICATION_FAIL_GET_SESSIONS";
	public static final String REPLICATION_FAIL_CONNECT_BACKUP_DEST = "REPLICATION_FAIL_CONNECT_BACKUP_DEST";

	//VCM NON PROXY
	public static final String AFRES_VCM_NON_PROXY_PREFIX = "AFRES_AFREPC_";
	public static final String AFRES_VCM_NON_PROXY_NETWORK_ERROR = AFRES_VCM_NON_PROXY_PREFIX + 20000;
	public static final String AFRES_VCM_NON_PROXY_VMDK_ERROR = AFRES_VCM_NON_PROXY_PREFIX + 21000;
	public static final String AFRES_VCM_NON_PROXY_DISK_ERROR = AFRES_VCM_NON_PROXY_PREFIX + 22000;
	public static final String AFRES_VCM_NON_PROXY_CREDENTIAL_ERROR = AFRES_VCM_NON_PROXY_PREFIX + 23000;
	public static final String AFRES_VCM_NON_PROXY_INTERNAL_ERROR = AFRES_VCM_NON_PROXY_PREFIX + 25000;
	public static final String AFRES_VCM_NON_PROXY_SPACE_ERROR = AFRES_VCM_NON_PROXY_PREFIX + 26000;
	public static final String AFRES_VCM_NON_PROXY_VMDK_FILE_ERROR = AFRES_VCM_NON_PROXY_PREFIX + 27000;
	public static final String AFRES_VCM_NON_PROXY_VMDK_LICENSE_ERROR = AFRES_VCM_NON_PROXY_PREFIX + 28000;
	
	public static final String POWERONVM = "POWERONVM";
	public static final String POWEROFFVM = "POWEROFFVM";
	public static final String REPLICATION_TRY_ADVANCED_MODE = "REPLICATION_TRY_ADVANCED_MODE";
	
	
	// Just for InstantVM usage.
	public static final String IVM_JOB_PROCESS_CRASH = "IVM_JOB_PROCESS_CRASH";

	private static ResourceBundle labels;

	static {
		labels = ResourceBundle.getBundle("com.ca.arcflash.webservice.replication.replicatonRes", DataFormatUtil.getServerLocale() );
	}
	
	public static String getResource(String key){
		return labels.getString(key);
	}
	public static String getResource(String key,String... pars){
		
		String labelValue= labels.getString(key);
		return String.format(labelValue, (Object[])pars);
		
	}
	public static String getMonitorServiceErrorString(String errorCode,String... mesg){
		try{
		String labelValue= labels.getString(REPLICATION_MONITORSERVICE_ERROR_PREX+errorCode);
		if(-1!=labelValue.indexOf("%s") && mesg!=null);
			labelValue= String.format(labelValue, (Object[])mesg);
		return labelValue;
		}catch(MissingResourceException m){
			return null;
		}
	}
	
	public static String getReplicationDestType(Protocol ptl) {
		if(ptl == Protocol.HeartBeatMonitor) {
			return getResource(REPLICATION_DEST_TYPE_HYPERV);
		}
		else if(ptl == Protocol.VMwareESX)
			return getResource(REPLICATION_DEST_TYPE_VMWARE_ESX);
		else if(ptl == Protocol.VMwareVCenter)
			return getResource(REPLICATION_DEST_TYPE_VIRTUAL_CENTER);
		else
			return getResource(REPLICATION_DEST_TYPE_UNKNOWN);
	}
}
