/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ca_edge_srm */

#ifndef _Included_com_ca_arcflash_webservice_edge_SrmJniCaller
#define _Included_com_ca_arcflash_webservice_edge_SrmJniCaller
#ifdef __cplusplus
extern "C" {
#endif
    /*
    * Class:     com_ca_Edge_SRM
    * Method:    getSysHardwareInfo
    * Signature: ()Ljava/lang/String;
    */
	
    JNIEXPORT jstring JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_getSysHardwareInfo
        (JNIEnv *, jclass);

    /*
    * Class:     com_ca_edge_srm
    * Method:    getSysSoftwareInfo
    * Signature: ()Ljava/lang/String;
    */
    JNIEXPORT jstring JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_getSysSoftwareInfo
        (JNIEnv *, jclass);

    /*
    * Class:     com_ca_edge_srm
    * Method:    getServerPkiInfo
    * Signature: (I)Ljava/lang/String;
    */
    JNIEXPORT jstring JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_getServerPkiInfo
        (JNIEnv *, jclass, jint);

    /*
    * Class:     com_ca_edge_srm
    * Method:    isARCInstalled
    * Signature: ()Z
    */
    JNIEXPORT jboolean JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_isARCInstalled
        (JNIEnv *, jclass);

    /*
    * Class:     com_ca_edge_srm
    * Method:    startPkiMonitor
    * Signature: ()Z
    */
    JNIEXPORT jboolean JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_startPkiMonitor
        (JNIEnv *, jclass);

    /*
    * Class:     com_ca_edge_srm
    * Method:    stopPkiMonitor
    * Signature: ()Z
    */
    JNIEXPORT jboolean JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_stopPkiMonitor
        (JNIEnv *, jclass);

	/*
	* Class:     com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller
	* Method:    isSRMEnabled
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_isSRMEnabled
		(JNIEnv *, jclass);
	/*
	* Class:     com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller
	* Method:    savePkiAlertPolicy
	* Signature: (Lcom/ca/arcflash/webservice/edge/srmagent/SRMPkiAlertSetting;)I
	*/
	JNIEXPORT jint JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_savePkiAlertPolicy
	(JNIEnv *, jclass, jobject);

	/*
	* Class:     com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller
	* Method:    getAlertRecords
	* Signature: ([I[Ljava/lang/String;[I[II)I
	* Parameter: jintArray - in/out used to store the alert types
	*			 jobjectArray - in/out used to store the alert headers
	*			 jintArray - in/out used to store the thresholds
	*			 jintArray - in/out used to store current utilizations
	*			 jint - in used to specify the array size
	*/
	JNIEXPORT jint JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_getAlertRecords
	(JNIEnv *, jclass, jintArray, jobjectArray, jintArray, jintArray, jint);

	/*
	* Class:     com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller
	* Method:    enableAlert
	* Signature: (Z)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_enableAlert
	(JNIEnv *, jclass, jboolean);

    /*
    * Class:     com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller
    * Method:    enablePkiUtl
    * Signature: (Z)Z
    */
    JNIEXPORT jboolean JNICALL Java_com_ca_arcflash_webservice_edge_srmagent_SrmJniCaller_enablePkiUtl
        (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
