#pragma once 

typedef enum _AF_DISK_TYPE {
				AF_DISK_UNKNOWN = 0,
				AF_DISK_RAW,
				AF_DISK_MBR_BASIC,
				AF_DISK_MBR_DYNAMIC,
				AF_DISK_GPT_BASIC,
				AF_DISK_GPT_DYNAMIC
} AF_DISK_TYPE;

typedef enum _AF_VOLUME_TYPE {
				AF_VOLUME_UNKNOWN = 0,
				AF_VOLUME_SIMPLE,
				AF_VOLUME_MIRROR,
				AF_VOLUME_SPANNED,
				AF_VOLUME_STRIPED,
				AF_VOLUME_RAID5
} AF_VOLUME_TYPE;
