#pragma once 
#include "AFFlt.h"

#define AFFLTMGR_MODULE_NAME   L"AFFltMgr.dll"

DWORD WINAPI AFFltEnableMonitorForSnapshot(LPCWSTR lpClassName);
typedef  DWORD (WINAPI *AFFLTENABLEMONITORFORSNAPSHOT_PFN)(LPCWSTR lpClassName);
#define  AFFLTENABLEMONITORFORSNAPSHOT_SIG  "AFFltEnableMonitorForSnapshot"

DWORD WINAPI AFFltGetBlockSize(HANDLE hVolume, DWORD* pdwSize);
typedef DWORD (WINAPI *AFFLTGETBLOCKSIZE_PFN)(HANDLE hVolume, DWORD* pdwSize);
#define AFFLTGETBLOCKSIZE_SIG  "AFFltGetBlockSize"

DWORD WINAPI AFFltPrepareForSnapshot(HANDLE hVolume);
typedef DWORD (WINAPI *AFFLTPREPAREFORSNAPSHOT_PFN)(HANDLE hVolume);
#define AFFLTPREPAREFORSNAPSHOT_SIG "AFFltPrepareForSnapshot"

DWORD WINAPI AFFltGetBitmap(IN HANDLE hVolume, IN PSTARTING_LCN_INPUT_BUFFER pStartLcn, IN DWORD dwInputSize, OUT PVOLUME_BITMAP_BUFFER pBitmap, IN DWORD dwOutputSize, OUT DWORD* pdwReturnSize);
typedef DWORD(WINAPI *AFFLTGETBITMAP_PFN)(IN HANDLE hVolume, IN PSTARTING_LCN_INPUT_BUFFER pStartLcn, IN DWORD dwInputSize, OUT PVOLUME_BITMAP_BUFFER pBitmap, IN DWORD dwOutputSize, OUT DWORD* pdwReturnSize);
#define AFFLTGETBITMAP_SIG "AFFltGetBitmap"

DWORD WINAPI AFFltSynSnapshotChangeBitmapToVolume(HANDLE hVolume, PVOLUME_BITMAP_BUFFER pBitmap, DWORD dwSize);
typedef DWORD(WINAPI *AFFLTSYNSNAPSHOTCHANGEBITMAPTOVOLUME_PFN)(HANDLE hVolume, PVOLUME_BITMAP_BUFFER pBitmap, DWORD dwSize);
#define AFFLTSYNSNAPSHOTCHANGEBITMAPTOVOLUME_SIG "AFFltSynSnapshotChangeBitmapToVolume"

DWORD WINAPI AFFltReplicationSuccess(HANDLE hVolume);
typedef DWORD (WINAPI *AFFltReplicationSuccess_PFN)(HANDLE hVolume);
#define AFFLTREPLICATIONSUCCESS_SIG "AFFltReplicationSuccess"

DWORD WINAPI AFFltDisableMonitorForSnapshot(LPCWSTR lpClassName);
typedef DWORD (WINAPI *AFFLTDISABLEMONITORFORSNAPSHOT_PFN)(LPCWSTR lpClassName);
#define AFFLTDISABLEMONITORFORSNAPSHOT_SIG "AFFltDisableMonitorForSnapshot"

DWORD WINAPI AFFltStopMonitorVolume(HANDLE hVolume);
typedef DWORD (WINAPI*AFFLTSTOPMONITORVOLUME_PFN)(HANDLE hVolume);
#define AFFLTSTOPMONITORVOLUME_SIG "AFFltStopMonitorVolume"

BOOL  WINAPI AFCanBLIDriverWork();
typedef  BOOL (WINAPI *AFCANBLIDRIVERWORK_PFN)();
#define  AFCANBLIDRIVERWORK_SIG "AFCanBLIDriverWork"