//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by E:\project\ARCserve Flash\Native\RCModules\SETUP\AgentDeployRes.dll\MasterSetup_e.rc
//
#define IDS_SETUPWIZARD                 1
#define IDS_HEADERTITLE                 2
#define IDS_LICENSEHEADERTITLE          2
#define IDS_DEPLOY_HIGHER_VER           2
#define IDS_HEADERSUBTITLE              3
#define IDS_LICENSEHEADERSUBTITLE       3
#define IDS_RUN_AGENTDEPLOY             3
#define IDS_CHOICEPRODUCTHEADERTITLE    4
#define IDS_ADT_PAUSE_WARN              4
#define IDS_CHOICEPRODUCTHEADERSUBTITLE 5
#define IDS_RMT_CLUSTER_WARN            5
#define IDS_COPYFILEHEADERTITLE         6
#define IDS_COPYFILEHEADERSUBTITLE      7
#define IDS_POSTCONFIGHEADERTITLE       8
#define IDS_PRODUCT_PRECOMPONENT        8
#define IDS_POSTCONFIGHEADERSUBTITLE    9
#define IDS_SERVER_SERVICE_DOWN         9
#define IDS_REVIEWHEADERTITLE           10
#define IDS_AD_NOTOPERATIONAL           10
#define IDS_REVIEWHEADERSUBTITLE        11
#define IDS_AD_INVALID_USER             11
#define IDS_SETUP_CANCEL                12
#define IDS_LICENSE_NEXT_BUTTON_TITLE   13
#define IDS_AD_PREVILEDGE               13
#define IDS_INSTALL                     14
#define IDS_CREMSLOTFAIL                15
#define IDM_ABOUTBOX                    0x0010
#define IDS_FINISH                      16
#define IDS_SECOND_INSTANCE             17
#define IDS_PRODUCT_WIZARD              18
#define IDS_LICENSE_CANCEL_BUTTON_TITLE 19
#define IDS_AD_UNKNOWN_ERR              19
#define IDS_INSTCOMPONENTS_NONE         20
#define IDS_INSTCOMPONENTS_ALL          21
#define IDS_INSTCOMPONENTS_SUBTITLE1    22
#define IDS_INSTCOMPONENTS_SUBTITLE2    23
#define IDS_CLOSE_SERVICEMGR_WARN       24
#define IDS_CLOSEJOBSERVICE_WARN        25
#define IDS_RESTART_UNIAGENT_WARN       26
#define IDS_SQLE_DBSIZE_WARN            27
#define IDS_SQLE_INST_CD1_WARN          28
#define IDS_HELP                        29
#define IDS_STRING_HOSTNAME             30
#define IDS_STRING_USERNAME             31
#define IDS_STRING_PASSWORD             32
#define IDS_STRING_STATUS               33
#define IDS_NEW_ITEM_HOST               34
#define IDS_HOST_STATUS_PENDING         35
#define IDS_HOST_STATUS_DOING           36
#define IDS_HOST_STATUS_SUCCESS         37
#define IDS_HOST_STATUS_FAIL            38
#define IDS_NAV_METHOD                  39
#define IDS_HEADER_METHOD               40
#define IDS_NAV_PRODSEL                 41
#define IDS_HEADER_PRODSEL              42
#define IDS_NAV_HOST                    43
#define IDS_HEADER_HOST                 44
#define IDS_NAV_MESSAGE                 45
#define IDS_HEADER_MESSAGE              46
#define IDS_NAV_SUMMARY                 47
#define IDS_HEADER_SUMMARY              48
#define IDS_NAV_STATUS                  49
#define IDS_HEADER_STATUS               50
#define IDS_NAV_REPORT                  51
#define IDS_HEADER_REPORT               52
#define IDS_AGENTDEPLOY_WELCOME         53
#define IDS_AGENTDEPLOY_AUTOUPG         54
#define IDS_AGENTDEPLOY_CUSTOM          55
#define IDS_STRING_AGENTS               56
#define IDS_WAIT_MSG_VERIFY             57
#define IDS_ALLOW_REBOOT                58
#define IDS_DEPLOY_AUTO_AGENTNOTFOUND   59
#define IDS_DEPLOY_AUTO_MISMATCH        60
#define IDS_REBOOT_REQUIRED             61
#define IDS_HOST_STATUS_COMPLETED       62
#define IDS_DEPLOY_HIDE_DETAIL          63
#define IDS_DEPLOY_SHOW_DETAIL          64
#define IDS_DEPLOY_ALREADYINSTLL        65
#define IDS_HOST_REBOOT_IGNORED         66
#define IDS_INST_INITIALIZE             67
#define IDS_DEPLOY_PAUSED               68
#define IDS_HOST_STATUS_SKIP            69
#define IDS_RMT_REBOOT_WARN             70
#define IDS_STAT_TOTAL                  71
#define IDS_STAT_INSTALLING             72
#define IDS_STAT_PAUSED                 73
#define IDS_STAT_WAITING                74
#define IDS_STAT_COMPLETED              75
#define IDS_STAT_FAILED                 76
#define IDS_DEPLOY_MAXHOSTS_LIMIT       77
#define IDS_DEPLOY_MULTIAGENTS_MORE     78
#define IDS_DEPLOY_PAUSE                79
#define IDS_DEPLOY_RESUME               80
#define IDS_DEPLOY_MULTIINSTANCE_WARN   81
#define IDS_DEPLOY_ARCSERVE             82
#define IDS_DEPLOY_LIST                 83
#define IDS_RESTART_HOSTS               84
#define IDS_AGENTDEPLOY_NAME            85
#define IDS_DISPLAYRESOLUTION_WARNING   86
#define IDS_HOSTNAME_LEN_EXCCEED        87
#define IDS_AGENTDEPLOY_AUTOUPG_DISABLE 88
#define IDS_EMPTY_HOSTNAME_WARN         89
#define IDS_ADT_WARN_REMOVE_NOHOST      90
#define IDS_AGENTDEPLOY_VM              91
#define IDS_STRING_INFOMATION           92
#define IDS_NEEDCFG_INFO                93
#define IDS_CHECKADMINRIGHTS_FAIL       94
#define IDS_OS_CHECK_FAIL               95
#define IDS_LOGIN_INVALID_CRED          96
#define IDS_LOGIN_CONNECT_ERROR         97
#define IDS_DEPLOY_UNSUPPORT_PLATFORM   98
#define IDS_ADT_PACKAGE_DAMAGED         99
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_ILLEGAL_CHAR                102
#define IDB_BANNER256                   103
#define IDB_BANNER16                    104
#define IDB_WATERMARK16                 105
#define IDB_WATERMARK256                106
#define IDC_BIGBOLDTITLE                107
#define IDC_BOLDTITLE                   108
#define IDS_INST_UPG_SERVTYPE_TITLE     108
#define IDS_INST_SERVTYPE_COMMON_MSG    109
#define IDS_UPG_NOTIFY_SANPRIMARY_TO_PRIMARY 110
#define IDC_TRANSPARENT3                111
#define IDS_UPG_NOTIFY_SANDISTRIBUTE_TO_MEMBER 111
#define IDC_LIST1                       112
#define IDC_LIST_STATUS                 112
#define IDS_UPG_NOTIFY_RCDBMEMBER_TO_PRIMARY 112
#define IDC_LIST_HOST                   112
#define IDC_SUMMARY_LIST                112
#define IDC_LIST_EXCH                   112
#define IDC_BUTTON1                     113
#define IDC_BTN_SETTING                 113
#define IDC_BTN_OK                      113
#define IDC_BTN_BROWSE                  113
#define IDC_OK                          113
#define IDC_HELPBUTTON                  113
#define IDS_UPG_NOTIFY_RCDBMEMBER_TO_STANDALONE 113
#define IDC_BUTTON_REFRESH              113
#define IDC_BTN_CANCEL                  114
#define IDS_UPG_NOTIFY_RCDBMEMBER_TO_MEMBER 114
#define IDC_BTN_PAUSE                   114
#define IDS_UPG_NOTIFY_RCDBSERVER_TO_PRIMARY 115
#define IDC_BUTTON3                     115
#define IDC_BTN_RESUME                  115
#define IDC_BTN_EXPORT                  115
#define IDD_INTRO_NEW                   116
#define IDS_UPG_NOTIFY_RCDBSERVER_TO_STANDALONE 116
#define IDD_INTERIOR1_NEW               117
#define IDS_UPG_NOTIFY_RCDBSERVER_TO_MEMBER 117
#define IDD_INTERIOR2_NEW               118
#define IDS_UPG_NOTIFY_PRIMARY_TO_PRIMARY 118
#define IDD_COMPLETION_NEW              119
#define IDS_UPG_NOTIFY_PRIMARY_TO_STANDALONE 119
#define IDS_UPG_NOTIFY_PRIMARY_TO_MEMBER 120
#define IDS_UPG_NOTIFY_MEMBER_TO_MEMBER 121
#define IDS_UPG_NOTIFY_MEMBER_TO_STANDALONE 122
#define IDS_UPG_NOTIFY_MEMBER_TO_PRIMARY 123
#define IDS_UPG_WARNING_HYPERLINK       124
#define IDS_UPG_NOTIFY_WARN1_MSG4       125
#define IDS_UPG_NOTIFY_WARN2_MSG7       126
#define IDS_UPG_NOTIFY_WARN2_MSG8       127
#define IDR_MAINFRAME                   128
#define IDS_UPG_NOTIFY_WARN2_MSG9       128
#define IDD_SETUP_LICENSE               129
#define IDS_UPG_NOTIFY_SUGGESTION_MSG10 129
#define IDS_UPG_NOTIFY_SUGGESTION_MSG11 130
#define IDD_SETUP_COPYFILE              131
#define IDS_UPG_NOTIFY_SUGGESTION_MSG12 131
#define IDD_SETUP_POST_CONFIG           132
#define IDS_UPG_NOTIFY_SUGGESTION_MSG13 132
#define IDS_UPG_NOTIFY_SUGGESTION_MSG14 133
#define IDB_CHECKBOX                    134
#define IDS_UPG_NOTIFY_SUGGESTION_MSG15 134
#define IDB_PRODUCT                     135
#define IDS_UPG_NOTIFY_SUGGESTION_MSG17 135
#define IDS_UPG_NOTIFY_WARN_TITLE       136
#define IDD_SETUP_SELECT_LANG           137
#define IDS_UPG_NOTIFY_SUGGESTION_TITLE 137
#define IDB_ARCSERVE                    138
#define IDS_REMOTE_UPGRADE_NOTSUPPORT   138
#define IDB_BLOCK_BAB                   139
#define IDD_SETUP_SETTING               139
#define IDS_WARNING_PAGE_TITLE          139
#define IDB_WIZARD_BAB                  140
#define IDS_WARNING_PAGE_SUBTITLE       140
#define IDB_BITMAP1                     141
#define IDS_UPGWARNDLG_TEMPLATE_WARNING 141
#define IDB_BLANK                       142
#define IDS_UPGWARNDLG_TEMPLATE_SUGGESTION 142
#define IDC_RADIO_LANGUAGE1             143
#define IDS_ICFFILE_OVERWRITE           143
#define IDC_RADIO_LANGUAGE2             144
#define IDD_DIALOG1                     144
#define IDS_CAROOT_EMPTYPWD_WARN        144
#define IDC_RADIO_LANGUAGE3             145
#define IDS_WARNING_JREINST_MSG         145
#define IDC_RADIO_LANGUAGE4             146
#define IDB_NET_TREE                    146
#define IDS_WARNING_MDACINST_MSG        146
#define IDC_RADIO_LANGUAGE5             147
#define IDB_COMPUTER_SM                 147
#define IDS_WARNING_INSTALLERINST_MSG   147
#define IDB_BANNER257                   148
#define IDS_WARNING_VCREDISTRIBUTEINST_MSG 148
#define IDD_SETUP_STATUS_MONITOR        149
#define IDS_WARN_CLIENTAGENT_UNSELECT   149
#define IDD_SETUP_SELECT_TYPE           150
#define IDS_WARN_CPSAN_UPGRADE          150
#define IDS_ERROR_BASE_MGR              151
#define IDS_WARN_MGR_UNSELECT           151
#define IDD_SETUP_LAUNCH                152
#define IDS_ERRMSG_DUPPATH_FORDIFFPRODUCTS 152
#define IDM_PROD                        153
#define IDS_MULTISTRIP_WARN_UPG         153
#define IDS_RSP_UPG2PRIMARY_WARN        154
#define IDC_MY_HAND                     155
#define IDS_RSP_UPG2STDORMEMBER_WARN    155
#define IDS_RSP_UPG_MULTISTRIPE_WARN    156
#define IDB_RELNOTE                     157
#define IDS_RSP_UPG_SANPRIMARY_WARN     157
#define IDB_DOC                         158
#define IDS_UPG_REMOTE_WARN             158
#define IDD_DLG_DRIVE_INFO              159
#define IDS_UPG_SQL2SQLE_WARN           159
#define IDS_UPGWARNDLG_SUBTITLE         160
#define IDD_RMT_SETPATH                 161
#define IDS_MDAC_COMPONENT              161
#define IDD_SETUP_COPYFILE_LOCAL        162
#define IDS_MSINSTALLER_COMPONENT       162
#define IDD_SETUP_CHS_PROD_WIZ          163
#define IDS_SQLE_COMPONENT              163
#define IDS_DOTNETFRAMEWORK_COMPONENT   164
#define IDD_SETUP_SETTING_L             165
#define IDS_VC2005SP1_COMPONENT         165
#define IDS_JRE_COMPONENT               166
#define IDC_RADIO_EX                    167
#define IDS_INST_COMPONENTS_TITLE       167
#define IDC_RADIO_CU                    168
#define IDB_WIZ97_BANNER256             169
#define IDB_WIZ97_BANNER16              170
#define IDC_BANNER_LN                   171
#define IDC_BMP_BACKGROUND              172
#define IDC_BANNER_LN2                  172
#define IDC_SUMMARY_TITLE               173
#define IDD_SETUP_SELECT_TYPE_OLD       174
#define IDD_WAIT_MESSAGE                175
#define IDI_SERVICE                     176
#define IDB_MESSAGE_TYPE                177
#define IDD_LANGUAGEDLG                 178
#define IDD_SETUP_SELECT_LIC_REG        178
#define IDI_ICON1                       178
#define IDI_ICON_RSA                    178
#define IDC_USE_TRIAL                   180
#define IDD_SETUP_INSTALLINFO           180
#define IDC_USE_KEY                     181
#define IDC_LICKEY1                     182
#define IDC_LICKEY2                     183
#define IDD_UPG_WARNING                 183
#define IDC_LICKEY3                     184
#define IDD_INST_SERVTYPE_NEW           184
#define IDC_LICKEY4                     185
#define IDC_LICKEY5                     186
#define IDB_TITLE_BITMAP                187
#define IDD_INST_SERVTYPE_NEW_UPG       187
#define IDS_OK                          188
#define IDB_CALOGO                      189
#define IDS_OS_CHECK_WARNING_WINXPBELOW 190
#define IDD_UPG_WARNING_WIZ             191
#define IDD_INSTALL_COMPONENTS_WIZ      192
#define IDD_UPG_WARNING_WIZ1            193
#define IDD_WARNSUMMARY_PAGE            193
#define IDB_INST_COMPONENT              194
#define IDB_BITMAP2                     201
#define IDB_WARN_BITMAP                 201
#define IDB_STANDALONE                  203
#define IDB_MANAGER                     204
#define IDB_MEMBER                      205
#define IDB_PRIMARY                     206
#define IDB_CUSTOM                      207
#define IDS_SINST_NOT_SUPPORT           208
#define IDB_BITMAP3                     209
#define IDB_BITMAP_STATUS               209
#define IDD_PAGE_SELECT_COMPUTER        210
#define IDB_BITMAP4                     211
#define IDB_HOST                        211
#define IDR_SELHOSTS_MENU               212
#define IDB_HEAD_CHECKBOX               213
#define IDD_PAGE_SELECT_PRODUCTS        214
#define IDD_PAGE_SELECT_SERVER_TYPE     215
#define IDD_PAGE_SELECT_INSTALL_TYPE    216
#define IDD_STATUS_PANEL                217
#define IDD_PAGE_SELECT_SERVER_TYPE1    218
#define IDD_PAGE_SELECT_UPGRADE_SERVER_TYPE 218
#define IDS_REQUIRE_REBOOT              218
#define IDD_DEPLOY_CHS_PROD_WIZ         219
#define IDB_METHOD_AUTO                 219
#define IDD_DEPLOY_SETUP_SETTING        220
#define IDB_DEPLOY_CUSTOM               220
#define IDB_METHOD_CUSTOM               220
#define IDD_WARNSUMMARY_PAGE1           221
#define IDD_DEPLOY_WARNSUMMARY_PAGE     221
#define IDD_DEPLOY_AUTOUPG_PRODSEL      223
#define IDD_AUTOUPG_SELECT_COMPUTER     224
#define IDD_DEPLOY_SETUP_SUMMARY        225
#define IDR_AGENT11                     225
#define IDD_DEPLOY_REBOOT_CONFIRM       226
#define IDI_AGENT1                      226
#define IDI_AGENT2                      227
#define IDI_AGENT3                      228
#define IDI_AGENT4                      229
#define IDI_AGENT5                      230
#define IDI_AGENT6                      231
#define IDI_AGENT7                      232
#define IDI_AGENT9                      233
#define IDB_MESSAGE_ICONS               234
#define IDS_MSG_VERIFY_FINISH           235
#define IDD_DEPLOY_METHOD_PAGE_EX       236
#define IDD_PAGE_SELECT_COMPUTER_VM     237
#define IDB_METHOD_VM                   238
#define IDD_DEPLOY_EXCH                 238
#define IDD_PAGE_LOGIN                  239
#define IDC_EDIT1                       1000
#define IDC_LICENSE_DESCRIPTION         1000
#define IDC_EDIT_DESCRIPTION            1000
#define IDC_USER_NAME                   1000
#define IDC_ICF_PATH                    1000
#define IDC_EDIT_PATH_RMT               1000
#define IDC_EDIT_HOST_FILE              1000
#define IDC_EDIT_AD                     1000
#define IDC_RADIO_ACCEPT_LICENSE        1001
#define IDC_RADIO_DO_NOT_ACCEPT_LICENSE 1002
#define IDC_TREE_PRODUCTS               1003
#define IDC_BUTTON_CHANGE_FOLDER        1005
#define IDC_BUTTON_CHANGE_OPTION        1006
#define IDC_PROGRESS_PRODUCT            1009
#define IDC_PROGRESS_FILES              1010
#define IDC_PIC_COPY_FILES              1010
#define IDC_CHECK1                      1011
#define IDC_CHECK_FILTER                1011
#define IDC_CHECK2                      1013
#define IDC_PROGRESS_COPY_FILES         1014
#define IDC_BMP_WIZARD                  1017
#define IDC_PORD_NAME                   1018
#define IDC_DESCRITPTION                1019
#define IDC_TREE                        1020
#define IDC_TREE_POSTCONFIG             1021
#define IDC_CUR_PROD_NAME               1022
#define IDC_PIC_CUR_PROD_NAME           1023
#define IDC_PIC_PROD_DESCRIPTION        1026
#define IDC_PROD_DESCRIPTION            1027
#define IDC_PIC_BOLDTITLE               1027
#define IDC_WELCOME_TITLE               1028
#define IDC_PIC_PROGRESS_ALL            1029
#define IDC_PROGRESS_ALL                1030
#define IDC_TREE2                       1030
#define IDC_LIST2                       1031
#define IDC_LIST_DRIVE                  1031
#define IDC_REBOOT_HOST_LIST            1031
#define IDC_PIC_SERVER_LIST             1032
#define IDC_LIST_SERVER                 1033
#define IDC_TREE_SETTING                1033
#define IDC_COMPUTER_NAME               1034
#define IDC_LOGON_STATIC3               1038
#define IDC_LOGON_STATIC2               1039
#define IDC_PIC_TITLE                   1042
#define IDC_SEL_PROD_TITLE              1043
#define IDC_SEL_LANG                    1043
#define IDC_MESSAGE                     1046
#define IDC_PHASE                       1048
#define IDC_RADIO1                      1049
#define IDC_RADIO_RI                    1049
#define IDC_AUTOUPG                     1049
#define IDC_SELECT_LANG_TITLE           1050
#define IDC_SELECT_TYPE_TITLE           1051
#define IDC_COMPLETION_TITLE            1052
#define IDC_DRIVE                       1055
#define IDC_REQUESTED_DISK              1056
#define IDC_FREE_DISK                   1057
#define IDC_EDT_REQ_DISK                1058
#define IDC_EDT_REM_DISK                1059
#define IDC_BUTTON_DISK_INFO            1060
#define IDC_EDIT_INST_FOLDER            1061
#define IDC_EDIT_REQ_DISK               1062
#define IDC_EDIT_REM_DISK               1063
#define IDC_COMBO_SHARE_DISK            1063
#define IDC_RADIO_LI                    1064
#define IDC_BTN_BACK                    1067
#define IDC_COMBO_INST_TYPE             1068
#define IDC_INST_TYPE_DESC              1069
#define IDC_PROD_NEED_SPACE             1070
#define IDC_STATIC_INSTALL_PATH         1071
#define IDC_RADIO_CRT_RESP              1072
#define IDC_RADIO_RMT                   1073
#define IDC_RADIO_LOCAL                 1074
#define IDC_WAIT_MESSAGE                1075
#define IDC_STATIC_LOCAL_DESC           1076
#define IDC_STATIC_RMT_DESC             1077
#define IDC_STATIC_CRT_DESC             1078
#define IDC_LAN_COMBO                   1080
#define IDC_LAN_TEXT_STATIC             1081
#define IDI_SETUP                       1082
#define IDC_ICON_STATIC                 1083
#define IDC_SETUP_LICENSE_MSG           1084
#define IDC_LICENSE_IMPORTANCE1         1085
#define IDC_LICENSE_IMPORTANCE2         1086
#define IDS_NOT_UPGRADE_IO              1087
#define IDS_NOT_UPGRADE_SBO             1088
#define IDS_LIC_CHK_FAILED              1089
#define IDC_INSTALLINFO_IMPORTANCE2     1089
#define IDS_REGISTER_CHK_FAILED         1090
#define IDC_INSTALLINFO_DESCRIPTION     1090
#define IDS_NOT_ENOUGH_SPACE_SYSTEM     1091
#define IDS_NOT_ENOUGH_SPACE_SYSTEM_REMOTE 1092
#define IDC_RADIO_CONSOLE_GUI           1092
#define IDC_RADIO_KEY                   1093
#define IDC_SERVER_DESCRIPT             1093
#define IDC_RADIO_ALP                   1094
#define IDC_RADIO_STANDALONE_GUI        1094
#define IDC_RADIO_TRIAL                 1095
#define IDC_TRIALKEY                    1096
#define IDC_RADIO_STANDALONE_GUI_DLG    1096
#define IDC_RADIO_PRIMARY_GUI           1096
#define IDS_TIMEOUT                     1097
#define IDC_STATIC_LICENSEKEY           1098
#define IDC_RADIO_PRIMARY_GUI_DLG       1098
#define IDC_RADIO_MEMBER_GUI            1098
#define IDS_INFO_RUN_DV_DCLICK          1099
#define IDC_RADIO_MEMBER_GUI_DLG        1100
#define IDC_RADIO_CUSTOM_GUI            1100
#define IDS_STATIC_CUSTOM_SUMMARY       1101
#define IDC_RADIO_CUSTOM_GUI_DLG        1102
#define IDC_STATIC_SERVTYPE_BORDER      1102
#define IDC_STATIC_SERVTYPE_BORDER_DLG  1103
#define IDC_RADIO_CONSOLE_GUI_DLG       1105
#define IDC_WARNING_EDTCTRL             1124
#define IDC_WARN_TITLE                  1127
#define IDC_STATIC_SUBTITLE             1129
#define IDC_INSTCOMPONENTSWIZ_SUBTITLE1 1132
#define IDC_INSTCOMPONENTSWIZ_SUBTITLE2 1133
#define IDC_DYNA_PIC                    1136
#define IDC_STATIC_COPY                 1137
#define IDC_STATIC_PRINT                1138
#define IDC_EDIT3                       1139
#define IDC_EDIT_PASSWORD               1139
#define IDC_EDIT_PWD                    1139
#define IDC_BTN_APPLY                   1140
#define IDC_BTN_REMOVE_HOST             1141
#define IDC_EDIT_USERNAME               1142
#define IDC_BTN_REMOVE                  1143
#define IDC_BTN_CONFIG                  1144
#define IDC_STATIC_WEBSITE              1145
#define IDC_STATIC_README               1146
#define IDC_WELCOME                     1147
#define IDC_CUSTOM                      1148
#define IDC_GROUP                       1149
#define IDC_STATIC_COLOR1               1150
#define IDC_STATIC_COLOR2               1151
#define IDC_TREE_STATUS                 1151
#define IDC_HOSTNAME                    1152
#define IDC_BTN_ADDHOST                 1153
#define IDC_STATIC_COLOR3               1154
#define IDC_STATIC_COLOR4               1155
#define IDC_STATIC_HOSTS                1156
#define IDC_STSMON_STATIC2              1157
#define IDC_STATIC_TOTALHOSTS           1158
#define IDC_STATIC_COMPLETED            1159
#define IDC_STATIC_FAILED               1160
#define IDC_STATIC_INSTALLING           1161
#define IDC_STATIC_WAITING              1162
#define IDC_STATIC_PAUSED               1163
#define IDC_STSMON_STATIC1              1164
#define IDC_BTN_SAVEREBOOT              1164
#define IDC_BTN_DETAIL                  1165
#define IDC_STS_STATIC1                 1166
#define IDC_PSTCFG_STATIC               1167
#define IDC_SUMMARY_STATIC1             1168
#define IDC_SUMMARY_STATIC2             1169
#define IDC__SUMMARY_STATIC3            1170
#define IDC_SUMMARY_STATIC3             1170
#define IDC_SUMMARY_STATIC4             1171
#define IDC_STATIC_HORBAR               1172
#define IDC_DESC                        1173
#define IDC_STATIC_AUTO                 1174
#define IDC_STATIC_CUSTOM               1175
#define IDC_BTN_UNSELALL                1176
#define IDC_BTN_SELALL                  1177
#define IDC_STATIC_DEPSUMMARY           1178
#define IDC_STATIC_SUMMARY              1178
#define IDC_REBOOT                      1180
#define IDC_SUMMARYLIST                 1181
#define IDC_BUTTON2                     1182
#define IDC_BTN_VALIDATE                1182
#define IDC_BTN_ADD                     1182
#define IDC_STATIC_USER                 1183
#define IDC_STATIC_PWD                  1184
#define IDC_VALIDATE_PROG               1185
#define IDC_TOTALHOSTS                  1187
#define IDC_VM                          1188
#define IDC_STATIC_VM                   1189
#define IDC_BTN_REFRESH                 1190
#define IDC_STATIC_REFRESH              1195
#define IDC_LOGIN_CURWINUSER            1196
#define IDC_STATIC_TITLE                1196
#define IDC_DOMAIN                      1197
#define IDC_STATIC_GROUP                1197
#define IDC_LOGIN_DOMAIN_SERVER         1198
#define IDC_EDIT_USER                   1198
#define IDC_AUTH_TYPE                   1199
#define IDC_LOGIN_STATIC_SERVER         1200
#define IDC_BTN_VERIFY                  1200
#define IDC_LOGIN_DOMAIN_USER           1201
#define IDC_LOGIN_DOMAIN_PWD            1202
#define IDC_LOGIN_STATIC_CREDENTIALSHEADER 1203
#define IDC_LOGIN_STATIC_USERNAME       1204
#define IDC_LOGIN_STATIC_PASSWORD       1205
#define IDC_LOGIN_STATIC_DOMAIN         1206
#define IDC_STATIC_UN2                  1207
#define IDM_DOC_RELEASE                 32771
#define IDM_ITEM1                       32772
#define IDM_ITEM2                       32773
#define IDM_ITEM3                       32774
#define IDM_ITEM4                       32775
#define ID_ADV_SELHOSTS_MENU_EDIT       32776
#define ID_HOSTCTRLMENU_DELETE          32777
#define ID_ADV_SELHOSTS_MENU_DELETE     32778
#define IDS_STRING_NO_USERNAME          32779
#define IDS_PLATFORM_NOT_SUPPORT        50000
#define IDS_PROD_CAN_BE_UPDATED         50001
#define IDS_PROD_CAN_NOT_UPDATED        50002
#define IDS_NOT_ENOUGH_SPACE            50003
#define IDS_LOAD_DLL_FAILED             50004
#define IDS_CALL_FUNC_FAILED            50005
#define IDS_MAPI_NOT_FOUND              50006
#define IDS_SETUPRV_PROD_NM             51050
#define IDS_SETUPRV_INST_PATH           51051
#define IDS_SETUPPRV_INSTALLPATH        51052
#define IDS_STPCHC_NOT_SELPRO           51100
#define IDS_SELECTLANG_TITLE            51151
#define IDS_SELECTLANG_DESCRIPTION      51152
#define IDS_WELCOME_TITLE               51201
#define IDS_WELCOME_DESCRITPTION        51202
#define IDS_PST_CFG_NEED_CONFIG         51250
#define IDS_PST_CFG_DOING_CONFIG        51251
#define IDS_PST_CFG_CONFIG_COMPLETE     51252
#define IDS_PST_CFG_BUTTON_NEXT         51253
#define IDS_PST_CFG_CONFIG_FAILED       51254
#define IDS_COPYFILES_CONTENT           51255
#define IDS_COPYFILES_TITLE             51256
#define IDS_SELECT_SERVER_LH            51300
#define IDS_SELECT_SERVER_TITLE         51301
#define IDS_SELECT_SERVER_SUBTITLE      51302
#define IDS_SELECT_SERVER_SPEC_SRVR     51303
#define IDS_SELECT_SERVER_ILL_CHAR      51304
#define IDS_SELECT_SERVER_BAD_RIGHTS    51305
#define IDS_SELECT_SERVER_LGN_FAIL      51306
#define IDS_SELECT_SERVER_LGN_CRED_CONFLICT 51307
#define IDS_SELECT_SERVER_SRVR_EXST     51308
#define IDS_SELECT_SERVER_SAH           51309
#define IDS_SELECT_SERVER_IP_WARNING    51310
#define IDS_SETTINGS_NO_SEL_SERVER      51350
#define IDS_SETTINGS_TITLE              51351
#define IDS_SETTINGS_SUB_TITLE          51352
#define IDS_SETTINGS_SEL_PROD           51353
#define IDS_SETTINGS_LOCAL_TITLE        51354
#define IDS_SETTINGS_LOCAL_SUB_TITLE    51355
#define IDS_LOGON_SPECIFY_USER          51400
#define IDS_LOGON_TITLE                 51401
#define IDS_LOGON_DOMAIN                51402
#define IDS_LOGON_DOMAIN2               51403
#define IDS_LOGON_DOMAIN3               51404
#define IDS_LOGON_UN                    51405
#define IDS_LOGON_PSW                   51406
#define IDS_LSM_COMPUTER_NAME           51407
#define IDS_LSM_USER_NAME               51408
#define IDS_LSM_STATUS                  51409
#define IDS_LSM_PROGRESS_BAR            51410
#define IDS_LSM_TITLE                   51411
#define IDS_LSM_SUB_TITLE               51412
#define IDS_LAUNCH_DEL_SRVC_FAIL        51413
#define IDS_INITIALIZE                  51450
#define IDS_COPYING_FILES               51451
#define IDS_INSTALLING_SRV              51452
#define IDS_INSTCOMPLETED               51453
#define IDS_INPROGRESS                  51454
#define IDS_ERROR_COPYFILES             51455
#define IDS_ERROR_NO_SPACE              51456
#define IDS_ALREADY_RUNNING             51457
#define IDS_STARTSRV_FAILED             51458
#define IDS_REMOVING_SRV                51459
#define IDS_CREATING_REGISTRY           51460
#define IDS_CREATING_ICANDFLD           51461
#define IDS_LOAD_SETUP_FAILED           51462
#define IDS_ARCSERVE_NOT_FOUND          51463
#define IDS_REQUIRE_CHANGER             51464
#define IDS_ERROR_REGISTRY              51465
#define IDS_ERROR_CREATESRV             51466
#define IDS_SNABASE_NOT_FOUND           51467
#define IDS_INIFILE_NOT_FOUND           51468
#define IDS_SERVICE_ALREADY_RUNNING     51469
#define IDS_IMPROPER_EDITION            51470
#define IDS_OPTION_NOTAVAILABLE         51471
#define IDS_RELATED_PROCESS_RUNNING     51472
#define IDS_MVS_JOB_RUNNING             51473
#define IDS_WINVERSION_ERR              51474
#define IDS_INSTNOTCOMPLETED            51475
#define IDS_INSTWINDOWSMSI              51476
#define IDS_UPDATEIE5                   51477
#define IDS_UPDATESYSLIB                51478
#define IDS_REBOOT                      51479
#define IDS_REBOOT_REINSTALL            51480
#define IDS_CONFIG_PRODUCT              51481
#define IDS_UPDATE_PRODUCT              51482
#define IDS_SEND_LOG_FILENAME           51483
#define IDS_ERROR_INSTSP                51484
#define IDS_IN_PROGRESS                 51500
#define IDS_INST_COMPLETED              51501
#define IDS_INST_FAILED                 51502
#define IDS_INST_NOT_STARTED            51503
#define IDS_INST_3RD_SP                 51504
#define IDS_COPY_IMG                    51505
#define IDS_SELECTTYPE_TITLE            51600
#define IDS_SELECTTYPE_SUBTITLE         51601
#define IDS_SELECTLICREG_TITLE          51610
#define IDS_SELECTLICREG_SUBTITLE       51611
#define IDS_COMPLETION_TITLE            51650
#define IDS_DRIVEINFO_LIST_DRV          51700
#define IDS_DRIVEINFO_LIST_REQ          51701
#define IDS_DRIVEINFO_LIST_REM          51702
#define IDS_DRIVEINFO_SPACE_UNIT        51703
#define IDS_CHOOSEPROD_DRV              51750
#define IDS_NEED_REBOOT                 51751
#define IDS_LPM_WAITING                 51752
#define IDS_ADMIN_ERROR                 51753
#define IDS_INST_FAILED_H               51754
#define IDS_MASTERSETUP                 51755
#define IDS_INST_WAITING                51756
#define IDS_CUSTOM_INFO_HEADER          51757
#define IDS_CUSTOM_INFO_SUBHDR          51758
#define IDS_CRT_RESPONSE_OK_1           51759
#define IDS_CRT_RESPONSE_OK_2           51760
#define IDS_CREATE_DIR_FAILED           51761
#define IDS_TYPE_LOCAL_TITLE            51762
#define IDS_TYPE_REMOTE_TITLE           51763
#define IDS_TYPE_CRT_REPS_TITLE         51764
#define IDS_TYPE_LOCAL_DESC             51765
#define IDS_TYPE_REMOTE_DESC            51766
#define IDS_TYPE_CRT_REPS_DESC          51767
#define IDS_CHS_PROD_NEED_SPACE         51768
#define IDS_CHS_FT_NEED_SPACE           51769
#define IDS_CONFLICT_PROD_INST          51770
#define IDS_WARNING_MSG_PROD            51771
#define IDS_INFOR_NEED_REBOOT           51772
#define IDS_COPYFILE_INSTALLING         51773
#define IDS_REBOOT_CONTINUE             51774
#define IDS_REBOOT_TO_INSTALL           51775
#define IDS_LPM_CANCEL                  51776
#define IDS_SINST_COPYRIGHT             51777
#define IDS_SINST_COPYRIGHTR            51778
#define IDS_SINST_USAGE0                51779
#define IDS_SINST_USAGE1                51780
#define IDS_SINST_USAGE2                51781
#define IDS_SINST_USAGE3                51782
#define IDS_SINST_USAGE4                51783
#define IDS_SINST_USAGE5                51784
#define IDS_SINST_USAGE6                51785
#define IDS_SINST_START                 51786
#define IDS_SINST_PRS                   51787
#define IDS_SINST_IRCS                  51788
#define IDS_SINST_US                    51789
#define IDS_SINST_INSTP                 51790
#define IDS_SINST_SUMMARY               51791
#define IDS_SINST_CHARSTR               51792
#define IDS_SINST_HOSTNAME              51793
#define IDS_SINST_USERNAME              51794
#define IDS_SINST_INSTPATH              51795
#define IDS_SINST_COMPLETED             51796
#define IDS_SINST_FAILED                51797
#define IDS_SINST_LOGFILE               51798
#define IDS_SINST_INST_TAIL             51799
#define IDS_SINST_RLOGIN                51800
#define IDS_SINST_RWARN                 51801
#define IDS_SINST_RERROR_SRV0           51802
#define IDS_SINST_RERROR_SRV1           51803
#define IDS_SINST_COPY_IMG              51804
#define IDS_SINST_ERR_NO_PROD           51805
#define IDS_SINST_START_TAIL            51806
#define IDS_REBOOT_RMT_MACHINE          51807
#define IDS_RESFILE_NULL                51808
#define IDS_HIDDEN_FOLDER               51809
#define IDS_LPM_USER_CANCEL_PRE         51810
#define IDS_WIZARD_DONE                 51811
#define IDS_BRWSFLD_TITLE               51812
#define IDS_NOT_UPGRADE                 51813
#define IDS_INSTALL_HEADER              51814
#define IDS_SINST_INST_END              51815
#define IDS_NOT_UPGRADE_ASO             51816
#define IDS_NOT_UPGRADE_EE              51817
#define IDS_SINST_WILL_NOT_INSTED       51818
#define IDS_INST_CA_LICENSE             51819
#define IDS_CA_LICENSE_FAILED           51820
#define IDS_NOT_UPGRADE_ASM             51821
#define IDS_INSTALL_SUMMARY_TITLE       51822
#define IDS_NOT_FND_RMT_SRV             51823
#define IDS_FAILED_LOAD_INSTALL_LOG     51824
#define IDS_SINST_INVALID_USR           51825
#define IDS_SINST_NOT_FND_ICFFILE       51826
#define IDS_SINST_NOT_ICFFILE           51827
#define IDS_NOT_RUN_WIN95               51828
#define IDS_COPYFILE_SUBTITLE           51830
#define IDS_ERROR_TEMP_PATH             52001
#define IDS_ERROR_CRT_FLD               52002
#define IDS_LOG_TITLE                   52003
#define IDS_LOG_CHECK_ENV               52004
#define IDS_ERR_WORK_DIR                52005
#define IDS_LOG_WORK_DIR                52006
#define IDS_ERR_FIND_FILE               52007
#define IDS_LOG_WIN_9X                  52008
#define IDS_LOG_WIN_NT                  52009
#define IDS_LOG_XP_HOME                 52010
#define IDS_LOG_WIN_64B                 52011
#define IDS_ERR_OS_VER                  52012
#define IDS_ERR_MACHINE_NAME            52013
#define IDS_LOG_MACHINE_NAME            52014
#define IDS_LOG_PARAMETER               52015
#define IDS_LOG_RMT_MODE                52016
#define IDS_LOG_ICF_FILE                52017
#define IDS_LOG_PARSE_CAT               52018
#define IDS_LOG_ERR_PROD_KEY            52019
#define IDS_LOG_READ_BYTE               52020
#define IDS_LOG_REQUIRED_SPACE          52021
#define IDS_LOG_CALL_RPC0               52022
#define IDS_ERR_FIND_FIRST_HD           52023
#define IDS_LOG_FIND_FIRST_HD           52024
#define IDS_LOG_LAUNCH_SETUP            52025
#define IDS_ERR_COPYFILE                52026
#define IDS_LOG_COPY_IMG                52027
#define IDS_ERR_LOGIN                   52028
#define IDS_LOG_START_SRV               52029
#define IDS_LOG_RMT_SETUP               52030
#define IDS_LOG_CRT_ANS_FILE            52031
#define IDS_LOG_LOCAL_SETUP             52032
#define IDS_LOG_LAUNCH_PROCESS          52033
#define IDS_ERR_LAUNCH_PROCESS          52034
#define IDS_LOG_CALL_FUNC               52035
#define IDS_LOG_LOAD_DLL                52036
#define IDS_ERR_LOAD_DLL                52037
#define IDS_LOG_RETURN_CODE             52038
#define IDS_LOG_PRE_INST                52039
#define IDS_LOG_LAUNCH_THREAD           52040
#define IDS_ERR_LAUNCH_THREAD           52041
#define IDS_ERR_OPEN_REGKEY             52042
#define IDS_ERR_SET_REGVAL              52043
#define IDS_LOG_INST_SP                 52044
#define IDS_LOG_CMD_LINE                52045
#define IDS_LOG_THREAD_EXIT             52046
#define IDS_LOG_THREAD_RUN              52047
#define IDS_ERR_NO_SPACE                52048
#define IDS_COLLECT_INFO                52049
#define IDS_WIZBACK                     52050
#define IDS_WIZNEXT                     52051
#define IDS_WIZCANCEL                   52052
#define IDS_WIZFINISH                   52053
#define IDS_WAIT_MSG_CFG                52054
#define IDS_FOLDER_DOESNOT_EXIST        52055
#define IDS_INVALID_PATH                52056
#define IDS_ERROR_CREATE_PATH           52057
#define IDS_FORDER_NAME                 52058
#define IDS_NOT_UPGRADE_ARC             52059
#define IDS_NOT_RMT_64B                 52060
#define IDS_NOT_SHARE_FOLDER            52061
#define IDS_COMPONENT                   52062
#define IDS_REQUIRE_NTSP6               52063
#define IDS_SINST_USAGE_DISPLAY         52064
#define IDS_NOT_SBS                     52065
#define IDS_NOT_WINNT                   52066
#define IDS_NOT_WIN9X                   52067
#define IDS_SELLICTYPETITLE             52068
#define IDS_SELLICTYPESUBTITLE          52069
#define IDS_SEL_LIC_TRIAL               52070
#define IDS_SEL_LIC_KEY                 52071
#define IDS_KEY_ERROR                   52072
#define IDS_WARNING_NEED_IE             52073
#define IDS_LICENSEKEY_HELP1            52074
#define IDS_LICENSEKEY_HELP2            52075
#define IDS_LICENSE_MSG                 52076
#define IDS_KEY_ERROR_TITLE             52077
#define IDS_LICENSE_IMPORTANCE1         52078
#define IDS_LICENSE_IMPORTANCE2         52079
#define IDS_LICENSEKEY_HELP3            52080
#define IDS_MSG_LIC_DISAGREE            52081
#define IDS_TRIAL_CD_KEY_MISSING_ERROR  52082
#define IDS_TRIAL_CD_KEY_MISSING_TITLE  52083
#define IDS_NOT_UPGRADE_EE10_0          52084
#define IDS_NOT_UPGRADE_EE10_5          52085
#define IDS_SETUP_LIC_DESC              52086
#define IDS_SETUP_LIC_KEY               52087
#define IDS_SETUP_LIC_ALP               52088
#define IDS_SETUP_LIC_TRIAL             52089
#define IDS_SETUP_LIC_HELP_DESC         52090
#define IDS_INSTALLING_MDB              52091
#define IDS_INSTALLING_EXTERNAL         52091
#define IDS_INSTALLING_EIAM             52092
#define IDS_SETUP_LIC_ALP_ERROR         52093
#define IDS_ERR_BASE_NTAGENT            52094
#define IDS_ASDB_REMOTEINSTALL_WARN     52095
#define IDS_VALID_REGSERVICE            52096
#define IDS_SINST_USAGE7                52097
#define IDS_INST_SERVTYPE_TITLE         52097
#define IDC_BT_PRINT                    52098
#define IDS_INST_SERVTYPE_SUBTITLE      52098
#define IDC_EXPLORER1                   52099
#define IDS_STATIC_CONSOLE_GUI_SUMMARY  52099
#define IDC_EXPLORER_NEW_COMPONENTS     52099
#define IDS_STATIC_STANDALONE_SUMMARY   52100
#define IDC_EXPLORER_INSTALLED_COMPONENTS 52100
#define IDS_STATIC_PRIMARY_SUMMARY      52101
#define IDS_STATIC_MEMBER_SUMMARY       52102
#define IDS_BConfig_RETCODE_1           52110
#define IDS_BConfig_RETCODE_2           52111
#define IDS_BConfig_RETCODE_4           52112
#define IDS_BConfig_RETCODE_100         52113
#define IDS_BConfig_RETCODE_200         52114
#define IDS_BConfig_RETCODE_300         52115
#define IDS_BConfig_RETCODE_400         52116
#define IDS_ASPORTMAPPER_WARNING        52120
#define IDS_SETUPSQL_RETCODE_1          52121
#define IDS_SETUPSQL_RETCODE_2          52122
#define IDS_SETUPSQL_RETCODE_3          52123
#define IDS_SETUPSQL_RETCODE_4          52124
#define IDS_SETUPSQL_RETCODE_5          52125
#define IDS_REMOTE_PRIVILEGE_ERR        52130
#define IDS_SERMIGRATION_REBOOT_MSG     52131
#define IDS_REMOTEASDB_OK_MSG           52132
#define IDS_REMOTEASDB_FAILED_MSG       52133
#define IDS_WARNING_NET20INST_MSG       52134
#define IDS_WARNING_SQLESP2INST_MSG     52135
#define IDS_SETUPSQL_RETCODE_6          52136
#define IDS_OS_CHECK_WARNING_WINNT      52140
#define IDS_OS_CHECK_WARNING_WIN2KSP4   52141
#define IDS_OS_CHECK_WARNING_WINXPSP2   52142
#define IDS_OS_CHECK_WARNING_WIN2K3SP1  52143
#define IDS_WARNING_VMWARE_INST         52144
#define IDS_ERRMSG_ETPKI_SETUP          52145
#define IDS_REBOOT_WARNING_MSG          52150
#define IDS_REMOTE_REBOOT_WARNING_MSG   52151
#define IDC_INSTCOMPONENTS_SUBTITLE1    52152
#define IDC_INSTCOMPONENTS_SUBTITLE2    52153
#define IDS_UPG_FOLDER_LOCKED_WARNINGMSG 52154
#define IDS_UPG_FOLDER_RESTOREFAILED_WARNINGMSG 52160
#define IDS_SQLE_INSTFAILED_ERRORMSG    52161
#define IDS_SINST_USAGE8                52162
#define IDS_SINST_USAGE9                52163
#define IDS_SSHAREPOINT_UPGWARN         52164
#define IDS_RMTUPG_MEMBER_SRVMGR        52170
#define IDS_ICFTUPG_MEMBER_SRVMGR       52171
#define IDS_SILENTUPG_MEMBER_SRVMGR     52172
#define IDS_ETPKI_REBOOT_WARN           52173
#define IDS_PREVIOUS_PRIMARY_UPG_WARN1  52200
#define IDS_PREVIOUS_PRIMARY_UPG_WARN2  52201
#define IDS_SQLE_NATIVECLIENT_WARN      52210
#define IDS_SAP_ORACLE_VERSION_WARN     52211
#define IDS_RMAN_ORACLE_VERSION_WARN    52212
#define IDS_PRIMARY_VERCHECK_FAILED_RMT 52300
#define IDS_PRIMARY_VERCHECK_FILEERR_RMT 52301
#define IDS_PRIMARY_VERCHECK_FAILED_LOC 52302
#define IDS_PRIMARY_VERCHECK_FAILED_SILENT 52303
#define IDS_PRIMARY_VERCHECK_CANNOTGETVER 52304
#define IDS_WARNING_SYSTEM_FREESPACE    52400
#define IDS_WARNING_SQLAGENT_NETCFG     52401
#define IDS_DASHBOARD_UNINSTALL_WARN    52402
#define IDS_LOGIN_HEADTITLE             52403
#define IDS_AUTH_TYPE_ARCSERVE          52404
#define IDS_AUTH_TYPE_WINDOWS           52405
#define IDS_DOMAIN_USERNAME             52406
#define IDS_USERNAME                    52407
#define IDS_WINDOWS_USER_FORMAT_ERROR   52408
#define IDS_ONLY_SUPPORT_ARCSERVE_AUTH  52409
#define IDS_WITHOUT_EM_OR_LICENSE       52410
#define IDS_EM_LICENSE_EXPIRED          52411
#define IDS_ACCESS_DENIED_FOR_WIZARD    52412
#define IDS_NOT_ADMINISTRAOTOR_USER     52413
#define IDS_NO_USERNAME_ERROR           52414
#define IDS_WARNING_RMTASDB_SQLAGENT_UPG 52500
#define IDS_SELECT_SERVER_BAD_RIGHTS_SECCTION 52501
#define IDC_HORBAR1                     65535
#define IDC_HORBAR2                     65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        239
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1202
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
