#ifndef _MY_RESOURCE_H
#define _MY_RESOURCE_H

#define DD_CUSTOM                                200
#define ID_EDIT_DELETE                           201
#define ID_EDIT_EDIT                             202
#define ID_POPUP_MENU                            203
#define IDB_ACCOUNT                              204
#define IDB_BANNER16                             205
#define IDB_BANNER16SHORT                        206
#define IDB_BANNER256                            207
#define IDB_BANNER256SHORT                       208
#define IDB_BANNER257                            209
#define IDB_BBRD1                                210
#define IDB_BBRD2                                211
#define IDB_BBRD3                                212
#define IDB_BBRD4                                213
#define IDB_BBRD5                                214
#define IDB_BBRD6                                215
#define IDB_BBRD7                                216
#define IDB_BBRDDR                               217
#define IDB_BBRDIMAGE                            218
#define IDB_BBRDRAID                             219
#define IDB_BBRDSILO                             220
#define IDB_BITMAP1                              221
#define IDB_BITMAP10                             222
#define IDB_BITMAP11                             223
#define IDB_BITMAP12                             224
#define IDB_BITMAP2                              225
#define IDB_BITMAP4                              226
#define IDB_BITMAP6                              227
#define IDB_BITMAP7                              228
#define IDB_BITMAP8                              229
#define IDB_BITMAP9                              230
#define IDB_BLANK                                231
#define IDB_NWELCOME                             232
#define IDB_TITLE                                233
#define IDB_UNWELCOME                            234
#define IDB_WATERMARK16                          235
#define IDB_WATERMARK256                         236
#define IDBACK                                   237
#define IDC_AADRENABLE                           238
#define IDC_ADD                                  239
#define IDC_AGENT_TYPE                           240
#define IDC_AGENT_TYPE_1                         241
#define IDC_ALERT                                242
#define IDC_ALERT_DIR                            243
#define IDC_ALERT_GBOX                           244
#define IDC_ALERT_PATH                           245
#define IDC_ALERT_TEXT                           246
#define IDC_ALT_BROWSE                           247
#define IDC_ANIMATE                              248
#define IDC_ARCSERVE_DIR                         249
#define IDC_ARCSERVE_GBOX                        250
#define IDC_ARCSERVE_INFO                        251
#define IDC_ARCSERVE_PATH                        252
#define IDC_ARCSERVE_SERVER                      253
#define IDC_ARCUNIX                              254
#define IDC_ARCWINNT                             255
#define IDC_AS_MANAGER                           256
#define IDC_AS_SERVER                            257
#define IDC_AS_SERVER_ADMIN                      258
#define IDC_AUTHENTICITY_NT                      259
#define IDC_AUTHENTICITY_SQL                     260
#define IDC_BACK                                 261
#define IDC_BACKUP_AGENT_TYPE                    262
#define IDC_BANNER_TEXT                          263
#define IDC_BLOCK                                264
#define IDC_BROWSE                               265
#define IDC_BROWSE_LOG                           266
#define IDC_BROWSE_TEMP                          267
#define IDC_BROWSE1                              268
#define IDC_BROWSE2                              269
#define IDC_BTN_BACK                             270
#define IDC_BTN_CANCEL                           271
#define IDC_BTN_OK                               272
#define IDC_BUTTON_ADD                           273
#define IDC_BUTTON_BROWSE                        274
#define IDC_BUTTON_BROWSER                       275
#define IDC_BUTTON_DELETE                        276
#define IDC_BUTTON_MODIFY                        277
#define IDC_BUTTON1                              278
#define IDC_CAUSETEXT                            279
#define IDC_CDKEY_TEXT                           280
#define IDC_CHECK_BRICK_LEVEL                    281
#define IDC_CHECKBOX_SINGLE_INST                 282
#define IDC_CLUSTER                              283
#define IDC_CLUSTER_CFMPWD                       284
#define IDC_CLUSTER_PWD                          285
#define IDC_CLUSTER_TEXT                         286
#define IDC_CLUSTER_USER                         287
#define IDC_COMBO_SHARE_DISK                     288
#define IDC_COMP_FIVE                            289
#define IDC_COMP_FOUR                            290
#define IDC_COMP_ONE                             291
#define IDC_COMP_SIX                             292
#define IDC_COMP_THREE                           293
#define IDC_COMP_TWO                             294
#define IDC_COMPANY                              295
#define IDC_COMPONENT                            296
#define IDC_CONFIG_ABORT                         297
#define IDC_CONFIG_MSG                           298
#define IDC_CONFIG_TCPIP_VI                      299
#define IDC_Configure_TCPIP                      300
#define IDC_CONFIRM                              301
#define IDC_CONFIRM_NTPWD                        302
#define IDC_CONFIRM_PASSWORD                     303
#define IDC_CONFIRM2                             304
#define IDC_CREATE_ACCOUNT                       305
#define IDC_CUSTOM_SETUP                         306
#define IDC_DB_COMBO                             307
#define IDC_DB_TEXT                              308
#define IDC_DELETE                               309
#define IDC_DELETE_QUEUE                         310
#define IDC_DESTINATIONFILE                      311
#define IDC_DISK_INFO                            312
#define IDC_DOMAIN                               313
#define IDC_DOMAIN_NAME                          314
#define IDC_DONE_MSG                             315
#define IDC_DONE_RADIO_NO                        316
#define IDC_DONE_RADIO_YES                       317
#define IDC_DOSAPCONFIGURE                       318
#define IDC_DR_NETPC                             319
#define IDC_EDIT_ACCOUNT                         320
#define IDC_EDIT_BACKINT_PATH                    321
#define IDC_EDIT_BLOCK_NUMBER                    322
#define IDC_EDIT_BLOCK_SIZE                      323
#define IDC_EDIT_BLOCKSIZE                       324
#define IDC_EDIT_CLUSTER_SRV_CFMPWD              325
#define IDC_EDIT_CLUSTER_SRV_PWD                 326
#define IDC_EDIT_CLUSTER_SRV_USER                327
#define IDC_EDIT_CONFIRM_PASSWORD                328
#define IDC_EDIT_COUNTER                         329
#define IDC_EDIT_DEBUGLEVEL                      330
#define IDC_EDIT_DELAY                           331
#define IDC_EDIT_DEPTH                           332
#define IDC_EDIT_DIRECTORY                       333
#define IDC_EDIT_DOMAIN_NAME                     334
#define IDC_EDIT_INSTANCE_NAME                   335
#define IDC_EDIT_LOG                             336
#define IDC_EDIT_LOGIN_ID                        337
#define IDC_EDIT_MAIL                            338
#define IDC_EDIT_MAILBOX                         339
#define IDC_EDIT_MAILNAME_EXC55                  340
#define IDC_EDIT_MEM                             341
#define IDC_EDIT_PASSWORD                        342
#define IDC_EDIT_PATH_LOG                        343
#define IDC_EDIT_PATH_RMT                        344
#define IDC_EDIT_PATH_TEMP                       345
#define IDC_EDIT_PORT_NO                         346
#define IDC_EDIT_PORT_NUMBER                     347
#define IDC_EDIT_PORTNO                          348
#define IDC_EDIT_SERVERID                        349
#define IDC_EDIT_TEMP                            350
#define IDC_EDIT_THREADS                         351
#define IDC_EDIT_VIRTUAL_MAILBOX                 352
#define IDC_EDIT_VIRTUAL_PASSWORD                353
#define IDC_EDIT_VIRTUAL_SERVER_NAME             354
#define IDC_EDIT_VIRTUAL_SERVICE_ACCOUNT         355
#define IDC_EDIT_VIRTUAL_SQL_SRV                 356
#define IDC_EDIT1                                357
#define IDC_EDIT2                                358
#define IDC_EDIT3                                359
#define IDC_EDIT4                                360
#define IDC_ERRORINFO                            361
#define IDC_EXCH2000_LOG_PATH                    362
#define IDC_EXCHANGE_ERROR_MESSAGE               363
#define IDC_EXPLANATION                          364
#define IDC_EXPLANATIONTEXT                      365
#define IDC_EXPRESS                              366
#define IDC_FILE                                 367
#define IDC_FILENAME                             368
#define IDC_FOLDSIZE                             369
#define IDC_FOUR                                 370
#define IDC_FULLPATH                             371
#define IDC_GAUGE                                372
#define IDC_HELPBUTTON                           373
#define IDC_HOST                                 374
#define IDC_HOSTPWD                              375
#define IDC_HOSTPWD_CONFIRM                      376
#define IDC_HOSTPWD_CONFIRM2                     377
#define IDC_HOSTUSERNAME                         378
#define IDC_HSM                                  379
#define IDC_ICON1                                380
#define IDC_ID                                   381
#define IDC_INFORMIXSERVER                       382
#define IDC_INIFILE_PATH                         383
#define IDC_IPEDIT                               384
#define IDC_LASTWRITE1                           385
#define IDC_LASTWRITE2                           386
#define IDC_LICTEXT                              387
#define IDC_LIST                                 388
#define IDC_LIST_ACCOUNT                         389
#define IDC_LIST_VIRTUAL                         390
#define IDC_LOCAL                                391
#define IDC_LOGINID                              392
#define IDC_MACHINE_NAME                         393
#define IDC_MACHINE_OR_ORACLE_NETWORK_NAME       394
#define IDC_MACHINENAME                          395
#define IDC_MBOX                                 396
#define IDC_MODIFY                               397
#define IDC_MORE                                 398
#define IDC_NAME                                 399
#define IDC_NAMED_PIPE                           400
#define IDC_NETWORK_PROTOCOL                     401
#define IDC_NEWSUBDIRECTORY                      402
#define IDC_NEXT                                 403
#define IDC_NT_ORACLE_FAIL_SAFE_ACCOUNT          404
#define IDC_NTAGENT_PATH                         405
#define IDC_NTPWD                                406
#define IDC_NTUSER                               407
#define IDC_OK                                   408
#define IDC_ONE                                  409
#define IDC_ORGANIZATION                         410
#define IDC_OVERWRITE_DB                         411
#define IDC_PASS_CONFIRM                         412
#define IDC_PASSWORD                             413
#define IDC_PASSWORD2                            414
#define IDC_PATH                                 415
#define IDC_PATH2                                416
#define IDC_PICTURE                              417
#define IDC_PORTNO                               418
#define IDC_PROTOCOL                             419
#define IDC_QUESTION                             420
#define IDC_QUEUE_TEXT                           421
#define IDC_QUEUE_WARNING                        422
#define IDC_RADIO_CA_BACKUP_AGENT                423
#define IDC_RADIO_GIGANET                        424
#define IDC_RADIO_MIXEDMODE                      425
#define IDC_RADIO_NAMED_PIPE                     426
#define IDC_RADIO_NO                             427
#define IDC_RADIO_NOTES_BACKUP_AGENT             428
#define IDC_RADIO_TCP_IP                         429
#define IDC_RADIO_VIRTUAL_NAMED_PIPES            430
#define IDC_RADIO_VIRTUAL_TCP_IP                 431
#define IDC_RADIO_WINMODE                        432
#define IDC_RADIO_YES                            433
#define IDC_RAIMA_DATABASE_ONLY                  434
#define IDC_REASONS                              435
#define IDC_REMOTE                               436
#define IDC_REMOTE_USERCREATE                    437
#define IDC_REPLACE_ALERT                        438
#define IDC_REPOSITORY_NAME                      439
#define IDC_REPOSITORY_PWD                       440
#define IDC_REPOSITORY_PWD2                      441
#define IDC_REPOSITORY_USER                      442
#define IDC_SERVERID                             443
#define IDC_SERVICE_MSG                          444
#define IDC_SETUP_TYPE                           445
#define IDC_SHARE_LIST                           446
#define IDC_SHARE_TEXT                           447
#define IDC_SID                                  448
#define IDC_SINGLEINS                            449
#define IDC_SLIDER_TP                            450
#define IDC_SLIDER1                              451
#define IDC_SOURCEFILE                           452
#define IDC_SPACE_AVAILABLE                      453
#define IDC_SPACE_NEEDED                         454
#define IDC_SPIN_BLOCK_SIZE                      455
#define IDC_SPIN_COUNTER                         456
#define IDC_SPIN_DEBUGLEVEL                      457
#define IDC_SPIN_DELAY                           458
#define IDC_SPIN_DEPTH                           459
#define IDC_SPIN_MEM                             460
#define IDC_SPIN_THREADS                         461
#define IDC_SPIN1                                462
#define IDC_SPIN2                                463
#define IDC_SPIN3                                464
#define IDC_SPIN4                                465
#define IDC_SPIN6                                466
#define IDC_SPIN7                                467
#define IDC_SQL_DATABASE_ONLY                    468
#define IDC_SQL_SERVER                           469
#define IDC_START_STATE                          470
#define IDC_STATIC_AADRNOTE                      471
#define IDC_STATIC_AADRNOTE1                     472
#define IDC_STATIC_AADRNOTE2                     473
#define IDC_STATIC_AADRNOTE3                     474
#define IDC_STATIC_ABORTED                       475
#define IDC_STATIC_BLOCK_SIZE                    476
#define IDC_STATIC_DOMAIN                        477
#define IDC_STATIC_FILE                          478
#define IDC_STATIC_GROUP_BOX                     479
#define IDC_STATIC_GROUP_BOX1                    480
#define IDC_STATIC_LOTUS                         481
#define IDC_STATIC_MAILBOX                       482
#define IDC_STATIC_MSG                           483
#define IDC_STATIC_MSG2                          484
#define IDC_STATIC_NA                            485
#define IDC_STATIC_PASSWORD                      486
#define IDC_STATIC_PASSWORD2                     487
#define IDC_STATIC_PORT_NO                       488
#define IDC_STATIC_REG                           489
#define IDC_STATIC_REPOSITORYNAME                490
#define IDC_STATIC_REPOSITORYPWD                 491
#define IDC_STATIC_REPOSITORYPWD2                492
#define IDC_STATIC_REPOSITORYUSER                493
#define IDC_STATIC_SERVERNAME                    494
#define IDC_STATIC_SERVICE_ACCOUNT               495
#define IDC_STATIC_USERNAME                      496
#define IDC_STATIC1                              497
#define IDC_STATIC10                             498
#define IDC_STATIC11                             499
#define IDC_STATIC12                             500
#define IDC_STATIC13                             501
#define IDC_STATIC14                             502
#define IDC_STATIC15                             503
#define IDC_STATIC16                             504
#define IDC_STATIC17                             505
#define IDC_STATIC18                             506
#define IDC_STATIC2                              507
#define IDC_STATIC3                              508
#define IDC_STATIC4                              509
#define IDC_STATIC5                              510
#define IDC_STATIC6                              511
#define IDC_STATIC7                              512
#define IDC_STATIC8                              513
#define IDC_STATIC9                              514
#define IDC_STEP                                 515
#define IDC_STOP                                 516
#define IDC_TCP_IP                               517
#define IDC_TEXT                                 518
#define IDC_TEXT_ONE                             519
#define IDC_TEXT_THREE                           520
#define IDC_TEXT_TWO                             521
#define IDC_TEXT1                                522
#define IDC_TEXT2                                523
#define IDC_THREE                                524
#define IDC_TNG                                  525
#define IDC_TWO                                  526
#define IDC_UNDONE_MSG                           527
#define IDC_UNFOLD                               528
#define IDC_UNINSTALL_ALERT                      529
#define IDC_UNINSTALL_AS                         530
#define IDC_USE_GIGANET                          531
#define IDC_USE_NAMED_PIPE                       532
#define IDC_USE_TCP_IP                           533
#define IDC_USER_NAME                            534
#define IDC_USERNAME                             535
#define IDC_VER_PASSWORD                         536
#define IDC_VIRTUAL_SQL_SRV                      537
#define IDC_WAIT_MESSAGE                         538
#define IDC_WARNICON                             539
#define IDC_WARNING                              540
#define IDC_WHATTEXT                             541
#define IDCANCEL1                                542
#define IDD_AADRENABLE                           543
#define IDD_ABORTED_1_                           544
#define IDD_ABORTED_10_                          545
#define IDD_ABORTED_11_                          546
#define IDD_ABORTED_2_                           547
#define IDD_ABORTED_3_                           548
#define IDD_ABORTED_4_                           549
#define IDD_ABORTED_5_                           550
#define IDD_ABORTED_6_                           551
#define IDD_ABORTED_7_                           552
#define IDD_ABORTED_8_                           553
#define IDD_ABORTED_9_                           554
#define IDD_ACCOUNT_1_                           555
#define IDD_ACCOUNT_2_                           556
#define IDD_ACCOUNT_CONFIG_PAGE_1_               557
#define IDD_ACCOUNT_CONFIG_PAGE_2_               558
#define IDD_ACCOUNT_CONFIG_PAGE_3_               559
#define IDD_ACCOUNT_CONFIG_PAGE_4_               560
#define IDD_ACCOUNT_CONFIG_PAGE_5_               561
#define IDD_ACCOUNT_CONFIG_PAGE_6_               562
#define IDD_ACCOUNT_CONFIG_SAP_PAGE              563
#define IDD_ADDINSTANCE                          564
#define IDD_ASKADDNETPCSUPPORT                   565
#define IDD_BEFOREREMOVINGCOMPONENTS             566
#define IDD_BILLBOARD_1_                         567
#define IDD_BILLBOARD_2_                         568
#define IDD_BILLBOARD_3_                         569
#define IDD_BILLBOARD_4_                         570
#define IDD_BILLBOARD_5_                         571
#define IDD_BILLBOARD_6_                         572
#define IDD_BRICK_LEVEL_BACKUP                   573
#define IDD_BROWSEDIR_1_                         574
#define IDD_BROWSEDIR_2_                         575
#define IDD_BROWSEDIR_3_                         576
#define IDD_BROWSEDIR_4_                         577
#define IDD_BROWSEDIR_5_                         578
#define IDD_BROWSEDIR_6_                         579
#define IDD_CDKEY_1_                             580
#define IDD_CDKEY_2_                             581
#define IDD_CDKEY_3_                             582
#define IDD_CDKEY_4_                             583
#define IDD_CDKEY_5_                             584
#define IDD_CHECKENVIRONMENT_1_                  585
#define IDD_CHECKENVIRONMENT_2_                  586
#define IDD_CHECKENVIRONMENT_3_                  587
#define IDD_CHECKENVIRONMENT_4_                  588
#define IDD_CHECKENVIRONMENT_5_                  589
#define IDD_CHECKENVIRONMENT_6_                  590
#define IDD_CHECKENVIRONMENT_7_                  591
#define IDD_CHECKENVIRONMENT_8_                  592
#define IDD_CONFIG_1_                            593
#define IDD_CONFIG_2_                            594
#define IDD_CONFIG_3_                            595
#define IDD_CONFIG_DLA                           596
#define IDD_CONFIGURATION_1_                     597
#define IDD_CONFIGURATION_10_                    598
#define IDD_CONFIGURATION_2_                     599
#define IDD_CONFIGURATION_3_                     600
#define IDD_CONFIGURATION_4_                     601
#define IDD_CONFIGURATION_5_                     602
#define IDD_CONFIGURATION_6_                     603
#define IDD_CONFIGURATION_7_                     604
#define IDD_CONFIGURATION_8_                     605
#define IDD_CONFIGURATION_9_                     606
#define IDD_CONFIRMFILEREPLACE_1_                607
#define IDD_CONFIRMFILEREPLACE_2_                608
#define IDD_CONFIRMFILEREPLACE_3_                609
#define IDD_CONFIRMFILEREPLACE_4_                610
#define IDD_CONFIRMFILEREPLACE_5_                611
#define IDD_CONFIRMFILEREPLACE_6_                612
#define IDD_COPYINGFILES_1_                      613
#define IDD_COPYINGFILES_2_                      614
#define IDD_COPYINGFILES_3_                      615
#define IDD_DBACCOUNT_1_                         616
#define IDD_DBACCOUNT_2_                         617
#define IDD_DBACCOUNT_3_                         618
#define IDD_DBACCOUNT_4_                         619
#define IDD_DBACCOUNT_5_                         620
#define IDD_DBACCOUNT_6_                         621
#define IDD_DBACCOUNT1_1_                        622
#define IDD_DBACCOUNT1_2_                        623
#define IDD_DBACCOUNT1_3_                        624
#define IDD_DBACCOUNT2                           625
#define IDD_DIALOG_CREATE_ACCOUNT                626
#define IDD_DONE_1_                              627
#define IDD_DONE_10_                             628
#define IDD_DONE_11_                             629
#define IDD_DONE_2_                              630
#define IDD_DONE_3_                              631
#define IDD_DONE_4_                              632
#define IDD_DONE_5_                              633
#define IDD_DONE_6_                              634
#define IDD_DONE_7_                              635
#define IDD_DONE_8_                              636
#define IDD_DONE_9_                              637
#define IDD_DONEREBOOT                           638
#define IDD_EXCH_VERIFY                          639
#define IDD_GETLICENSEINFO                       640
#define IDD_GETLICENSEINFO_1_                    641
#define IDD_GETLICENSEINFO_2_                    642
#define IDD_GETLICENSEINFO_3_                    643
#define IDD_GETLICENSEINFO_4_                    644
#define IDD_INSERTCD_1_                          645
#define IDD_INSERTCD_2_                          646
#define IDD_INSERTCD_3_                          647
#define IDD_INSERTCD_4_                          648
#define IDD_LIC_AGREE                            649
#define IDD_NETWORK_CONFIG_PAGE                  650
#define IDD_READINGINFO_1_                       651
#define IDD_READINGINFO_10_                      652
#define IDD_READINGINFO_11_                      653
#define IDD_READINGINFO_2_                       654
#define IDD_READINGINFO_3_                       655
#define IDD_READINGINFO_4_                       656
#define IDD_READINGINFO_5_                       657
#define IDD_READINGINFO_6_                       658
#define IDD_READINGINFO_7_                       659
#define IDD_READINGINFO_8_                       660
#define IDD_READINGINFO_9_                       661
#define IDD_REMOTE_PROPERTIES_1_                 662
#define IDD_REMOTE_PROPERTIES_2_                 663
#define IDD_REMOTE_PROPERTIES_3_                 664
#define IDD_REMOVINGCOMPONENTS_1_                665
#define IDD_REMOVINGCOMPONENTS_2_                666
#define IDD_REMOVINGCOMPONENTS_3_                667
#define IDD_REMOVINGCOMPONENTS_4_                668
#define IDD_REPORTERROR_1_                       669
#define IDD_REPORTERROR_2_                       670
#define IDD_REPORTERROR_3_                       671
#define IDD_REPORTERROR_4_                       672
#define IDD_REPORTERROR_5_                       673
#define IDD_REPORTERROR_6_                       674
#define IDD_REPORTERROR_7_                       675
#define IDD_RMT_SETPATH                          676
#define IDD_SELECT_BACKUP_AGENT                  677
#define IDD_SELECTPATH_1_                        678
#define IDD_SELECTPATH_2_                        679
#define IDD_SERVER_CONFIG_PAGE                   680
#define IDD_SPACE_ERROR                          681
#define IDD_SPLASHSCREEN                         682
#define IDD_SPLASHSCREEN_1_                      683
#define IDD_SPLASHSCREEN_2_                      684
#define IDD_STOP_SERVICE_1_                      685
#define IDD_STOP_SERVICE_2_                      686
#define IDD_STOP_SERVICE_3_                      687
#define IDD_STOP_SERVICE_4_                      688
#define IDD_STOP_SERVICE_5_                      689
#define IDD_STOP_SERVICE_6_                      690
#define IDD_STOP_SERVICE_7_                      691
#define IDD_STOP_SERVICE_8_                      692
#define IDD_UNDONE_1_                            693
#define IDD_UNDONE_2_                            694
#define IDD_UNDONE_3_                            695
#define IDD_UNDONE_4_                            696
#define IDD_UNDONE_5_                            697
#define IDD_UNINSTALL_ABORTED_1_                 698
#define IDD_UNINSTALL_ABORTED_2_                 699
#define IDD_UNINSTALL_ABORTED_3_                 700
#define IDD_UNINSTALL_ABORTED_4_                 701
#define IDD_UNINSTALL_ABORTED_5_                 702
#define IDD_UNINSTALL_ABORTED_6_                 703
#define IDD_UNWELCOME                            704
#define IDD_UPDATE_DIALOG_1_                     705
#define IDD_UPDATE_DIALOG_10_                    706
#define IDD_UPDATE_DIALOG_11_                    707
#define IDD_UPDATE_DIALOG_2_                     708
#define IDD_UPDATE_DIALOG_3_                     709
#define IDD_UPDATE_DIALOG_4_                     710
#define IDD_UPDATE_DIALOG_5_                     711
#define IDD_UPDATE_DIALOG_6_                     712
#define IDD_UPDATE_DIALOG_7_                     713
#define IDD_UPDATE_DIALOG_8_                     714
#define IDD_UPDATE_DIALOG_9_                     715
#define IDD_VIRTUAL_SERVER                       716
#define IDD_WAIT_MESSAGE_1_                      717
#define IDD_WAIT_MESSAGE_10_                     718
#define IDD_WAIT_MESSAGE_11_                     719
#define IDD_WAIT_MESSAGE_2_                      720
#define IDD_WAIT_MESSAGE_3_                      721
#define IDD_WAIT_MESSAGE_4_                      722
#define IDD_WAIT_MESSAGE_5_                      723
#define IDD_WAIT_MESSAGE_6_                      724
#define IDD_WAIT_MESSAGE_7_                      725
#define IDD_WAIT_MESSAGE_8_                      726
#define IDD_WAIT_MESSAGE_9_                      727
#define IDD_WELCOME                              728
#define IDI_SERVICE                              729
#define IDI_SETUP                                730
#define IDNEXT                                   731
#define IDNOTOALL                                732
#define IDR_AVI_FILECOPY                         733
#define IDR_AVI_FILEDEL                          734
#define IDS_65_AND_OLDER_VER_1_                  735
#define IDS_65_AND_OLDER_VER_2_                  736
#define IDS_65_AND_OLDER_VER_3_                  737
#define IDS_661_GROUP_NAME_1_                    738
#define IDS_661_GROUP_NAME_2_                    739
#define IDS_661_GROUP_NAME_3_                    740
#define IDS_661_GROUP_NAME_4_                    741
#define IDS_661W2K_GROUP_NAME_1_                 742
#define IDS_661W2K_GROUP_NAME_2_                 743
#define IDS_AADR_DESC                            744
#define IDS_AADR_TITLE                           745
#define IDS_AADRENABLE                           746
#define IDS_AADRENABLE_NOTE                      747
#define IDS_AADRENABLE_NOTE1                     748
#define IDS_AADRENABLE_NOTE2                     749
#define IDS_AADRENABLE_NOTE3                     750
#define IDS_ACCOUNT_IS_TOO_LONG_1_               751
#define IDS_ACCOUNT_IS_TOO_LONG_2_               752
#define IDS_ACCOUNT_IS_TOO_LONG_3_               753
#define IDS_ACCOUNT_TOO_LONG                     754
#define IDS_ACCOUNTHEADERSUBTITLE_1_             755
#define IDS_ACCOUNTHEADERSUBTITLE_2_             756
#define IDS_ACCOUNTHEADERSUBTITLE_3_             757
#define IDS_ACCOUNTHEADERSUBTITLE_4_             758
#define IDS_ACCOUNTHEADERSUBTITLE_5_             759
#define IDS_ACCOUNTHEADERSUBTITLE_6_             760
#define IDS_ACCOUNTHEADERTITLE_1_                761
#define IDS_ACCOUNTHEADERTITLE_2_                762
#define IDS_ACCOUNTHEADERTITLE_3_                763
#define IDS_ACCOUNTHEADERTITLE_4_                764
#define IDS_ADD_1_                               765
#define IDS_ADD_2_                               766
#define IDS_ADD_3_                               767
#define IDS_ADD_4_                               768
#define IDS_ADD_SYS_DSN_FAIL                     769
#define IDS_ADD_SYSTEM_PRIVILEGE                 770
#define IDS_ADDTO_ADMINGROUP                     771
#define IDS_ADMIN_ERROR_1_                       772
#define IDS_ADMIN_ERROR_2_                       773
#define IDS_ADMIN_ERROR_3_                       774
#define IDS_ADMIN_ERROR_4_                       775
#define IDS_ADMIN_ERROR_5_                       776
#define IDS_ADMIN_ERROR_6_                       777
#define IDS_ADMIN_ERROR_7_                       778
#define IDS_ADMIN_ERROR_8_                       779
#define IDS_AGENT_ADMIN_CAPTION_1_               780
#define IDS_AGENT_ADMIN_CAPTION_2_               781
#define IDS_ALERT                                782
#define IDS_ALERT_1_                             783
#define IDS_ALERT_2_                             784
#define IDS_ALREADY_INSTALL                      785
#define IDS_ALREADY_INSTALL_1_                   786
#define IDS_ALREADY_INSTALL_2_                   787
#define IDS_ALREADY_INSTALLED_1_                 788
#define IDS_ALREADY_INSTALLED_2_                 789
#define IDS_ALREADY_INSTALLED_3_                 790
#define IDS_ALREADY_INSTALLED_4_                 791
#define IDS_ALTERNATE_ERROR                      792
#define IDS_ANOTHER_AGENT_1_                     793
#define IDS_ANOTHER_AGENT_2_                     794
#define IDS_ANOTHER_AGENT_3_                     795
#define IDS_ANOTHER_AGENT_4_                     796
#define IDS_ANOTHER_AGENT_5_                     797
#define IDS_ANOTHER_AGENT_CONTINUE_1_            798
#define IDS_ANOTHER_AGENT_CONTINUE_2_            799
#define IDS_ANOTHER_AGENT_CONTINUE_3_            800
#define IDS_API_CALL_FAIL_1_                     801
#define IDS_API_CALL_FAIL_2_                     802
#define IDS_API_CALL_FAIL_3_                     803
#define IDS_API_CALL_FAIL_4_                     804
#define IDS_API_CALL_FAIL_5_                     805
#define IDS_API_CALL_FAIL_6_                     806
#define IDS_ARCSERVE_IMPROPER_EDITION_1_         807
#define IDS_ARCSERVE_IMPROPER_EDITION_2_         808
#define IDS_ARCSERVE_IMPROPER_EDITION_3_         809
#define IDS_ARCSERVE_IMPROPER_EDITION_4_         810
#define IDS_ARCSERVE_IMPROPER_EDITION_5_         811
#define IDS_ARCSERVE_IMPROPER_EDITION_6_         812
#define IDS_ARCSERVE66NOTINSTALLED_1_            813
#define IDS_ARCSERVE66NOTINSTALLED_2_            814
#define IDS_ARCSERVE66NOTINSTALLED_3_            815
#define IDS_ARCSERVE66NOTINSTALLED_4_            816
#define IDS_ARCSERVE66NOTINSTALLED_5_            817
#define IDS_ARCSERVE66NOTINSTALLED_6_            818
#define IDS_ARCSERVE66NOTINSTALLED_7_            819
#define IDS_ARCSERVE66NOTINSTALLED_8_            820
#define IDS_ARCSERVE66NOTINSTALLED2              821
#define IDS_ARCSERVENOTINSTALLED_1_              822
#define IDS_ARCSERVENOTINSTALLED_2_              823
#define IDS_ARCSERVENOTINSTALLED_3_              824
#define IDS_ARCSERVENOTINSTALLED_4_              825
#define IDS_ARCSERVENOTINSTALLED_5_              826
#define IDS_ARCSERVENOTINSTALLED_6_              827
#define IDS_ARCSERVENOTINSTALLED_7_              828
#define IDS_ARCSERVENOTINSTALLED2                829
#define IDS_ARCSERVEPROGRAMGROUP                 830
#define IDS_ARCSERVESERVERNOTINSTALLED_1_        831
#define IDS_ARCSERVESERVERNOTINSTALLED_2_        832
#define IDS_ARCSERVESERVERNOTINSTALLED_3_        833
#define IDS_ARCSERVESERVERNOTINSTALLED_4_        834
#define IDS_ARCSERVESERVERNOTINSTALLED_5_        835
#define IDS_ARCSERVESERVERNOTINSTALLED_6_        836
#define IDS_ARCSERVESERVERNOTINSTALLED_7_        837
#define IDS_ARCSERVESERVERNOTINSTALLED_8_        838
#define IDS_ARCSERVESERVERNOTINSTALLED2          839
#define IDS_ARCSERVEWND                          840
#define IDS_ASK_REBOOT                           841
#define IDS_ASKREMOVEOLDDR                       842
#define IDS_ASO_VALID_UPGRADE                    843
#define IDS_AUTHENTICATE_FAILED                  844
#define IDS_AUTHENTICATION                       845
#define IDS_AUTOCONFIGRUNNING                    846
#define IDS_BCREATE_AUTH_FAILED                  847
#define IDS_BDC_USER_CREATE_FAILED               848
#define IDS_BETA_CDKEY                           849
#define IDS_BETA_CDKEY_1_                        850
#define IDS_BETA_CDKEY_2_                        851
#define IDS_BLOCK_SIZE                           852
#define IDS_BRIGHTSTOR_PRO                       853
#define IDS_BRWSFLD_TITLE                        854
#define IDS_BUILD_MISMATCH                       855
#define IDS_BUILD_NUMBER                         856
#define IDS_BUILD_NUMBER_1_                      857
#define IDS_BUILD_NUMBER_2_                      858
#define IDS_BUILD_NUMBER_3_                      859
#define IDS_BUTTON_SKIP                          860
#define IDS_BUTTON_SKIP_1_                       861
#define IDS_BUTTON_SKIP_2_                       862
#define IDS_CA_LICENSE_FAILED_1_                 863
#define IDS_CA_LICENSE_FAILED_2_                 864
#define IDS_CA_LICENSE_FAILED_3_                 865
#define IDS_CA_LICENSE_FAILED_4_                 866
#define IDS_CA_LICENSE_FAILED_5_                 867
#define IDS_CA_LICENSE_FAILED_6_                 868
#define IDS_CALICENSE_FAILED_1_                  869
#define IDS_CALICENSE_FAILED_2_                  870
#define IDS_CALICENSE_FAILED_3_                  871
#define IDS_CALICENSE_FAILED_4_                  872
#define IDS_CALICENSE_FAILED_5_                  873
#define IDS_CALICENSE_FAILED_6_                  874
#define IDS_CANCEL_VIRTUAL_ACCOUNT               875
#define IDS_CANCELOPERATION                      876
#define IDS_CANCELOPERATION_1_                   877
#define IDS_CANCELOPERATION_2_                   878
#define IDS_CANCELOPERATION_3_                   879
#define IDS_CANCELOPERATION_4_                   880
#define IDS_CANNOT_FIND_INSTALLER                881
#define IDS_CANNOT_FIND_INSTALLER_1_             882
#define IDS_CANNOT_FIND_INSTALLER_2_             883
#define IDS_CANNOT_FIND_SNMP                     884
#define IDS_CANNOT_FIND_TAPE_LIBRARY_1_          885
#define IDS_CANNOT_FIND_TAPE_LIBRARY_2_          886
#define IDS_CANNOT_FIND_WORLDVIEW                887
#define IDS_CANNOT_LOAD_DLL                      888
#define IDS_CANNOT_LOAD_DLL_1_                   889
#define IDS_CANNOT_LOAD_DLL_2_                   890
#define IDS_CANNOT_LOCATE_LICFILE                891
#define IDS_CANNOT_LOCATE_LICFILE_1_             892
#define IDS_CANNOT_LOCATE_LICFILE_2_             893
#define IDS_CANNOT_LOCATE_LICFILE_3_             894
#define IDS_CANNOT_LOCATE_LICFILE_4_             895
#define IDS_CANNOT_RSETUP                        896
#define IDS_CANNOT_START_DS                      897
#define IDS_CANNOT_STOP_DS                       898
#define IDS_CANNOT_UPGRADE                       899
#define IDS_CANNOTCONTINUE                       900
#define IDS_CANNOTCONTINUE_1_                    901
#define IDS_CANNOTCONTINUE_2_                    902
#define IDS_CANNOTCONTINUE_3_                    903
#define IDS_CANNOTCONTINUE_4_                    904
#define IDS_CANNOTFINDIBMLIBMANAGER              905
#define IDS_CANNOTFINDLIBATTACH                  906
#define IDS_CANNOTFINDPATH                       907
#define IDS_CANNOTINSTALLARCHIVE                 908
#define IDS_CANNOTINSTALLARCHIVE_1_              909
#define IDS_CANNOTINSTALLARCHIVE_2_              910
#define IDS_CANNOTINSTALLARCHIVE_3_              911
#define IDS_CANT_EMPTY                           912
#define IDS_CANT_ENVI                            913
#define IDS_CANT_INIT                            914
#define IDS_CANT_LIBBSA                          915
#define IDS_CANT_MSM                             916
#define IDS_CANT_QUERY_PATH                      917
#define IDS_CANT_SET_PATH                        918
#define IDS_CAPTION                              919
#define IDS_CD                                   920
#define IDS_CD_1_                                921
#define IDS_CD_2_                                922
#define IDS_CFGWIZARD_TITLE_1_                   923
#define IDS_CFGWIZARD_TITLE_2_                   924
#define IDS_CFGWIZARD_TITLE_3_                   925
#define IDS_CFGWIZARD_TITLE_4_                   926
#define IDS_CFGWIZARD_TITLE_5_                   927
#define IDS_CFGWIZARD_TITLE_6_                   928
#define IDS_CFGWIZARD_TITLE_7_                   929
#define IDS_CHECK_SETUPINFO                      930
#define IDS_CHECK_SETUPINFO_1_                   931
#define IDS_CHECK_SETUPINFO_2_                   932
#define IDS_CHECK_UNINSTALLINFO                  933
#define IDS_CHECK_UNINSTALLINFO_1_               934
#define IDS_CHECK_UNINSTALLINFO_2_               935
#define IDS_CHECKENVIRONMENT_1_                  936
#define IDS_CHECKENVIRONMENT_2_                  937
#define IDS_CHECKENVIRONMENT_3_                  938
#define IDS_CHECKENVIRONMENT_4_                  939
#define IDS_CHECKENVIRONMENT_5_                  940
#define IDS_CHECKENVIRONMENT_6_                  941
#define IDS_CHECKENVIRONMENT_7_                  942
#define IDS_CHEYSAQ                              943
#define IDS_CLEANINGREGISTRY                     944
#define IDS_CLEANINGREGISTRY_1_                  945
#define IDS_CLEANINGREGISTRY_2_                  946
#define IDS_CLEANINGREGISTRY_3_                  947
#define IDS_CLEANINGREGISTRY_4_                  948
#define IDS_CLIENTAGENT_1_                       949
#define IDS_CLIENTAGENT_2_                       950
#define IDS_CLIENTSERVICE_1_                     951
#define IDS_CLIENTSERVICE_2_                     952
#define IDS_CLIENTSERVICE_3_                     953
#define IDS_CLIENTSERVICE_4_                     954
#define IDS_CLUS_CONFIRM_PW                      955
#define IDS_CLUS_PW                              956
#define IDS_CLUS_USER_NAME                       957
#define IDS_CLUSTER_MSG                          958
#define IDS_CLUSTER_SERVER                       959
#define IDS_CLUSTER_SERVER_PASSWORD              960
#define IDS_CLUSTER_SERVER_USER_NAME             961
#define IDS_CLUSTER_TITLE                        962
#define IDS_CLUSTER_USER_NAME                    963
#define IDS_CONFIG_CANCEL                        964
#define IDS_CONFIG_CANCEL_1_                     965
#define IDS_CONFIG_CANCEL_2_                     966
#define IDS_CONFIG_CANCEL_3_                     967
#define IDS_CONFIG_CANCEL_4_                     968
#define IDS_CONFIG_CANCEL_5_                     969
#define IDS_CONFIG_CANCEL_6_                     970
#define IDS_CONFIG_SUCCEED                       971
#define IDS_CONFIG_SUCCEED_1_                    972
#define IDS_CONFIG_SUCCEED_2_                    973
#define IDS_CONFIG_TITLE_1_                      974
#define IDS_CONFIG_TITLE_2_                      975
#define IDS_CONFIG_WARNING                       976
#define IDS_CONFIG_WARNING_1_                    977
#define IDS_CONFIG_WARNING_2_                    978
#define IDS_CONFIGDONE_1_                        979
#define IDS_CONFIGDONE_2_                        980
#define IDS_CONFIGDONE_3_                        981
#define IDS_CONFIGDONE_4_                        982
#define IDS_CONFIGDONE_5_                        983
#define IDS_CONFIGURATION_1_                     984
#define IDS_CONFIGURATION_2_                     985
#define IDS_CONFIGURATION_3_                     986
#define IDS_CONFIGURATION_4_                     987
#define IDS_CONFIGURATION_5_                     988
#define IDS_CONFIGURE_DONE                       989
#define IDS_CONFIGURE_FAILED                     990
#define IDS_CONFIGURE_RETRY                      991
#define IDS_CONFIGURED                           992
#define IDS_CONFIGURESERVER_1_                   993
#define IDS_CONFIGURESERVER_2_                   994
#define IDS_CONFIRM                              995
#define IDS_CONFIRM_1_                           996
#define IDS_CONFIRM_2_                           997
#define IDS_CONFIRM_DELETE_ACCOUNT_1_            998
#define IDS_CONFIRM_DELETE_ACCOUNT_2_            999
#define IDS_CONFIRM_DELETE_ACCOUNT_3_            1000
#define IDS_CONFIRM_PW                           1001
#define IDS_CONFIRM_PW_1_                        1002
#define IDS_CONFIRM_PW_2_                        1003
#define IDS_CONFIRMPASSWORD_1_                   1004
#define IDS_CONFIRMPASSWORD_2_                   1005
#define IDS_CONFIRMPASSWORD_3_                   1006
#define IDS_CONTINUEOPERATION                    1007
#define IDS_CONTINUEOPERATION_1_                 1008
#define IDS_CONTINUEOPERATION_2_                 1009
#define IDS_CONTINUEOPERATION_3_                 1010
#define IDS_COPY_CALICENSE                       1011
#define IDS_COPY_CALICENSE_1_                    1012
#define IDS_COPY_CALICENSE_2_                    1013
#define IDS_COPY_CALICENSE_3_                    1014
#define IDS_COPY_CALICENSE_4_                    1015
#define IDS_COPY_CALICENSE_5_                    1016
#define IDS_COPYFILES                            1017
#define IDS_COPYFILES_1_                         1018
#define IDS_COPYFILES_2_                         1019
#define IDS_COPYFILES_3_                         1020
#define IDS_CREATE_ACCOUNT                       1021
#define IDS_CREATE_ACCOUNT_EX2000                1022
#define IDS_CREATE_ACCOUNT_EX55                  1023
#define IDS_CREATE_ACCOUNT_FAILED                1024
#define IDS_CREATE_ICONS                         1025
#define IDS_CREATE_ICONS_1_                      1026
#define IDS_CREATE_ICONS_2_                      1027
#define IDS_CREATE_ICONS_3_                      1028
#define IDS_CREATE_ICONS_4_                      1029
#define IDS_CREATE_ICONS_5_                      1030
#define IDS_CREATE_ICONS_6_                      1031
#define IDS_CREATE_REGISTRY                      1032
#define IDS_CREATE_REGISTRY_1_                   1033
#define IDS_CREATE_REGISTRY_2_                   1034
#define IDS_CREATE_REGISTRY_3_                   1035
#define IDS_CREATE_REGISTRY_FAIL_1_              1036
#define IDS_CREATE_REGISTRY_FAIL_10_             1037
#define IDS_CREATE_REGISTRY_FAIL_11_             1038
#define IDS_CREATE_REGISTRY_FAIL_12_             1039
#define IDS_CREATE_REGISTRY_FAIL_13_             1040
#define IDS_CREATE_REGISTRY_FAIL_2_              1041
#define IDS_CREATE_REGISTRY_FAIL_3_              1042
#define IDS_CREATE_REGISTRY_FAIL_4_              1043
#define IDS_CREATE_REGISTRY_FAIL_5_              1044
#define IDS_CREATE_REGISTRY_FAIL_6_              1045
#define IDS_CREATE_REGISTRY_FAIL_7_              1046
#define IDS_CREATE_REGISTRY_FAIL_8_              1047
#define IDS_CREATE_REGISTRY_FAIL_9_              1048
#define IDS_CREATE_REMOTE_DBAGENT_SERVICE_FAIL   1049
#define IDS_CREATE_SERVICE_FAIL_1_               1050
#define IDS_CREATE_SERVICE_FAIL_2_               1051
#define IDS_CREATE_SERVICE_FAIL_3_               1052
#define IDS_CREATE_SERVICE_FAIL_4_               1053
#define IDS_CREATE_SUCCESSFUL                    1054
#define IDS_CREATE_TARGET_DIR                    1055
#define IDS_CURRENT_VERSION_INSTALLED            1056
#define IDS_DBAPROGRAMGROUP                      1057
#define IDS_DBENGINE                             1058
#define IDS_DBENGINE_1_                          1059
#define IDS_DBENGINE_2_                          1060
#define IDS_DEFAULT_INSTANCE_PASSWORD_ISNOT_CONFIRMED 1061
#define IDS_DEFAULT_INSTANCE_PASSWORD_TOO_LONG   1062
#define IDS_DELETE_1_                            1063
#define IDS_DELETE_2_                            1064
#define IDS_DELETE_3_                            1065
#define IDS_DELETE_4_                            1066
#define IDS_DELETE_DEFAULT_INSTANCE              1067
#define IDS_DELETE_SERVICE_FAIL                  1068
#define IDS_DELETE_SERVICE_FAIL_1_               1069
#define IDS_DELETE_SERVICE_FAIL_2_               1070
#define IDS_DIRECTORY_IS_TOO_LONG                1071
#define IDS_DISCRIPTER_REGISTER_FAIL_1_          1072
#define IDS_DISCRIPTER_REGISTER_FAIL_2_          1073
#define IDS_DISCRIPTER_REGISTER_FAIL_3_          1074
#define IDS_DISCRIPTER_REGISTER_FAIL_4_          1075
#define IDS_DISCRIPTER_REGISTER_FAIL_5_          1076
#define IDS_DISCRIPTER_REGISTER_FAIL_6_          1077
#define IDS_DISCRIPTER_REGISTER_FAIL_7_          1078
#define IDS_DISCRIPTER_UNREGISTER_FAIL_1_        1079
#define IDS_DISCRIPTER_UNREGISTER_FAIL_2_        1080
#define IDS_DISCRIPTER_UNREGISTER_FAIL_3_        1081
#define IDS_DISCRIPTER_UNREGISTER_FAIL_4_        1082
#define IDS_DOMAIN_IS_TOO_LONG                   1083
#define IDS_DONE_SAPINSTALL                      1084
#define IDS_DOUBLE_INSTANCE                      1085
#define IDS_DOUBLE_SID                           1086
#define IDS_DOUBLESID                            1087
#define IDS_DRCREATECAPTION                      1088
#define IDS_DRCREATERUNNING                      1089
#define IDS_DRIVER_NOT_FOUND                     1090
#define IDS_DRO_WARNING                          1091
#define IDS_DRWCAPTION                           1092
#define IDS_DRWRUNNING                           1093
#define IDS_DS_ALTERNATE_ERROR1                  1094
#define IDS_DSOCONFIG_CAPTION                    1095
#define IDS_DSSERVICE_INSTALL_FAIL_1_            1096
#define IDS_DSSERVICE_INSTALL_FAIL_2_            1097
#define IDS_DSSERVICE_INSTALL_FAIL_3_            1098
#define IDS_DSSERVICE_INSTALL_FAIL_4_            1099
#define IDS_DSSERVICE_INSTALL_FAIL_5_            1100
#define IDS_DSSERVICE_UNINSTALL_FAIL_1_          1101
#define IDS_DSSERVICE_UNINSTALL_FAIL_2_          1102
#define IDS_DSSERVICE_UNINSTALL_FAIL_3_          1103
#define IDS_DSSERVICE_UNINSTALL_FAIL_4_          1104
#define IDS_DSSERVICE_UNINSTALL_FAIL_5_          1105
#define IDS_ELO                                  1106
#define IDS_EMPTY_VIR_MAILBOX                    1107
#define IDS_EMPTY_VIR_MAILBOX2                   1108
#define IDS_EMPTY_VIR_SRV_NAME                   1109
#define IDS_EMPTY_VIR_SRVC_ACCOUNT               1110
#define IDS_ENABLE_MESSAGES                      1111
#define IDS_ENTER_INSTANCE                       1112
#define IDS_ENTER_LOGINID                        1113
#define IDS_ENTER_SID                            1114
#define IDS_ENTERLOGIN_1_                        1115
#define IDS_ENTERLOGIN_2_                        1116
#define IDS_ENTERLOGIN_3_                        1117
#define IDS_ENTERPASSWORD                        1118
#define IDS_ENTERSID                             1119
#define IDS_ERROR_CONFIG_IBM                     1120
#define IDS_ERROR_CONFIG_NLO                     1121
#define IDS_ERROR_CREATE_PATH                    1122
#define IDS_ERROR_EXEC_VERIFY                    1123
#define IDS_ERROR_INVALID_PATH                   1124
#define IDS_ERROR_LOAD_WINUSERUPD                1125
#define IDS_ERROR_OLO                            1126
#define IDS_ERROR_TLO                            1127
#define IDS_ERROR_WINUSERUPD                     1128
#define IDS_EXCH_BASE_NOT_INSTALL                1129
#define IDS_EXCHANGE_SERVER_NOT_FOUND            1130
#define IDS_FAIL_TO_GET_ACCOUNT_INFO             1131
#define IDS_FAIL_UPDATE_ONCONFIG                 1132
#define IDS_FAILED_CONFIG_FOR_CREATE             1133
#define IDS_FAILED_CONFIG_SUCCESSFUL_CREATE      1134
#define IDS_FAILED_CONVERSION                    1135
#define IDS_FAILED_IN_COPYFILE                   1136
#define IDS_FAILED_IN_DELETEFILE                 1137
#define IDS_FAILED_INSTALL_DS_1_                 1138
#define IDS_FAILED_INSTALL_DS_2_                 1139
#define IDS_FAILED_INSTALL_DS_3_                 1140
#define IDS_FAILED_TO_DELETE_FILE                1141
#define IDS_FAILED_TO_INSTALL                    1142
#define IDS_FAILED_TO_INSTALL_1_                 1143
#define IDS_FAILED_TO_INSTALL_2_                 1144
#define IDS_FAILED_TO_REMOVE_DIR                 1145
#define IDS_FCR_FAILED                           1146
#define IDS_FOLDER_DOESNOT_EXIST                 1147
#define IDS_FORDER_NAME                          1148
#define IDS_FSM_FAILED                           1149
#define IDS_GROUP_NAME_66                        1150
#define IDS_GROUP_SAPSQL_66                      1151
#define IDS_GROUP_SQL_66                         1152
#define IDS_HBM_INSTALL_ERROR                    1153
#define IDS_HBM_INSTALL_FAIL                     1154
#define IDS_HBMDRIVER                            1155
#define IDS_HPEA_PROD_NAME                       1156
#define IDS_IBM_NAME                             1157
#define IDS_IBMLO                                1158
#define IDS_ILLEGAL_CHAR_1_                      1159
#define IDS_ILLEGAL_CHAR_2_                      1160
#define IDS_ILLEGAL_CHAR_3_                      1161
#define IDS_IMPROPER_EDITION_1_                  1162
#define IDS_IMPROPER_EDITION_2_                  1163
#define IDS_IMPROPER_EDITION_3_                  1164
#define IDS_IMPROPER_EDITION_4_                  1165
#define IDS_INFORMIX_SERVER_NOT_FOUND            1166
#define IDS_INGRES_SERVER_NOT_FOUND              1167
#define IDS_INITIALIZE                           1168
#define IDS_INITIALIZE_1_                        1169
#define IDS_INITIALIZE_2_                        1170
#define IDS_INITIALIZE_3_                        1171
#define IDS_INITIALIZE_4_                        1172
#define IDS_INSERTCD                             1173
#define IDS_INSERTCD_1_                          1174
#define IDS_INSERTCD_2_                          1175
#define IDS_INSERTCD_3_                          1176
#define IDS_INSERTCD_4_                          1177
#define IDS_INSTALL_AADR                         1178
#define IDS_INSTALL_COMPLETED                    1179
#define IDS_INSTALL_COMPLETED_1_                 1180
#define IDS_INSTALL_COMPLETED_2_                 1181
#define IDS_INSTALL_COMPLETED_3_                 1182
#define IDS_INSTALL_COMPLETED_4_                 1183
#define IDS_INSTALL_COMPLETED_5_                 1184
#define IDS_INSTALL_COMPLETED_6_                 1185
#define IDS_INSTALL_HBMS_FAILED                  1186
#define IDS_INSTALL_SERVICE                      1187
#define IDS_INSTALL_SERVICE_1_                   1188
#define IDS_INSTALL_SERVICE_2_                   1189
#define IDS_INSTALL_SERVICE_3_                   1190
#define IDS_INSTALL_SERVICE_4_                   1191
#define IDS_INSTALLDONE_1_                       1192
#define IDS_INSTALLDONE_2_                       1193
#define IDS_INSTALLDONE_3_                       1194
#define IDS_INSTALLDONE_4_                       1195
#define IDS_INSTALLDONE_5_                       1196
#define IDS_INSTALLDRIVER                        1197
#define IDS_INSTALLNETPC                         1198
#define IDS_INSTALLNETPC_FAIL                    1199
#define IDS_INSTALLSTEP1                         1200
#define IDS_INSTALLSTEP1_1_                      1201
#define IDS_INSTALLSTEP1_2_                      1202
#define IDS_INSTANCE                             1203
#define IDS_INSTANCE_NAME_EXISTS                 1204
#define IDS_INSTANCE_NULL                        1205
#define IDS_INSTANCE_NULL_1_                     1206
#define IDS_INSTANCE_NULL_2_                     1207
#define IDS_INSTANCE_PASSWORD_ISNOT_CONFIRMED    1208
#define IDS_INSTANCE_PASSWORD_TOO_LONG           1209
#define IDS_INSTANCE_TOO_LONG                    1210
#define IDS_INSTANCE_TOO_LONG_1_                 1211
#define IDS_INSTANCE_TOO_LONG_2_                 1212
#define IDS_INSUFFICIENT_INFO                    1213
#define IDS_INVALID_ACCOUNT_NAME                 1214
#define IDS_INVALID_CDKEY1                       1215
#define IDS_INVALID_CDKEY1_1_                    1216
#define IDS_INVALID_CDKEY1_2_                    1217
#define IDS_INVALID_CDKEY1_3_                    1218
#define IDS_INVALID_CDKEY1_4_                    1219
#define IDS_INVALID_CDKEY1_5_                    1220
#define IDS_INVALID_CDKEY1_6_                    1221
#define IDS_INVALID_CDKEY1_7_                    1222
#define IDS_INVALID_CDKEY1_8_                    1223
#define IDS_INVALID_EXCH_ACCT                    1224
#define IDS_INVALID_IFMX                         1225
#define IDS_INVALID_INSTANCE                     1226
#define IDS_INVALID_INSTANCE_NAME                1227
#define IDS_INVALID_PATH                         1228
#define IDS_INVALID_PATH_1_                      1229
#define IDS_INVALID_PATH_2_                      1230
#define IDS_INVALID_PATH_3_                      1231
#define IDS_INVALID_PATH_4_                      1232
#define IDS_INVALID_PATH2                        1233
#define IDS_INVALID_PATH2_1_                     1234
#define IDS_INVALID_PATH2_2_                     1235
#define IDS_INVALID_PWD_1_                       1236
#define IDS_INVALID_PWD_2_                       1237
#define IDS_INVALID_PWD_3_                       1238
#define IDS_INVALID_PWD_4_                       1239
#define IDS_INVALID_PWD2                         1240
#define IDS_INVALID_PWD2_1_                      1241
#define IDS_INVALID_PWD2_2_                      1242
#define IDS_INVALID_PWD2_3_                      1243
#define IDS_INVALID_SID_1_                       1244
#define IDS_INVALID_SID_2_                       1245
#define IDS_INVALID_SRV_NAME                     1246
#define IDS_INVALID_UPGRADE_1_                   1247
#define IDS_INVALID_UPGRADE_2_                   1248
#define IDS_INVALID_UPGRADE_3_                   1249
#define IDS_INVALID_UPGRADE_4_                   1250
#define IDS_INVALID_UPGRADE_5_                   1251
#define IDS_INVALID_UPGRADE_6_                   1252
#define IDS_INVALID_UPGRADE_7_                   1253
#define IDS_INVALID_UPGRADE1                     1254
#define IDS_IO_NAME                              1255
#define IDS_IS_UNINST_EXE                        1256
#define IDS_IS_UNINST_EXE_1_                     1257
#define IDS_IS_UNINST_EXE_2_                     1258
#define IDS_ISCLUSTER_EXCHANGE                   1259
#define IDS_JOBENGINE                            1260
#define IDS_LOAD_FAIL                            1261
#define IDS_LOAD_FAIL1                           1262
#define IDS_LOAD_FAIL2                           1263
#define IDS_LOAD_FAIL3                           1264
#define IDS_LOAD_LIBRARY_FAIL_1_                 1265
#define IDS_LOAD_LIBRARY_FAIL_2_                 1266
#define IDS_LOAD_LIBRARY_FAIL_3_                 1267
#define IDS_LOAD_LIBRARY_FAIL_4_                 1268
#define IDS_LOAD_LIBRARY_FAIL_5_                 1269
#define IDS_LOAD_LIBRARY_FAIL_6_                 1270
#define IDS_LOAD_LICENSE_FAIL                    1271
#define IDS_LOAD_LICENSE_FAIL_1_                 1272
#define IDS_LOAD_LICENSE_FAIL_2_                 1273
#define IDS_LOAD_LICENSE_FAIL_3_                 1274
#define IDS_LOAD_LICENSE_FAIL_4_                 1275
#define IDS_LOAD_LICENSE_FAIL_5_                 1276
#define IDS_LOGIN_ID                             1277
#define IDS_LOGINID                              1278
#define IDS_LOGINID_1_                           1279
#define IDS_LOGINID_2_                           1280
#define IDS_LOGINID_TOO_LONG                     1281
#define IDS_LOGINID_TOO_LONG_1_                  1282
#define IDS_LOGINID_TOO_LONG_2_                  1283
#define IDS_MACHINE_TOO_LONG                     1284
#define IDS_MACHINE_TOO_LONG_1_                  1285
#define IDS_MACHINE_TOO_LONG_2_                  1286
#define IDS_MACHINENAME                          1287
#define IDS_MAILBOX                              1288
#define IDS_MAILBOX_INVALID                      1289
#define IDS_MAILBOX_IS_TOO_LONG                  1290
#define IDS_MIXED_MODE                           1291
#define IDS_MODIFY_1_                            1292
#define IDS_MODIFY_2_                            1293
#define IDS_MODIFY_3_                            1294
#define IDS_MODIFY_4_                            1295
#define IDS_MS_ASO_VALID_UPGRADE                 1296
#define IDS_MS_VALID_UPGRADE_1_                  1297
#define IDS_MS_VALID_UPGRADE_2_                  1298
#define IDS_MS_VALID_UPGRADE_B                   1299
#define IDS_MS_VALID_UPGRADE1_1_                 1300
#define IDS_MS_VALID_UPGRADE1_2_                 1301
#define IDS_MS_VALID_UPGRADEASO                  1302
#define IDS_MSGENGINE                            1303
#define IDS_MSGENGINE_1_                         1304
#define IDS_MSGENGINE_2_                         1305
#define IDS_MSGENGINE_3_                         1306
#define IDS_MSGENGINERUNNING_1_                  1307
#define IDS_MSGENGINERUNNING_2_                  1308
#define IDS_MSGENGINERUNNING_3_                  1309
#define IDS_MSGENGINERUNNING_4_                  1310
#define IDS_MSGENGINERUNNING_5_                  1311
#define IDS_MSGENGINERUNNING_6_                  1312
#define IDS_MSGENGINERUNNING_7_                  1313
#define IDS_MSGENGINERUNNING_8_                  1314
#define IDS_MSGENGINERUNNING_9_                  1315
#define IDS_MSGFILEINUSE                         1316
#define IDS_NAS_EXIST                            1317
#define IDS_NEED_CONFIG                          1318
#define IDS_NETWORK_PROTOCOL                     1319
#define IDS_NETWORK_PROTOCOL_NAMED_PIPES         1320
#define IDS_NETWORK_PROTOCOL_TCPIP               1321
#define IDS_NETWORK_PROTOCOL_VI                  1322
#define IDS_NETWORKHEADERSUBTITLE                1323
#define IDS_NETWORKHEADERTITLE                   1324
#define IDS_NEW_ITEM_1_                          1325
#define IDS_NEW_ITEM_2_                          1326
#define IDS_NEW_ITEM_3_                          1327
#define IDS_NLO                                  1328
#define IDS_NLO_NAME                             1329
#define IDS_NLOCONFIG_CAPTION                    1330
#define IDS_NO_SERVER_INSTALLED                  1331
#define IDS_NO_SQL_INSTALLED                     1332
#define IDS_NO_UPDATE_INFO                       1333
#define IDS_NOACCOUNT_1_                         1334
#define IDS_NOACCOUNT_2_                         1335
#define IDS_NOACCOUNT_3_                         1336
#define IDS_NOACCOUNT_4_                         1337
#define IDS_NOT_CONFIGURED                       1338
#define IDS_NOT_ENOUGH_SPACE_1_                  1339
#define IDS_NOT_ENOUGH_SPACE_2_                  1340
#define IDS_NOT_ENOUGH_SPACE_3_                  1341
#define IDS_NOT_ENOUGH_SPACE_4_                  1342
#define IDS_NOT_ENOUGH_SPACE_5_                  1343
#define IDS_NOT_ENOUGH_SPACE_6_                  1344
#define IDS_NOT_ENOUGH_SPACE_7_                  1345
#define IDS_NOT_ENOUGH_SPACE_8_                  1346
#define IDS_NOT_ENOUGH_SPACE_9_                  1347
#define IDS_NOTES_SERVER_NOT_FOUND               1348
#define IDS_NOTES_SERVER_NOT_FOUND_1             1349
#define IDS_NOTESAGENT_EXIST                     1350
#define IDS_NSOCONFIG_CAPTION_1_                 1351
#define IDS_NSOCONFIG_CAPTION_2_                 1352
#define IDS_NT_AUTHENTICATION                    1353
#define IDS_NT_MACHINE                           1354
#define IDS_NT_ORACLE_FAIL_SAFE_ACCOUNT          1355
#define IDS_NT_PASSWORD_TOO_LONG                 1356
#define IDS_NT351_NOT_SUPPORTED                  1357
#define IDS_NT351_NOT_SUPPORTED_1_               1358
#define IDS_NT351_NOT_SUPPORTED_2_               1359
#define IDS_NTSERVER                             1360
#define IDS_OLD_GROUP_NAME_1_                    1361
#define IDS_OLD_GROUP_NAME_2_                    1362
#define IDS_OLD_GROUP_NAME_3_                    1363
#define IDS_OLD_IBM_INSTALLED                    1364
#define IDS_OLD_IO_INSTALLED                     1365
#define IDS_OLD_NLO_INSTALLED                    1366
#define IDS_OLD_OLO_INSTALLED                    1367
#define IDS_OLD_PRODUCT_INSTALLED_1_             1368
#define IDS_OLD_PRODUCT_INSTALLED_2_             1369
#define IDS_OLD_PRODUCT_INSTALLED_3_             1370
#define IDS_OLD_SBO_INSTALLED                    1371
#define IDS_OLD_TLO_INSTALLED                    1372
#define IDS_OLD_UNINSTALL_KEY                    1373
#define IDS_OLD95AGENT_PROGRAMNAME               1374
#define IDS_OLD95AGENT_PROGRAMNAME_1_            1375
#define IDS_OLD95AGENT_PROGRAMNAME_2_            1376
#define IDS_OLDARCNAME_1_                        1377
#define IDS_OLDARCNAME_2_                        1378
#define IDS_OLDARCNAME_3_                        1379
#define IDS_OLDDRCREATECAPTION                   1380
#define IDS_OLDDRWCAPTION                        1381
#define IDS_OLDER_GROUP_NAME_1_                  1382
#define IDS_OLDER_GROUP_NAME_2_                  1383
#define IDS_OLDGROUPNAME                         1384
#define IDS_OLDNTAGENT_PROGRAMNAME_1_            1385
#define IDS_OLDNTAGENT_PROGRAMNAME_2_            1386
#define IDS_OLDNTAGENT_PROGRAMNAME_3_            1387
#define IDS_OLDRELNAME_1_                        1388
#define IDS_OLDRELNAME_2_                        1389
#define IDS_OLDRELNAME_3_                        1390
#define IDS_OLDRELNAME_4_                        1391
#define IDS_OLO_NAME                             1392
#define IDS_OPTION_BUNDLED                       1393
#define IDS_OPTION_NOAVAILABLE                   1394
#define IDS_OPTION_NOTAVAILABLE_1_               1395
#define IDS_OPTION_NOTAVAILABLE_2_               1396
#define IDS_OPTION_NOTAVAILABLE_3_               1397
#define IDS_OPTION_NOTAVAILABLE_4_               1398
#define IDS_OPTION_NOTAVAILABLE_5_               1399
#define IDS_OPTION_NOTAVAILABLE_6_               1400
#define IDS_ORA_INSTALLED                        1401
#define IDS_ORACLE_NETWORK_NAME                  1402
#define IDS_ORACLE_SAP_NOT_FOUND                 1403
#define IDS_ORACLESAP_INSTALLED                  1404
#define IDS_OVERWRITE_NEW_1_                     1405
#define IDS_OVERWRITE_NEW_10_                    1406
#define IDS_OVERWRITE_NEW_2_                     1407
#define IDS_OVERWRITE_NEW_3_                     1408
#define IDS_OVERWRITE_NEW_4_                     1409
#define IDS_OVERWRITE_NEW_5_                     1410
#define IDS_OVERWRITE_NEW_6_                     1411
#define IDS_OVERWRITE_NEW_7_                     1412
#define IDS_OVERWRITE_NEW_8_                     1413
#define IDS_OVERWRITE_NEW_9_                     1414
#define IDS_PASSWORD                             1415
#define IDS_PASSWORD_1_                          1416
#define IDS_PASSWORD_2_                          1417
#define IDS_PASSWORD_3_                          1418
#define IDS_PASSWORD_IS_TOO_LONG                 1419
#define IDS_PASSWORD_IS_TOO_LONG_1_              1420
#define IDS_PASSWORD_IS_TOO_LONG_2_              1421
#define IDS_PASSWORD_IS_TOO_LONG_3_              1422
#define IDS_PASSWORD_ISNOT_CONFIRMED_1_          1423
#define IDS_PASSWORD_ISNOT_CONFIRMED_2_          1424
#define IDS_PASSWORD_ISNOT_CONFIRMED_3_          1425
#define IDS_PASSWORD_ISNOT_CONFIRMED_4_          1426
#define IDS_PASSWORD_TOO_LONG                    1427
#define IDS_PATH_INVALID                         1428
#define IDS_PGROUPNAMEDBA66_1_                   1429
#define IDS_PGROUPNAMEDBA66_2_                   1430
#define IDS_PGROUPNAMEDBA66_SAP                  1431
#define IDS_PGROUPNAMEDBA661                     1432
#define IDS_PLATFORM_IO_WARNING                  1433
#define IDS_PLATFORM_SBO_WARNING                 1434
#define IDS_PLATFORM_WARNING                     1435
#define IDS_PLATFORM_WARNING_1_                  1436
#define IDS_PLATFORM_WARNING_2_                  1437
#define IDS_PLEASEINSTALL                        1438
#define IDS_PREVINST_DETECTED                    1439
#define IDS_PREVINST_DETECTED_1_                 1440
#define IDS_PREVINST_DETECTED_2_                 1441
#define IDS_PREVINST_DETECTED_3_                 1442
#define IDS_PREVINST_DETECTED_4_                 1443
#define IDS_PREVINST_DETECTED_5_                 1444
#define IDS_PREVIOUS_AGENT_CONTINUE_1_           1445
#define IDS_PREVIOUS_AGENT_CONTINUE_2_           1446
#define IDS_PREVIOUS_AGENT_CONTINUE_3_           1447
#define IDS_PREVIOUS_AGENT_CONTINUE_4_           1448
#define IDS_PREVIOUS_AGENT_CONTINUE_5_           1449
#define IDS_PREVIOUS_AGENT_CONTINUE_6_           1450
#define IDS_PREVIOUS_AGENT_CONTINUE_7_           1451
#define IDS_PREVIOUS_AGENT_CONTINUE_8_           1452
#define IDS_PREVIOUS_AGENT_CONTINUE_9_           1453
#define IDS_PREVIOUS_REMOVE_FAIL_1_              1454
#define IDS_PREVIOUS_REMOVE_FAIL_2_              1455
#define IDS_PRIVILEGE_NOT_HELD                   1456
#define IDS_PROD_CAN_NOT_UPDATED_1_              1457
#define IDS_PROD_CAN_NOT_UPDATED_2_              1458
#define IDS_PRODDISPLAYNAME                      1459
#define IDS_PRODUCT_EXISTS_1_                    1460
#define IDS_PRODUCT_EXISTS_2_                    1461
#define IDS_PRODUCT_EXISTS_3_                    1462
#define IDS_PRODUCT_EXISTS_4_                    1463
#define IDS_PRODUCT_EXISTS_5_                    1464
#define IDS_PRODUCT_EXISTS_6_                    1465
#define IDS_PRODUCT_EXISTS_7_                    1466
#define IDS_PRODUCT_IBM_INSTALLED                1467
#define IDS_PRODUCT_INSTALLED                    1468
#define IDS_PRODUCT_INSTALLED_1_                 1469
#define IDS_PRODUCT_INSTALLED_2_                 1470
#define IDS_PRODUCT_INSTALLED_3_                 1471
#define IDS_PRODUCT_IO_INSTALLED                 1472
#define IDS_PRODUCT_NAME_95_1_                   1473
#define IDS_PRODUCT_NAME_95_2_                   1474
#define IDS_PRODUCT_NAME_ASM_1_                  1475
#define IDS_PRODUCT_NAME_ASM_2_                  1476
#define IDS_PRODUCT_NAME_ASM_3_                  1477
#define IDS_PRODUCT_NAME_ASM_4_                  1478
#define IDS_PRODUCT_NAME_ASM_5_                  1479
#define IDS_PRODUCT_NAME_ASM_6_                  1480
#define IDS_PRODUCT_NAME_ASO_1_                  1481
#define IDS_PRODUCT_NAME_ASO_2_                  1482
#define IDS_PRODUCT_NAME_ASO_3_                  1483
#define IDS_PRODUCT_NAME_ASO_4_                  1484
#define IDS_PRODUCT_NAME_ASO_5_                  1485
#define IDS_PRODUCT_NAME_ASO_6_                  1486
#define IDS_PRODUCT_NAME_ASO_7_                  1487
#define IDS_PRODUCT_NAME_EE_1_                   1488
#define IDS_PRODUCT_NAME_EE_2_                   1489
#define IDS_PRODUCT_NAME_EE_3_                   1490
#define IDS_PRODUCT_NAME_EE_4_                   1491
#define IDS_PRODUCT_NAME_EE_5_                   1492
#define IDS_PRODUCT_NAME_EE_6_                   1493
#define IDS_PRODUCT_NAME_EE_7_                   1494
#define IDS_PRODUCT_NAME_NAS                     1495
#define IDS_PRODUCT_NAME_NT_1_                   1496
#define IDS_PRODUCT_NAME_NT_2_                   1497
#define IDS_PRODUCT_NAME_SF                      1498
#define IDS_PRODUCT_NAME_WG_1_                   1499
#define IDS_PRODUCT_NAME_WG_2_                   1500
#define IDS_PRODUCT_NAME_WG_3_                   1501
#define IDS_PRODUCT_NAME_WG_4_                   1502
#define IDS_PRODUCT_NAME_WG_5_                   1503
#define IDS_PRODUCT_NAME_WG_6_                   1504
#define IDS_PRODUCT_NAME_WG_7_                   1505
#define IDS_PRODUCT_NLO_INSTALLED                1506
#define IDS_PRODUCT_OLO_INSTALLED                1507
#define IDS_PRODUCT_SBO_INSTALLED                1508
#define IDS_PRODUCT_SHORT_NAME_1_                1509
#define IDS_PRODUCT_SHORT_NAME_10_               1510
#define IDS_PRODUCT_SHORT_NAME_11_               1511
#define IDS_PRODUCT_SHORT_NAME_12_               1512
#define IDS_PRODUCT_SHORT_NAME_13_               1513
#define IDS_PRODUCT_SHORT_NAME_14_               1514
#define IDS_PRODUCT_SHORT_NAME_15_               1515
#define IDS_PRODUCT_SHORT_NAME_16_               1516
#define IDS_PRODUCT_SHORT_NAME_2_                1517
#define IDS_PRODUCT_SHORT_NAME_3_                1518
#define IDS_PRODUCT_SHORT_NAME_4_                1519
#define IDS_PRODUCT_SHORT_NAME_5_                1520
#define IDS_PRODUCT_SHORT_NAME_6_                1521
#define IDS_PRODUCT_SHORT_NAME_7_                1522
#define IDS_PRODUCT_SHORT_NAME_8_                1523
#define IDS_PRODUCT_SHORT_NAME_9_                1524
#define IDS_PRODUCT_SHORT_NAME_IBM               1525
#define IDS_PRODUCT_SHORT_NAME_OLO               1526
#define IDS_PRODUCT_SHORT_NAME_SAP_1_            1527
#define IDS_PRODUCT_SHORT_NAME_SAP_2_            1528
#define IDS_PRODUCT_SHORT_NAME2                  1529
#define IDS_PRODUCT_SUBTYPE_1_                   1530
#define IDS_PRODUCT_SUBTYPE_2_                   1531
#define IDS_PRODUCT_SUBTYPE_3_                   1532
#define IDS_PRODUCT_SUBTYPE_4_                   1533
#define IDS_PRODUCT_SUBTYPE_5_                   1534
#define IDS_PRODUCT_TLO_INSTALLED                1535
#define IDS_PRODUCT_UPGRADE_1_                   1536
#define IDS_PRODUCT_UPGRADE_2_                   1537
#define IDS_PRODUCT_UPGRADE_3_                   1538
#define IDS_PRODUCT_UPGRADE_MS                   1539
#define IDS_PRODUCT_UPGRADE_SILENT               1540
#define IDS_PRODUCT_UPGRADE1                     1541
#define IDS_PROFILECAUSE                         1542
#define IDS_PROFILECAUSE_1_                      1543
#define IDS_PROFILECAUSE_2_                      1544
#define IDS_PROFILECAUSE_3_                      1545
#define IDS_PROFILEEXPLAIN                       1546
#define IDS_PROFILEEXPLAIN_1_                    1547
#define IDS_PROFILEEXPLAIN_2_                    1548
#define IDS_PROFILEEXPLAIN_3_                    1549
#define IDS_PROFILEEXPLAIN_4_                    1550
#define IDS_PROFILEEXPLAIN_5_                    1551
#define IDS_PROFILEEXPLAIN_6_                    1552
#define IDS_REALLYCANCEL_1_                      1553
#define IDS_REALLYCANCEL_10_                     1554
#define IDS_REALLYCANCEL_11_                     1555
#define IDS_REALLYCANCEL_12_                     1556
#define IDS_REALLYCANCEL_13_                     1557
#define IDS_REALLYCANCEL_2_                      1558
#define IDS_REALLYCANCEL_3_                      1559
#define IDS_REALLYCANCEL_4_                      1560
#define IDS_REALLYCANCEL_5_                      1561
#define IDS_REALLYCANCEL_6_                      1562
#define IDS_REALLYCANCEL_7_                      1563
#define IDS_REALLYCANCEL_8_                      1564
#define IDS_REALLYCANCEL_9_                      1565
#define IDS_REBOOT_MACHINE_UNINSTALL             1566
#define IDS_REBOOT_SERVICEUNINSTALL              1567
#define IDS_REBOOT_SERVICEUNINSTALL_1_           1568
#define IDS_REBOOT_SERVICEUNINSTALL_2_           1569
#define IDS_REBOOT_SILENT                        1570
#define IDS_REG_EXCHDBA_BL                       1571
#define IDS_REG_EXCHDBA_DB                       1572
#define IDS_REG_EXCHDBA_IFS                      1573
#define IDS_REG_ROOT_KEY                         1574
#define IDS_REMOTE_CAPTION                       1575
#define IDS_REMOTE_CAPTION_1_                    1576
#define IDS_REMOTE_CAPTION_2_                    1577
#define IDS_REMOTE_DBAGENT_SERVICE               1578
#define IDS_REMOVE_DISCOVERYSERVICE              1579
#define IDS_REMOVEOLDDR                          1580
#define IDS_REMOVING_PREV_HDS                    1581
#define IDS_REMOVING_PREV_HP_DISK_ARRAY          1582
#define IDS_REMOVING_PREV_NTAGENT                1583
#define IDS_REMOVING_PREV_VERSION_1_             1584
#define IDS_REMOVING_PREV_VERSION_2_             1585
#define IDS_REMOVING_PREV_VERSION_3_             1586
#define IDS_REMOVING_PREV_VERSION_4_             1587
#define IDS_REMOVING_PREV_VERSION_5_             1588
#define IDS_REMOVING_PREV_VERSION_6_             1589
#define IDS_REMOVING_PREV_VERSION_7_             1590
#define IDS_REMOVING_PREV_VERSION_8_             1591
#define IDS_REMOVING_RAID_1_                     1592
#define IDS_REMOVING_RAID_2_                     1593
#define IDS_REMOVINGCOMPONENTS                   1594
#define IDS_REMOVINGCOMPONENTS_1_                1595
#define IDS_REMOVINGCOMPONENTS_2_                1596
#define IDS_REMOVINGDATABASE                     1597
#define IDS_REMOVINGDATABASE_1_                  1598
#define IDS_REMOVINGDATABASE_2_                  1599
#define IDS_REMOVINGDATABASE_3_                  1600
#define IDS_REMOVINGDRIVE                        1601
#define IDS_REMOVINGDRIVER                       1602
#define IDS_REMOVINGFILES                        1603
#define IDS_REMOVINGFILES_1_                     1604
#define IDS_REMOVINGFILES_2_                     1605
#define IDS_REMOVINGFILES_3_                     1606
#define IDS_RESTART_MACHINE                      1607
#define IDS_RESTART_ORACLE_SERVICE               1608
#define IDS_RESTART_RPC                          1609
#define IDS_RMANOTHER_CLIENT_AGENT_CONTINUE_1_   1610
#define IDS_RMANOTHER_CLIENT_AGENT_CONTINUE_2_   1611
#define IDS_RMANOTHER_CLIENT_AGENT_CONTINUE_3_   1612
#define IDS_RMANOTHER_CLIENT_AGENT_CONTINUE_4_   1613
#define IDS_RMANOTHER_CLIENT_AGENT_CONTINUE_5_   1614
#define IDS_RMANOTHER_CLIENT_AGENT_CONTINUE_6_   1615
#define IDS_RMANOTHER_CLIENT_AGENT_CONTINUE_7_   1616
#define IDS_RMARCSERVE_IMPROPER_EDITION          1617
#define IDS_RMARCSERVE66NOTINSTALLED_1_          1618
#define IDS_RMARCSERVE66NOTINSTALLED_2_          1619
#define IDS_RMARCSERVE66NOTINSTALLED_3_          1620
#define IDS_RMARCSERVE66NOTINSTALLED_4_          1621
#define IDS_RMARCSERVE66NOTINSTALLED_5_          1622
#define IDS_RMARCSERVESERVERNOTINSTALLED         1623
#define IDS_RMASK_REBOOT_1_                      1624
#define IDS_RMASK_REBOOT_2_                      1625
#define IDS_RMASK_REBOOT_3_                      1626
#define IDS_RMOPTION_NOTAVAILABLE_1_             1627
#define IDS_RMOPTION_NOTAVAILABLE_2_             1628
#define IDS_RMOPTION_NOTAVAILABLE_3_             1629
#define IDS_RMSERVERNT_1_                        1630
#define IDS_RMSERVERNT_2_                        1631
#define IDS_RMSERVERNT_3_                        1632
#define IDS_RMSERVERNT_4_                        1633
#define IDS_RMSERVERNT_5_                        1634
#define IDS_RO_WARNING                           1635
#define IDS_RUNNING_INSTALL                      1636
#define IDS_RUNNING_INSTALL_1_                   1637
#define IDS_RUNNING_INSTALL_2_                   1638
#define IDS_RUNNING_INSTALL_3_                   1639
#define IDS_RUNNING_UNINSTALL                    1640
#define IDS_RUNNING_UNINSTALL_1_                 1641
#define IDS_RUNNING_UNINSTALL_2_                 1642
#define IDS_RUNNING_UNINSTALL_3_                 1643
#define IDS_SAN_REQUIRED                         1644
#define IDS_SAN_WARNING                          1645
#define IDS_SAPCONFIG_CAPTION                    1646
#define IDS_SAPORA_INSTALLED                     1647
#define IDS_SAPORA_INSTALLED_1_                  1648
#define IDS_SAPORA_INSTALLED_2_                  1649
#define IDS_SAPSQL_INSTALLED                     1650
#define IDS_SAPSQL_INSTALLED_1_                  1651
#define IDS_SAPSQL_INSTALLED_2_                  1652
#define IDS_SAVE_SETUPINFO                       1653
#define IDS_SBO                                  1654
#define IDS_SBO_1_                               1655
#define IDS_SBO_2_                               1656
#define IDS_SBO_NAME                             1657
#define IDS_SELECT_TO_DELETE                     1658
#define IDS_SELECT_TO_DELETE_1_                  1659
#define IDS_SELECT_TO_DELETE_2_                  1660
#define IDS_SELECT_TO_MODIFY_1_                  1661
#define IDS_SELECT_TO_MODIFY_2_                  1662
#define IDS_SERVERHEADERSUBTITLE                 1663
#define IDS_SERVERHEADERTITLE                    1664
#define IDS_SERVERID_IS_TOO_LONG                 1665
#define IDS_SERVICE_ACCOUNT                      1666
#define IDS_SERVICEPACKNOTINSTALLED              1667
#define IDS_SERVICERUNNING_1_                    1668
#define IDS_SERVICERUNNING_2_                    1669
#define IDS_SERVICERUNNING_3_                    1670
#define IDS_SETTINGS_FAIL                        1671
#define IDS_SETUP_CANNOTCONTINUE                 1672
#define IDS_SETUP_VALID_UPGRADE1_1_              1673
#define IDS_SETUP_VALID_UPGRADE1_2_              1674
#define IDS_SETUPISNOTCOMPLETE                   1675
#define IDS_SHARING_VIOLATION                    1676
#define IDS_SHARING_VIOLATION_1_                 1677
#define IDS_SHARING_VIOLATION_2_                 1678
#define IDS_SID_1_                               1679
#define IDS_SID_2_                               1680
#define IDS_SID_NULL                             1681
#define IDS_SID_PASSWORD_ISNOT_CONFIRMED         1682
#define IDS_SID_PASSWORD_TOO_LONG                1683
#define IDS_SID_TOO_LONG                         1684
#define IDS_SMARTBACKUP_STOP_FAIL                1685
#define IDS_SMARTBACKUP_STOP_FAIL_1_             1686
#define IDS_SMARTBACKUP_STOP_FAIL_2_             1687
#define IDS_SPECIFY_DIRECTORY_1_                 1688
#define IDS_SPECIFY_DIRECTORY_2_                 1689
#define IDS_SPECIFY_DIRECTORY_3_                 1690
#define IDS_SQL_AUTHENTICATION                   1691
#define IDS_SQL_INSTALLED                        1692
#define IDS_SQL_SERVER_NOT_FOUND                 1693
#define IDS_SQL7_NOT_SUPPORTED                   1694
#define IDS_START_SERVICE_FAIL                   1695
#define IDS_START_SERVICE_FAIL_1_                1696
#define IDS_START_SERVICE_FAIL_2_                1697
#define IDS_START_SERVICE_FAIL_3_                1698
#define IDS_START_SNMP                           1699
#define IDS_STOP_ORACLE_SERVICE                  1700
#define IDS_STOP_SERVICE_1_                      1701
#define IDS_STOP_SERVICE_2_                      1702
#define IDS_STOP_SERVICE_3_                      1703
#define IDS_STOP_SERVICE_4_                      1704
#define IDS_STOP_SERVICE_5_                      1705
#define IDS_STOP_SERVICE_FAIL                    1706
#define IDS_STOP_SNMP                            1707
#define IDS_SUBTYPE_ADVANCED                     1708
#define IDS_SUBTYPE_ENTERPRISE                   1709
#define IDS_SUBTYPE_ERROR_1_                     1710
#define IDS_SUBTYPE_ERROR_10_                    1711
#define IDS_SUBTYPE_ERROR_11_                    1712
#define IDS_SUBTYPE_ERROR_2_                     1713
#define IDS_SUBTYPE_ERROR_3_                     1714
#define IDS_SUBTYPE_ERROR_4_                     1715
#define IDS_SUBTYPE_ERROR_5_                     1716
#define IDS_SUBTYPE_ERROR_6_                     1717
#define IDS_SUBTYPE_ERROR_7_                     1718
#define IDS_SUBTYPE_ERROR_8_                     1719
#define IDS_SUBTYPE_ERROR_9_                     1720
#define IDS_SUBTYPE_NAME_ADV                     1721
#define IDS_SUBTYPE_NAME_ADV_1_                  1722
#define IDS_SUBTYPE_NAME_ADV_2_                  1723
#define IDS_SUBTYPE_NAME_ASM                     1724
#define IDS_SUBTYPE_NAME_ASO                     1725
#define IDS_SUBTYPE_NAME_ASO_1_                  1726
#define IDS_SUBTYPE_NAME_ASO_2_                  1727
#define IDS_SUBTYPE_NAME_EE                      1728
#define IDS_SUBTYPE_NAME_WG                      1729
#define IDS_SUBTYPE_NAME_WG_1_                   1730
#define IDS_SUBTYPE_NAME_WG_2_                   1731
#define IDS_SUBTYPE_TNG_ASM                      1732
#define IDS_SUBTYPE_TNG_ASO_1_                   1733
#define IDS_SUBTYPE_TNG_ASO_2_                   1734
#define IDS_SUBTYPE_TNG_ASO_3_                   1735
#define IDS_SUBTYPE_UNKNOWN                      1736
#define IDS_SUBTYPE_WORKGROUP                    1737
#define IDS_SUBTYPE_WORKGROUP_ADVANCED           1738
#define IDS_SUCCESS_UNINSTALL                    1739
#define IDS_SYBASE_NOT_EXIST                     1740
#define IDS_SYBASE_ROOTDIR_NOT_EXIST             1741
#define IDS_SYBASE_SERVER_NOT_FOUND              1742
#define IDS_SYSACCOUNTINFO                       1743
#define IDS_TAPEENGINE                           1744
#define IDS_TITLE_1_                             1745
#define IDS_TITLE_2_                             1746
#define IDS_TITLE_3_                             1747
#define IDS_TITLE_4_                             1748
#define IDS_TITLE_VIRT                           1749
#define IDS_TLO_NAME                             1750
#define IDS_TNGF_INSTALL_ERROR                   1751
#define IDS_TNGF_INSTALL_FAIL                    1752
#define IDS_TRIAL_CDKEY                          1753
#define IDS_TRIAL_CDKEY_1_                       1754
#define IDS_TRIAL_CDKEY_2_                       1755
#define IDS_UI_WARNING                           1756
#define IDS_UNABLE_MSG_ENGINE                    1757
#define IDS_UNABLE_MSG_ENGINE_1_                 1758
#define IDS_UNABLE_MSG_ENGINE_2_                 1759
#define IDS_UNEXPECT_1_                          1760
#define IDS_UNEXPECT_2_                          1761
#define IDS_UNEXPECT_3_                          1762
#define IDS_UNICENTER125BACKUPINSTALLED_1_       1763
#define IDS_UNICENTER125BACKUPINSTALLED_2_       1764
#define IDS_UNICENTER125BACKUPINSTALLED_3_       1765
#define IDS_UNICENTER125BACKUPINSTALLED_4_       1766
#define IDS_UNICENTER125BACKUPINSTALLED_5_       1767
#define IDS_UNICENTER125BACKUPINSTALLED2         1768
#define IDS_UNINFCR_FAILED                       1769
#define IDS_UNINST_ERROR                         1770
#define IDS_UNINSTALL_CANNOTCONTINUE             1771
#define IDS_UNINSTALL_ERROR_1_                   1772
#define IDS_UNINSTALL_ERROR_2_                   1773
#define IDS_UNINSTALL_HBMS_FAILED                1774
#define IDS_UNINSTALLPREVIOUSAGENT               1775
#define IDS_UNINSTALLPREVIOUSAGENT_1_            1776
#define IDS_UNINSTALLPREVIOUSAGENT_2_            1777
#define IDS_UNINSTALLTAPE_1_                     1778
#define IDS_UNINSTALLTAPE_2_                     1779
#define IDS_UNINSTALLTAPE_3_                     1780
#define IDS_UNKNOWN_EDITION                      1781
#define IDS_UNKNOWN_EDITION_1_                   1782
#define IDS_UNKNOWN_EDITION_2_                   1783
#define IDS_UNKNOWN_EDITION_3_                   1784
#define IDS_UNKNOWN_EDITION_4_                   1785
#define IDS_UPDATE_LIB                           1786
#define IDS_UPDATE_MSI_1_                        1787
#define IDS_UPDATE_MSI_2_                        1788
#define IDS_UPDATE_MSI_3_                        1789
#define IDS_UPDATE_MSI_4_                        1790
#define IDS_UPDATE_MSI_5_                        1791
#define IDS_UPDATE_MSI_6_                        1792
#define IDS_UPDATE_ONCONFIG                      1793
#define IDS_UPDATE_REGISTRY                      1794
#define IDS_UPDATE_REGISTRY_1_                   1795
#define IDS_UPDATE_REGISTRY_2_                   1796
#define IDS_UPGRADE_FAIL_1_                      1797
#define IDS_UPGRADE_FAIL_10_                     1798
#define IDS_UPGRADE_FAIL_11_                     1799
#define IDS_UPGRADE_FAIL_12_                     1800
#define IDS_UPGRADE_FAIL_13_                     1801
#define IDS_UPGRADE_FAIL_14_                     1802
#define IDS_UPGRADE_FAIL_2_                      1803
#define IDS_UPGRADE_FAIL_3_                      1804
#define IDS_UPGRADE_FAIL_4_                      1805
#define IDS_UPGRADE_FAIL_5_                      1806
#define IDS_UPGRADE_FAIL_6_                      1807
#define IDS_UPGRADE_FAIL_7_                      1808
#define IDS_UPGRADE_FAIL_8_                      1809
#define IDS_UPGRADE_FAIL_9_                      1810
#define IDS_UPGRADE_FAIL_RAID                    1811
#define IDS_UPGRADE_INFORMATION_1_               1812
#define IDS_UPGRADE_INFORMATION_2_               1813
#define IDS_UPGRADE_INFORMATION_3_               1814
#define IDS_UPGRADE_INFORMATION_4_               1815
#define IDS_UPGRADE_INFORMATION_5_               1816
#define IDS_UPGRADE_INFORMATION_6_               1817
#define IDS_UPGRADE_INFORMATION_ELO              1818
#define IDS_UPGRADE_NEED_REBOOT                  1819
#define IDS_UPGRADE_TITLE                        1820
#define IDS_UPGRADE_WARNING_1_                   1821
#define IDS_UPGRADE_WARNING_2_                   1822
#define IDS_UPGRADE_WARNING_IBM                  1823
#define IDS_UPGRADE_WARNING_IO                   1824
#define IDS_UPGRADE_WARNING_NLO                  1825
#define IDS_UPGRADE_WARNING_OLO                  1826
#define IDS_UPGRADE_WARNING_SB                   1827
#define IDS_UPGRADE_WARNING_TLO                  1828
#define IDS_USER_PASSWORD_ISNOT_CONFIRMED        1829
#define IDS_USER_PASSWORD_ISNOT_CONFIRMED_1_     1830
#define IDS_USER_PASSWORD_ISNOT_CONFIRMED_2_     1831
#define IDS_USER_PASSWORD_TOO_LONG               1832
#define IDS_USER_TOO_LONG                        1833
#define IDS_USER_TOO_LONG_1_                     1834
#define IDS_USER_TOO_LONG_2_                     1835
#define IDS_USERNAME                             1836
#define IDS_VALID_UPGRADE_1                      1837
#define IDS_VALID_UPGRADE_1_                     1838
#define IDS_VALID_UPGRADE_1_1_                   1839
#define IDS_VALID_UPGRADE_1_2_                   1840
#define IDS_VALID_UPGRADE_2                      1841
#define IDS_VALID_UPGRADE_2_                     1842
#define IDS_VALID_UPGRADE_2_1_                   1843
#define IDS_VALID_UPGRADE_2_2_                   1844
#define IDS_VALID_UPGRADE_3_                     1845
#define IDS_VALID_UPGRADE_3_1_                   1846
#define IDS_VALID_UPGRADE_3_2_                   1847
#define IDS_VALID_UPGRADE_4_                     1848
#define IDS_VALID_UPGRADE_5_                     1849
#define IDS_VALID_UPGRADE_6_                     1850
#define IDS_VALID_UPGRADE_7_                     1851
#define IDS_VALID_UPGRADE_8_                     1852
#define IDS_VALID_UPGRADE_9_                     1853
#define IDS_VALID_UPGRADE_ASO_1_                 1854
#define IDS_VALID_UPGRADE_ASO_2_                 1855
#define IDS_VALID_UPGRADE_ASO_R3_1_              1856
#define IDS_VALID_UPGRADE_ASO_R3_2_              1857
#define IDS_VALID_UPGRADE_B                      1858
#define IDS_VALID_UPGRADE_R3_1_                  1859
#define IDS_VALID_UPGRADE_R3_2_                  1860
#define IDS_VALID_UPGRADE_SILENCE_1_             1861
#define IDS_VALID_UPGRADE_SILENCE_2_             1862
#define IDS_VALID_UPGRADE_SILENCE_ASO_1_         1863
#define IDS_VALID_UPGRADE_SILENCE_ASO_2_         1864
#define IDS_VALID_UPGRADE_SILENCE_ASO_R3_1_      1865
#define IDS_VALID_UPGRADE_SILENCE_ASO_R3_2_      1866
#define IDS_VALID_UPGRADE_SILENCE_R3_1_          1867
#define IDS_VALID_UPGRADE_SILENCE_R3_2_          1868
#define IDS_VALID_UPGRADE1                       1869
#define IDS_VALID_UPGRADE2                       1870
#define IDS_VALID_UPGRADE3                       1871
#define IDS_VALID_UPGRADEASO                     1872
#define IDS_VERIFYPWD                            1873
#define IDS_VIRSQL_INFORMATION                   1874
#define IDS_VIRSQLNAME_INSTANCE                  1875
#define IDS_VIRSRV_NAME_EXISTS                   1876
#define IDS_VIRTUAL_MAILBOX                      1877
#define IDS_VIRTUAL_PASSWORD                     1878
#define IDS_VIRTUAL_SERVER_NAME                  1879
#define IDS_VIRTUAL_SERVICE_ACCOUNT              1880
#define IDS_VIRTUAL_SQL_NAME                     1881
#define IDS_VIRTUAL_SQL_SERVER_NAME              1882
#define IDS_VOLUMECONFIG_CAPTION                 1883
#define IDS_VOLUMECONFIGRUNNING                  1884
#define IDS_VSQL_NAME                            1885
#define IDS_W95AGENT_STOP_FAIL_1_                1886
#define IDS_W95AGENT_STOP_FAIL_2_                1887
#define IDS_W95AGENT_STOP_FAIL_3_                1888
#define IDS_W95AGENT_STOP_FAIL_4_                1889
#define IDS_W95AGENT_STOP_FAIL_5_                1890
#define IDS_W95AGENT_STOP_FAIL_6_                1891
#define IDS_WANT_TO_INSTALL                      1892
#define IDS_WANT_TO_INSTALL_1_                   1893
#define IDS_WANT_TO_INSTALL_2_                   1894
#define IDS_WARNING                              1895
#define IDS_WARNING_1_                           1896
#define IDS_WARNING_2_                           1897
#define IDS_WARNING_MSG                          1898
#define IDS_WARNING_MSG_1_                       1899
#define IDS_WARNING_MSG_2_                       1900
#define IDS_WARNING_MSG_3_                       1901
#define IDS_WARNING_MSG_4_                       1902
#define IDS_WELCOME                              1903
#define IDS_WELCOME_1_                           1904
#define IDS_WELCOME_2_                           1905
#define IDS_WELCOME_3_                           1906
#define IDS_WELCOME_4_                           1907
#define IDS_WELCOME_5_                           1908
#define IDS_WIN_MODE                             1909
#define IDS_WIN2000_INSTALL                      1910
#define IDS_WINDOWS95                            1911
#define IDS_WINDOWSNT                            1912
#define IDS_WINVERSION_ERR                       1913
#define IDS_WIZBUTTON_BACK                       1914
#define IDS_WIZBUTTON_BACK_1_                    1915
#define IDS_WIZBUTTON_BACK_2_                    1916
#define IDS_WIZBUTTON_BACK_3_                    1917
#define IDS_WIZBUTTON_CANCEL                     1918
#define IDS_WIZBUTTON_CANCEL_1_                  1919
#define IDS_WIZBUTTON_CANCEL_2_                  1920
#define IDS_WIZBUTTON_FINISH                     1921
#define IDS_WIZBUTTON_FINISH_1_                  1922
#define IDS_WIZBUTTON_FINISH_2_                  1923
#define IDS_WIZBUTTON_FINISH_3_                  1924
#define IDS_WIZBUTTON_NEXT                       1925
#define IDS_WIZBUTTON_NEXT_1_                    1926
#define IDS_WIZBUTTON_NEXT_2_                    1927
#define IDS_WIZBUTTON_NEXT_3_                    1928
#define IDS_WRONGPASSWORD                        1929
#define SD_STA_IMAGE_2                           1930
#define SD_STA_IMAGE_3                           1931

#endif

