//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by e:\project\R12.v\BrightStor r11.5\BB\RCModules\Setup\DeployDummyRes.DLL\MasterSetup_e.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CAWIZARDDLG_DIALOG          102
#define IDD_DIALOG_BASE                 102
#define IDS_MAINTENANCE_TITLE           102
#define IDC_LIST_STATUS                 112
#define IDR_MAINFRAME                   128
#define IDR_HTML_START                  140
#define IDR_HTML_INSTALL1               141
#define IDR_CCS                         148
#define IDB_WIZ97_BANNER256             210
#define IDB_WATERMARK256                211
#define IDB_BLANK                       212
#define IDD_STATUS_PANEL                213
#define IDB_BITMAP2                     214
#define IDB_BITMAP_STATUS               214
#define IDB_BITMAP1                     215
#define IDB_BITMAP_INFORMATION          215
#define IDB_BITMAP3                     216
#define IDB_MESSAGE_ICONS               216
#define IDD_DIALOG_STEP1                217
#define IDD_DIALOG_RUNATDVD             217
#define IDD_DIALOG_FIXPACKAGE           218
#define IDS_PREREQUISITES_NAME          341
#define IDS_PREREQUISITES_STATUS        342
#define IDS_STRING_PENDING              343
#define IDS_STRING_INSTALLING           344
#define IDS_STRING_INSTALLED            345
#define IDS_STRING_FAILED               346
#define IDS_STRING_MSG_INSTALLING       347
#define IDS_STRING_MSG_INSTALLFINISH    348
#define IDS_INSTALL_WARNING_MSG         349
#define IDS_INSTALL_WARNING_TITLE       350
#define IDS_STRING_APPLICATION_TITLE    351
#define IDS_ERROR_RUN_DUMMY             352
#define IDS_STRING_SUBTITLE             353
#define IDS_ADMIN_ERROR                 353
#define IDS_STRING_WIZ_INSTALL          354
#define IDS_STRING_WIZ_CANCEL           355
#define IDS_DISPLAYRESOLUTION_WARNING   356
#define IDS_SETUP_CANCEL                357
#define IDS_INSTALL_PACKAGE_GUIDE       358
#define IDS_STRING_WIZ_CONTINUE         358
#define IDS_ERR_SPECIFY_VALIDPATH       359
#define IDS_REBOOT_WARNING_MSG          360
#define IDS_TITLE_MASTERSETUP           361
#define IDS_INSTALLFILES                362
#define IDC_BUTTON_NEXT                 1000
#define IDC_STATIC_TOP                  1002
#define IDC_STATIC_MIDDLE               1003
#define IDC_STATIC_LINE                 1005
#define IDC_STATIC_LINE2                1006
#define IDC_BANNER                      1006
#define IDC_BUTTON_INSTALL              1007
#define ID_BUTTON_INSTALL               1007
#define IDC_STATIC_DESCRIPT             1020
#define IDC_LIST_PREREQUISITES          1023
#define IDC_PROGRESS_INSTALLPRE         1024
#define IDC_STATIC_SUBTITLE             1025
#define IDC_STATIC_INSTALLING_MSG       1026
#define IDS_STRING_MSG_FAILED           1026
#define IDC_STATIC_T1                   1123
#define IDC_STATIC_T3                   1125
#define IDC_STATIC_T4                   1126
#define IDC_STATIC_T5                   1127
#define IDC_PROGRESS1                   1128
#define IDC_STATIC_T6                   1128
#define IDC_EDIT_INSTPATH               1129
#define IDC_EDIT_DVDPATH                1130
#define IDC_STATIC_T7                   1131
#define IDC_BT_SOURCEPATH               1132
#define IDC_STATIC_T8                   1132
#define IDC_EDIT_SOURCEPATH             1133
#define IDC_STATIC_TA1                  1134
#define IDC_STATIC_TA2                  1135
#define IDC_STATIC_TA3                  1136
#define IDC_STATIC_TA4                  1137
#define IDC_EDIT_INSTPATH_FIX           1138
#define IDC_EDIT_DVDPATH_FIX            1138
#define IDC_BT_SEL_DVDPATH              1139
#define IDC_BT_SEL_DVDPATH2             1140
#define IDC_EDIT_INSTPATH_REPAIR        1141
#define IDC_STATIC_T9                   1142
#define IDC_STATIC_GUIDE                1142
#define IDC_STATIC_GUIDE_01             1143
#define IDC_STATIC_GUIDE_02             1144
#define IDC_STATIC_WEBSITE              1145
#define IDC_STATIC_GUIDE_11             1145
#define IDC_STATIC_README               1146
#define IDC_STATIC_GUIDE_12             1146
#define IDC_STATIC_GUIDE_21             1147
#define IDC_STATIC_GUIDE_22             1148
#define IDC_STATIC_T2                   1149
#define IDC_STATIC_T10_1                1150
#define IDC_TREE_STATUS                 1151
#define IDC_STATIC_T10                  1152
#define IDC_STATIC_T11_1                1153
#define IDC_STATIC_T11                  1154
#define IDC_BT_BROWSER                  1160
#define IDC_BT_BROWSERDVD               1161
#define IDC_BT_DISKINFO                 1162
#define IDC_STATIC_FILENAME             1163
#define IDS_STRING_HEAD                 1200
#define IDS_ERR_OTHERINSTANCE           1201
#define IDS_ERR_CMDLINE_INVALIDE        1202
#define IDS_WARNING_PACKAGE_DAMAGED     1203
#define IDS_FORDER_NAME                 1210
#define IDS_BRWSFLD_TITLE               1211
#define IDS_ERROR_INVALID_PATH          1212
#define IDS_PRODUCT_SHORT_NAME_BASE     1213
#define IDS_FOLDER_DOESNOT_EXIST        1214
#define IDS_ERROR_CREATE_PATH           1215
#define IDD_DLG_DRIVE_INFO              2215
#define IDC_LIST_DRIVE                  2216
#define IDS_DRIVEINFO_LIST_DRV          2217
#define IDS_DRIVEINFO_LIST_REQ          2218
#define IDS_DRIVEINFO_LIST_REM          2219
#define IDS_DRIVEINFO_SPACE_UNIT        2220
#define IDS_DRIVEINFO_TITLE             2221
#define IDS_NOT_ENOUGH_SPACE            2222
#define IDS_ERR_DVDROOTPATH_EMPTY       2223
#define IDS_ERR_INSTPATH_EMPTY          2224
#define IDS_ERR_DVDROOTPATH_NOTSETUP    2225
#define IDS_ERR_INSTPATH_SUBFLD         2226
#define IDS_ERR_INSTALL_OK              2227
#define IDS_ERR_INSTALL_FAILED          2228
#define IDS_NEXTBUTTON_FINISH           2229
#define IDS_NEXTBUTTON_RUN              2230
#define IDS_NEXTBUTTON_REPAIR           2231
#define IDD_DIALOG_BASE_MASTER          2232
#define IDS_MSG_MASTER_MODE_T3          2240
#define IDS_MSG_RUN_MODE_T3             2241
#define IDS_TITLE_RUN_MODE              2242
#define IDS_SUBTITLE_RUN_MODE           2243
#define IDS_TITLE_REPAIR_MODE           2244
#define IDS_SUBTITLE_REPAIR_MODE        2245
#define IDS_INSTALL_PREMSG              2246

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
