//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by E:\project\EPIC16.5-D2D-up7\Native\RCModules\SETUP\MSRes.dll\MasterSetup_e.rc
//
#define IDS_SETUPWIZARD                 1
#define IDS_LICENSEHEADERTITLE          2
#define IDS_LICENSEHEADERSUBTITLE       3
#define IDS_CHOICEPRODUCTHEADERTITLE    4
#define IDS_STRING_ONLY_32BITPACKAGE    5
#define IDS_COPYFILEHEADERTITLE         6
#define IDS_COPYFILEHEADERSUBTITLE      7
#define IDS_POSTCONFIGHEADERTITLE       8
#define IDS_STRING_URL                  9
#define IDS_PREREQUISITES_NAME          10
#define IDS_PREREQUISITES_STATUS        11
#define IDS_SETUP_CANCEL                12
#define IDS_INSTALL_STATUS_SUCCESS      13
#define IDS_INSTALL                     14
#define IDS_PRODUCT_UPGRADE             15
#define IDS_INSTALL_STATUS_FAILED       16
#define IDS_SECOND_INSTANCE             17
#define IDS_STRING_ONLY_64BITPACKAGE    18
#define IDS_INSTALL_STATUS_REBOOT       19
#define IDS_INSTALL_STATUS_INSTALL      20
#define IDS_PRODUCT_INSTALLED           21
#define IDS_OS_NOT_SUPPORT              22
#define IDS_FW_TOOLTIP                  23
#define IDS_INVALID_PORTNUMBER          24
#define IDS_PORTNUMBER_ISUSED           25
#define IDS_ERR_INVALID_USER            26
#define IDS_ERR_USER_NOT_IN_GROUP       27
#define IDS_ERR_UNKNOWN                 28
#define IDS_ERR_EMPTY_USERNAME          29
#define IDS_ERR_EMPTY_DOMAIN            30
#define IDS_D2D_ADDRESS                 31
#define IDS_URL_UNDERSTAND              32
#define IDS_URL_REGISTER                33
#define IDS_HELP                        34
#define IDS_HOST_STATUS_PENDING         35
#define IDS_URL_ACCESS                  36
#define IDS_DRIVEINFO_LIST_RUNTIME_REQ  38
#define IDS_PRODUCT_OUTOF_RANGE         39
#define IDS_ERR_EMPTY_PASSWORD          40
#define IDS_HTTP_PROTOCOL               41
#define IDS_HTTPS_PROTOCOL              42
#define IDS_HTTPS_WARNING               43
#define IDB_BANNER16                    104
#define IDB_WATERMARK16                 105
#define IDB_WATERMARK256                106
#define IDC_LIST_COMPONENTS             112
#define IDC_HELPBUTTON                  113
#define IDR_MAINFRAME                   128
#define IDD_SETUP_LICENSE               129
#define IDD_SETUP_POST_CONFIG           132
#define IDB_PRODUCT                     135
#define IDB_BLANK                       142
#define IDD_DLG_DRIVE_INFO              159
#define IDD_SETUP_COPYFILE_LOCAL        162
#define IDD_SETUP_CHS_PROD_WIZ          163
#define IDB_WIZ97_BANNER256             164
#define IDB_WIZ97_BANNER16              165
#define IDC_ICON_FIREWALL_TOOLTIP       166
#define IDC_RADIO_ALL_USER              167
#define IDC_RADIO_CURRENT_USER          168
#define IDC_STATIC_MONITOR_OPTION       169
#define IDC_SUMMARY_TITLE               174
#define IDD_WAIT_MESSAGE                175
#define IDI_SERVICE                     176
#define IDD_LANGUAGEDLG                 178
#define IDD_SETUP_SELECT_LIC_REG        179
#define IDC_LICKEY1                     182
#define IDC_LICKEY2                     183
#define IDC_LICKEY3                     184
#define IDC_LICKEY4                     185
#define IDC_LICKEY5                     186
#define IDB_BITMAP_STATUS               189
#define IDD_STATUS_PANEL                217
#define IDB_MESSAGE_ICONS               221
#define IDI_ICON_INFO                   222
#define IDC_STATIC_BMP_WARNING24        224
#define IDC_STATIC_MSG_LINK             225
#define IDC_ICON_DRIVER_TOOLTIP         226
#define IDI_ICON_COPY                   235
#define IDI_ICON_PRINT                  236
#define IDI_ICON_BROWSE                 237
#define IDI_ICON_DISKINFO               238
#define IDC_LICENSE_DESCRIPTION         1000
#define IDC_EDIT_DESCRIPTION            1000
#define IDC_TREE_PRODUCTS               1003
#define IDC_BUTTON_CHANGE_FOLDER        1005
#define IDC_BUTTON_CHANGE_OPTION        1006
#define IDC_PROGRESS_PRODUCT            1009
#define IDC_PROGRESS_FILES              1010
#define IDC_PIC_COPY_FILES              1010
#define IDC_PROGRESS_COPY_FILES         1014
#define IDC_PORD_NAME                   1018
#define IDC_DESCRITPTION                1019
#define IDC_TREE                        1020
#define IDC_TREE_POSTCONFIG             1021
#define IDC_STATIC_WARNING              1023
#define IDC_HTTPS_WARNING               1024
#define IDC_PROD_DESCRIPTION            1027
#define IDC_PIC_PROGRESS_ALL            1029
#define IDC_PROGRESS_ALL                1030
#define IDC_LIST_DRIVE                  1031
#define IDC_COMPUTER_NAME               1034
#define IDC_MESSAGE                     1046
#define IDC_PHASE                       1048
#define IDC_RADIO_AGREE                 1049
#define IDC_DRIVE                       1055
#define IDC_REQUESTED_DISK              1056
#define IDC_FREE_DISK                   1057
#define IDC_EDT_REQ_DISK                1058
#define IDC_EDT_REM_DISK                1059
#define IDC_BUTTON_DISK_INFO            1060
#define IDC_EDIT_INST_FOLDER            1061
#define IDC_PROD_NEED_SPACE             1070
#define IDC_WAIT_MESSAGE                1075
#define IDC_STATIC_LOCAL_DESC           1076
#define IDC_STATIC_CRT_DESC             1078
#define IDC_LAN_COMBO                   1080
#define IDC_LAN_TEXT_STATIC             1081
#define IDI_SETUP                       1082
#define IDC_ICON_STATIC                 1083
#define IDC_SETUP_LICENSE_MSG           1084
#define IDC_LICENSE_IMPORTANCE1         1085
#define IDC_LICENSE_IMPORTANCE2         1086
#define IDS_LIC_CHK_FAILED              1089
#define IDC_INSTALLINFO_IMPORTANCE2     1089
#define IDS_NOT_ENOUGH_SPACE_SYSTEM     1091
#define IDC_RADIO_KEY                   1093
#define IDC_RADIO_ALP                   1094
#define IDC_RADIO_TRIAL                 1095
#define IDC_TRIALKEY                    1096
#define IDS_TIMEOUT                     1097
#define IDC_STATIC_LICENSEKEY           1098
#define IDC_RADIO_PRIMARY_GUI_DLG       1098
#define IDC_STATIC_USERNAME             1120
#define IDC_STATIC_PASSWORD             1121
#define IDC_STATIC_PORT                 1122
#define IDC_STATIC_COPY                 1137
#define IDC_STATIC_PRINT                1138
#define IDC_STATIC_WEBSITE              1145
#define IDC_STATIC_README               1146
#define IDC_TREE_STATUS                 1151
#define IDC_RADIO_DISAGREE              1170
#define IDC_STATIC_COMPONENTS           1175
#define IDC_EDIT_PROT                   1177
#define IDC_STATIC_URL                  1178
#define IDC_HTTPS_WARN_ICON             1179
#define IDC_CHECK_CONFIGURE_FIREWALL    1180
#define IDC_CHECKBOX_HTTPS              1181
#define IDC_STATIC_WARN                 1182
#define IDC_STATIC_TOOPTIP              1183
#define IDC_PACKAGE_WARNING             1184
#define IDC_EDIT_USERNAME               1185
#define IDC_EDIT_PASSWORD               1186
#define IDC_PROGRESS_UPDATE             1187
#define IDC_STATIC_UPDATE_MSG           1188
#define IDC_D2DURL                      1189
#define IDC_STATIC_UNDERSTAND           1191
#define IDC_STATIC_REGISTER             1192
#define IDC_STATIC_ACCESS               1193
#define IDC_CHECK1                      1194
#define IDC_CHECK_DRIVER_OPTION         1194
#define IDC_EDIT1                       1195
#define IDC_EDIT_FIREWALL_COMMAND       1195
#define IDS_COPY                        13001
#define IDS_PRINT                       13002
#define IDS_MONITOR_OPTION              13005
#define IDS_TIP_BROWSE                  13006
#define IDS_TIP_DISKINFO                13007
#define IDS_LICENSE_IMPORTANCE2         13400
#define IDS_ERROR_SERVICE               13401
#define IDS_ERROR_DRIVER_CHANGETRACKING 13402
#define IDS_ERROR_DRIVER_KMDF           13403
#define IDS_ERROR_DRIVER_UMDF           13404
#define IDS_BTN_YES                     13500
#define IDS_BTN_NO                      13501
#define IDS_BTN_OK                      13502
#define IDS_BTN_CANCEL                  13503
#define IDS_BTN_CLOSE                   13504
#define IDS_RESTART_SYSTEM              13505
#define IDS_SETUPWIZARD_TITLE           13506
#define IDS_PLATFORM_NOT_SUPPORT        50000
#define IDS_PROD_CAN_BE_UPDATED         50001
#define IDS_PROD_CAN_NOT_UPDATED        50002
#define IDS_NOT_ENOUGH_SPACE            50003
#define IDS_LOAD_DLL_FAILED             50004
#define IDS_CALL_FUNC_FAILED            50005
#define IDS_HTTPS_MSG                   50006
#define IDS_PST_CFG_NEED_CONFIG         51250
#define IDS_PST_CFG_DOING_CONFIG        51251
#define IDS_PST_CFG_CONFIG_COMPLETE     51252
#define IDS_PST_CFG_CONFIG_FAILED       51254
#define IDS_SELECT_SERVER_BAD_RIGHTS    51305
#define IDS_SELECT_SERVER_LGN_FAIL      51306
#define IDS_SELECT_SERVER_LGN_CRED_CONFLICT 51307
#define IDS_LAUNCH_DEL_SRVC_FAIL        51413
#define IDS_INITIALIZE                  51450
#define IDS_COPYING_FILES               51451
#define IDS_INSTALLING_SRV              51452
#define IDS_INSTCOMPLETED               51453
#define IDS_INPROGRESS                  51454
#define IDS_ERROR_COPYFILES             51455
#define IDS_ERROR_NO_SPACE              51456
#define IDS_ALREADY_RUNNING             51457
#define IDS_STARTSRV_FAILED             51458
#define IDS_REMOVING_SRV                51459
#define IDS_CREATING_REGISTRY           51460
#define IDS_CREATING_ICANDFLD           51461
#define IDS_LOAD_SETUP_FAILED           51462
#define IDS_ARCSERVE_NOT_FOUND          51463
#define IDS_REQUIRE_CHANGER             51464
#define IDS_ERROR_REGISTRY              51465
#define IDS_ERROR_CREATESRV             51466
#define IDS_SNABASE_NOT_FOUND           51467
#define IDS_INIFILE_NOT_FOUND           51468
#define IDS_SERVICE_ALREADY_RUNNING     51469
#define IDS_IMPROPER_EDITION            51470
#define IDS_OPTION_NOTAVAILABLE         51471
#define IDS_RELATED_PROCESS_RUNNING     51472
#define IDS_MVS_JOB_RUNNING             51473
#define IDS_WINVERSION_ERR              51474
#define IDS_INSTNOTCOMPLETED            51475
#define IDS_INSTWINDOWSMSI              51476
#define IDS_UPDATEIE5                   51477
#define IDS_UPDATESYSLIB                51478
#define IDS_REBOOT                      51479
#define IDS_REBOOT_REINSTALL            51480
#define IDS_CONFIG_PRODUCT              51481
#define IDS_UPDATE_PRODUCT              51482
#define IDS_SEND_LOG_FILENAME           51483
#define IDS_ERROR_INSTSP                51484
#define IDS_IN_PROGRESS                 51500
#define IDS_INST_COMPLETED              51501
#define IDS_INST_FAILED                 51502
#define IDS_INST_NOT_STARTED            51503
#define IDS_INST_3RD_SP                 51504
#define IDS_COPY_IMG                    51505
#define IDS_SELECTLICREG_TITLE          51610
#define IDS_DRIVEINFO_LIST_DRV          51700
#define IDS_DRIVEINFO_LIST_REQ          51701
#define IDS_DRIVEINFO_LIST_REM          51702
#define IDS_DRIVEINFO_SPACE_UNIT        51703
#define IDS_CHOOSEPROD_DRV              51750
#define IDS_NEED_REBOOT                 51751
#define IDS_ADMIN_ERROR                 51753
#define IDS_INST_FAILED_H               51754
#define IDS_INST_WAITING                51756
#define IDS_CREATE_DIR_FAILED           51761
#define IDS_CHS_PROD_NEED_SPACE         51768
#define IDS_INFOR_NEED_REBOOT           51772
#define IDS_REBOOT_TO_INSTALL           51775
#define IDS_SINST_COPYRIGHT             51777
#define IDS_SINST_USAGE0                51779
#define IDS_SINST_USAGE1                51780
#define IDS_SINST_USAGE2                51781
#define IDS_SINST_USAGE3                51782
#define IDS_SINST_USAGE4                51783
#define IDS_SINST_USAGE5                51784
#define IDS_SINST_USAGE6                51785
#define IDS_SINST_START                 51786
#define IDS_SINST_PRS                   51787
#define IDS_SINST_IRCS                  51788
#define IDS_SINST_US                    51789
#define IDS_SINST_INSTP                 51790
#define IDS_SINST_SUMMARY               51791
#define IDS_SINST_CHARSTR               51792
#define IDS_SINST_HOSTNAME              51793
#define IDS_SINST_USERNAME              51794
#define IDS_SINST_COMPLETED             51796
#define IDS_SINST_FAILED                51797
#define IDS_SINST_LOGFILE               51798
#define IDS_SINST_RLOGIN                51800
#define IDS_SINST_RWARN                 51801
#define IDS_SINST_RERROR_SRV0           51802
#define IDS_SINST_RERROR_SRV1           51803
#define IDS_SINST_COPY_IMG              51804
#define IDS_SINST_ERR_NO_PROD           51805
#define IDS_REBOOT_RMT_MACHINE          51807
#define IDS_BRWSFLD_TITLE               51812
#define IDS_INSTALL_HEADER              51814
#define IDS_SINST_INST_END              51815
#define IDS_SINST_WILL_NOT_INSTED       51818
#define IDS_INST_CA_LICENSE             51819
#define IDS_CA_LICENSE_FAILED           51820
#define IDS_INSTALL_SUMMARY_TITLE       51822
#define IDS_NOT_FND_RMT_SRV             51823
#define IDS_FAILED_LOAD_INSTALL_LOG     51824
#define IDS_SINST_INVALID_USR           51825
#define IDS_SINST_NOT_FND_ICFFILE       51826
#define IDS_SINST_NOT_ICFFILE           51827
#define IDS_ERROR_TEMP_PATH             52001
#define IDS_ERROR_CRT_FLD               52002
#define IDS_LOG_TITLE                   52003
#define IDS_WARNING_UPG_ACTIVEJOB       52004
#define IDS_ERR_FIND_FILE               52007
#define IDS_LOG_PARAMETER               52015
#define IDS_LOG_REQUIRED_SPACE          52021
#define IDS_LOG_CALL_RPC0               52022
#define IDS_ERR_FIND_FIRST_HD           52023
#define IDS_LOG_FIND_FIRST_HD           52024
#define IDS_LOG_LAUNCH_SETUP            52025
#define IDS_ERR_COPYFILE                52026
#define IDS_LOG_COPY_IMG                52027
#define IDS_ERR_LOGIN                   52028
#define IDS_LOG_START_SRV               52029
#define IDS_LOG_RMT_SETUP               52030
#define IDS_LOG_CRT_ANS_FILE            52031
#define IDS_LOG_LAUNCH_PROCESS          52033
#define IDS_ERR_LAUNCH_PROCESS          52034
#define IDS_LOG_CALL_FUNC               52035
#define IDS_LOG_LOAD_DLL                52036
#define IDS_ERR_LOAD_DLL                52037
#define IDS_LOG_RETURN_CODE             52038
#define IDS_LOG_PRE_INST                52039
#define IDS_LOG_LAUNCH_THREAD           52040
#define IDS_ERR_LAUNCH_THREAD           52041
#define IDS_ERR_NO_SPACE                52048
#define IDS_COLLECT_INFO                52049
#define IDS_WIZBACK                     52050
#define IDS_WIZNEXT                     52051
#define IDS_WIZCANCEL                   52052
#define IDS_WIZFINISH                   52053
#define IDS_WAIT_MSG_CFG                52054
#define IDS_FOLDER_DOESNOT_EXIST        52055
#define IDS_INVALID_PATH                52056
#define IDS_ERROR_CREATE_PATH           52057
#define IDS_FORDER_NAME                 52058
#define IDS_COMPONENT                   52062
#define IDS_SINST_USAGE_DISPLAY         52064
#define IDS_KEY_ERROR                   52072
#define IDS_KEY_ERROR_TITLE             52077
#define IDS_INSTALLING_EXTERNAL         52091
#define IDS_VALID_REGSERVICE            52096
#define IDS_REBOOT_WARNING_MSG          52150
#define IDS_REMOTE_REBOOT_WARNING_MSG   52151
#define IDS_SINST_USAGE8                52162
#define IDS_SINST_USAGE9                52163
#define IDS_COMPONENT_INSTALING         52527
#define IDS_COMPONENT_FAILED            52528
#define IDS_INVALID_PATH_LENGTH         52529
#define IDS_WARNING_UPG_PROCESSBLOCK    52530
#define IDS_DRIVE_MSG                   52531
#define IDS_SERVICE_UA_RUNNING          52532
#define IDS_SERVICE_UA_STOP_WARNNING    52533
#define IDS_SERVICE_UA_STOP_QUESTION    52534
#define IDS_SERVICE_UA_CANNOTSTOP       52535
#define IDS_SERVICE_HBA_STOPWARNING     52536
#define IDS_SERVICE_HBA_CANNOTSTOP      52537
#define IDS_ITEM_OEM                    52538
#define IDS_MSG_OEM_FAILED              52539
#define IDS_TOOLTIP_TITLE               52540
#define IDS_WEBSERVER_REMOVAL_REBOOT    52541
#define IDD_UPGRADEMSG_DIALOG           52542
#define IDC_STATIC_UPGRADEMSG_WEBLINK   52543

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        226
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
