#pragma once

//command:
//SessionLauncher.exe  /i:ICFFILE
#define		SESSION_LAUNCHER_FLAG_CONFIGFILE			_T("/i:")

//SessionLauncher input file format
#define		SESSION_LAUNCHER_SECTION					_T("INSTALL")
#define		SESSION_LAUNCHER_VALUE_SESSION_ID			_T("SESSION")
#define		SESSION_LAUNCHER_VALUE_CREATEFLAG			_T("FLAG")
#define		SESSION_LAUNCHER_VALUE_WORKDIR				_T("WORKDIR")
#define		SESSION_LAUNCHER_VALUE_COMMAND				_T("COMMAND")
#define		SESSION_LAUNCHER_VALUE_LOGFOLDER			_T("LOGFOLDER")
#define		SESSION_LAUNCHER_VALUE_WAITTIME				_T("WAITTIME")
#define		SESSION_LAUNCHER_VALUE_RETVALUE				_T("RETTURNVALUE")
