/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ca_ha_webservice_jni_VMWareJNI */

#ifndef _Included_com_ca_ha_webservice_jni_VMWareJNI
#define _Included_com_ca_ha_webservice_jni_VMWareJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ca_ha_webservice_jni_VMWareJNI
 * Method:    ConvertVHD2VMDK
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_ConvertVHD2VMDK
(JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint, jobject, jint, jstring, jstring, jlong, jint, jstring, jstring, jobject);

/*
* Class:     com_ca_ha_webservice_jni_VMWareJNI
* Method:    D2D2VmdkSmartCopy
* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)J
*/
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_D2D2VmdkSmartCopy
(JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint, jobject, jint, jstring, jstring, jlong, jint, jstring, jstring, jobject);


/*
 * Class:     com_ca_ha_webservice_jni_VMWareJNI
 * Method:    GetVMDKSignature
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_GetVMDKSignature
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint,jobject,jstring, jstring, jstring);


/*
* Class:     com_ca_ha_webservice_jni_VMWareJNI
* Method:    SetVMDKGeometry
* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
*/
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_SetVMDKGeometry
(JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint,jobject, jstring, jlong, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_VMWareJNI
 * Method:    DoVMWareDriverInjection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_DoVMWareDriverInjection
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jobject, jobject,jobject, jstring, jstring, jstring, jstring, jstring, jstring, jboolean, jstring);


/*
* Class:     com_ca_ha_webservice_jni_VMWareJNI
* Method:    DriverInjectSingleVMDK
* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
*/
//modified by zhepa02 at 2015-04-14 ,add the strThumbprint jstring.
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_DriverInjectSingleVMDK
(JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint,jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_VMWareJNI
 * Method:    GetGuestID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_GetGuestID
  (JNIEnv *, jclass);

/*
 * Class:     com_ca_ha_webservice_jni_VMWareJNI
 * Method:    InstallVMwareTools
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_InstallVMwareTools
  (JNIEnv *, jclass);

/*
 * Class:     com_ca_ha_webservice_jni_VMWareJNI
 * Method:    VDDKInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_VDDKInit
  (JNIEnv *, jclass);

/*
 * Class:     com_ca_ha_webservice_jni_VMWareJNI
 * Method:    VDDKExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_VDDKExit
  (JNIEnv *, jclass);

/*
* Class:     com_ca_ha_webservice_jni_VMWareJNI
* Method:    GetVDDKVersion
* Signature: (Lcom/ca/arcflash/ha/model/FileVersion;)I
*/
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_GetVDDKVersion
(JNIEnv *, jclass, jobject);

/*
* Class:     com_ca_ha_webservice_jni_VMWareJNI
* Method:    UpdateDiskSigViaNBD
* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)J
*/
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_UpdateDiskSigViaNBD
(JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint, jobject, jint, jstring, jstring, jint, jstring, jstring);


JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_HALockD2DSessions
(JNIEnv *env, jclass cls, jstring sessionRoot, jint sessionBegin, jint sessionEnd, jboolean isForRemoteVCM, jobject resultCodeList);

JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_HAUnlockD2DSessions
(JNIEnv *env, jclass cls, jlong lockHandle);

JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_HAUnlockCTF2
(JNIEnv *env, jclass cls, jlong lockHandle);

/*
 * Class:     com_ca_arcflash_webservice_jni_WSJNI
 * Method:    DoRVCMInjectService
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/util/List;)J
 */
//modified by zhepa02 at 2015-04-14 ,add the strThumbprint jstring.
JNIEXPORT jlong JNICALL Java_com_ca_arcflash_webservice_jni_WSJNI_DoRVCMInjectService
  (JNIEnv *, jclass, jstring, jint, jobject, jstring, jstring, jstring, jobject, jstring, jobject, jstring, jstring, jobject, jboolean, jstring);

/*
 * Class:     com_ca_arcflash_webservice_jni_WSJNI
 * Method:    GetVDDKRegistryKey
 * Signature: (Ljava/lang/String;)J
 */

JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_VMWareJNI_GetVDDKRegistryKey(JNIEnv *env,jclass, jstring keyName);

#ifdef __cplusplus
}
#endif
#endif
