/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ca_ha_webservice_jni_HyperVJNI */

#ifndef _Included_com_ca_ha_webservice_jni_HyperVJNI
#define _Included_com_ca_ha_webservice_jni_HyperVJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ca_ha_webservice_jni_HyperVJNI_VM_STATE_UNKNOWN
#define com_ca_ha_webservice_jni_HyperVJNI_VM_STATE_UNKNOWN 0L
#undef com_ca_ha_webservice_jni_HyperVJNI_VM_STATE_RUNNING
#define com_ca_ha_webservice_jni_HyperVJNI_VM_STATE_RUNNING 2L
#undef com_ca_ha_webservice_jni_HyperVJNI_VM_STATE_TURNED_OFF
#define com_ca_ha_webservice_jni_HyperVJNI_VM_STATE_TURNED_OFF 3L
#undef com_ca_ha_webservice_jni_HyperVJNI_SCSI_CONTROLLER_MAX
#define com_ca_ha_webservice_jni_HyperVJNI_SCSI_CONTROLLER_MAX 4L
#undef com_ca_ha_webservice_jni_HyperVJNI_SCSI_POSITION_MAX
#define com_ca_ha_webservice_jni_HyperVJNI_SCSI_POSITION_MAX 64L
#undef com_ca_ha_webservice_jni_HyperVJNI_IDE_CONTROLLER_MAX
#define com_ca_ha_webservice_jni_HyperVJNI_IDE_CONTROLLER_MAX 2L
#undef com_ca_ha_webservice_jni_HyperVJNI_IDE_POSITION_MAX
#define com_ca_ha_webservice_jni_HyperVJNI_IDE_POSITION_MAX 2L
#undef com_ca_ha_webservice_jni_HyperVJNI_HYPERV_JNI_MERGE_OLDEST_SNAPSHOT
#define com_ca_ha_webservice_jni_HyperVJNI_HYPERV_JNI_MERGE_OLDEST_SNAPSHOT 1L
#undef com_ca_ha_webservice_jni_HyperVJNI_HYPERV_JNI_MERGE_SPECIFIED_SNAPSHOT
#define com_ca_ha_webservice_jni_HyperVJNI_HYPERV_JNI_MERGE_SPECIFIED_SNAPSHOT 2L
#undef com_ca_ha_webservice_jni_HyperVJNI_HYPERV_JNI_MERGE_MULTIPLE_SNAPSHOTS
#define com_ca_ha_webservice_jni_HyperVJNI_HYPERV_JNI_MERGE_MULTIPLE_SNAPSHOTS 3L
/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    OpenHypervHandle
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_OpenHypervHandle
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    CloseHypervHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_CloseHypervHandle
  (JNIEnv *, jclass, jlong);


/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    CreateVM
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_CreateVM
  (JNIEnv *, jclass, jlong, jstring, jstring, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    DestroyVM
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_DestroyVM
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    PowerOnVM
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_PowerOnVM
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    ShutdownVM
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_ShutdownVM
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetVMMemorySize
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetVMMemorySize
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetVMLogicalProcessorNum
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetVMLogicalProcessorNum
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    ModifyAttachedIdeHardDisk
 * Signature: (JLjava/lang/String;Ljava/lang/String;ZII)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_ModifyAttachedIdeHardDisk
  (JNIEnv *, jclass, jlong, jstring, jstring, jboolean, jint, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    ModifyAttachedScsiHardDisk
 * Signature: (JLjava/lang/String;Ljava/lang/String;ZLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_ModifyAttachedScsiHardDisk
  (JNIEnv *, jclass, jlong, jstring, jstring, jboolean, jstring, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AttachDVDDiskToVMIde
 * Signature: (JLjava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AttachDVDDiskToVMIde
  (JNIEnv *, jclass, jlong, jstring, jstring, jint, jint, jboolean);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AttachDVDDiskToVMSCSI
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AttachDVDDiskToVMSCSI
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jint, jboolean);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    TakeVmSnapshot
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_TakeVmSnapshot
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    MountVHD
 * Signature: (JLjava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_MountVHD
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    UnmountVHD
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_UnmountVHD
  (JNIEnv *, jclass, jlong, jstring);

/*
* Class:     com_ca_ha_webservice_jni_HyperVJNI
* Method:    OpenHypervMountHandle
* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
*/
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_OpenHypervMountHandle
(JNIEnv *, jclass, jstring, jstring, jstring);

/*
* Class:     com_ca_ha_webservice_jni_HyperVJNI
* Method:    MountVHDEx
* Signature: (JLjava/lang/String;J)Ljava/lang/String;
*/
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_MountVHDEx
(JNIEnv *, jclass, jlong, jobject);

/*
* Class:     com_ca_ha_webservice_jni_HyperVJNI
* Method:    UnmountVHDEx
* Signature: (JLjava/lang/String;)V
*/
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_UnmountVHDEx
(JNIEnv *, jclass, jlong);

/*
* Class:     com_ca_ha_webservice_jni_HyperVJNI
* Method:    CloseHypervMountHandle
* Signature: (J)V
*/
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_CloseHypervMountHandle
(JNIEnv *, jclass, jlong);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    InjectIDEDriver
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_InjectIDEDriver
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    InjectBCDFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_InjectBCDFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    EnableVirtualPlatformServices
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_EnableVirtualPlatformServices
  (JNIEnv *, jclass, jstring, jint, jboolean);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    ChangeProductionHostName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_ChangeProductionHostName
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    PrepareD2DForFailover
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_PrepareD2DForFailover
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AdjustVirtualCDDriveLetter
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AdjustVirtualCDDriveLetter
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetD2DSrvStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetD2DSrvStart
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    DisableShutDownEventTracker
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_DisableShutDownEventTracker
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AddPrivateNetwork
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AddPrivateNetwork
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AddInternalNetwork
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AddInternalNetwork
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AddExternalNetwork
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AddExternalNetwork
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AddLegacyNetworkAdapterToVm
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AddLegacyNetworkAdapterToVm
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AddNetworkAdapterToVm
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AddNetworkAdapterToVm
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    EnableHostDHCP
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_EnableHostDHCP
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    InstallIntegrationService
 * Signature: (ZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_InstallIntegrationService
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    DestroyVm
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_DestroyVm
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetVmBootOrder
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetVmBootOrder
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetVmStartupAction
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetVmStartupAction
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    ChangeVmFriendlyName
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_ChangeVmFriendlyName
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AttachIdeHardDiskToVm
 * Signature: (JLjava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AttachIdeHardDiskToVm
  (JNIEnv *, jclass, jlong, jstring, jstring, jint, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    DeleteVmLastSnapshot
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_DeleteVmLastSnapshot
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    DeleteVmSnapshot
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_DeleteVmSnapshot
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
* Class:     com_ca_ha_webservice_jni_HyperVJNI
* Method:    DeleteVmSnapshotAsync
* Signature: (JLjava/lang/String;Ljava/lang/String;)V
*/
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_DeleteVmSnapshotAsync
(JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    BeginDeleteSnapshot
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_BeginDeleteSnapshot
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    EndDeleteSnapshot
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_EndDeleteSnapshot
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    RevertToLastVmSnapshot
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_RevertToLastVmSnapshot
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    RevertToVmSnapshot
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_RevertToVmSnapshot
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    CreateChildVHD
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_CreateChildVHD
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    CreateIsoImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_CreateIsoImage
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    EnableHostStatic
 * Signature: (Ljava/lang/String;Ljava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_EnableHostStatic
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    EnableHostDNS
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_EnableHostDNS
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetHostDNSDomain
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetHostDNSDomain
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetHostDNSServerSearchOrder
 * Signature: (Ljava/lang/String;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetHostDNSServerSearchOrder
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetHostDNSSuffixSearchOrder
 * Signature: (Ljava/lang/String;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetHostDNSSuffixSearchOrder
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetHostDynamicDNSRegistration
 * Signature: (Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetHostDynamicDNSRegistration
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetHostGateways
 * Signature: (Ljava/lang/String;Ljava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetHostGateways
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    SetHostWINSServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_SetHostWINSServer
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetSystemDiskSignature
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetSystemDiskSignature
  (JNIEnv *, jclass);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetFreePhysicalNetworkAdapter
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetFreePhysicalNetworkAdapter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetVmSnapshots
 * Signature: (JLjava/lang/String;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetVmSnapshots
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetHostAdapterList
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetHostAdapterList
  (JNIEnv *, jclass);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetVmList
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetVmList
  (JNIEnv *, jclass, jlong);

/*
* Class:     com_ca_ha_webservice_jni_HyperVJNI
* Method:    GetVmNotes
* Signature: (JLjava/lang/String;)I
*/
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetVmNotes
(JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetVmState
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetVmState
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetVirutalNetworkList
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetVirutalNetworkList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetAttachedDiskImage
 * Signature: (JLjava/lang/String;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetAttachedDiskImage
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetSnapshotVhds
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetSnapshotVhds
  (JNIEnv *, jclass, jlong, jstring, jstring, jobject);


JNIEXPORT jboolean JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_IsVMOperatingNormally
  (JNIEnv *env, jclass klass, jlong handle, jstring vmGuid); //<huvfe01>2012-12-7 #VM operational status


/*
* Class:     com_ca_ha_webservice_jni_HyperVJNI
* Method:    IsVmInStorageOperationalStatus
* Signature: (JLjava/lang/String;)Z
*/
JNIEXPORT jboolean JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_IsVmInStorageOperationalStatus
(JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    ListScsiControls
 * Signature: (JLjava/lang/String;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_ListScsiControls
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    AddScsiControl
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_AddScsiControl
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    isDifferencingDisk
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_isDifferencingDisk
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    modifyParentAbsolutePath
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_modifyParentAbsolutePath
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    getParentAbsolutePath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_getParentAbsolutePath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    startTransServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_startTransServer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    stopTransServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_stopTransServer
  (JNIEnv *, jclass);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetMaxCPUSForHypervVm
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetMaxCPUSForHypervVm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetMaxRAMForHypervVm
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetMaxRAMForHypervVm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetHyperVSystemInfo
 * Signature: (JLcom/ca/ha/webservice/jni/JHyperVSystemInfo)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetHyperVSystemInfo
  (JNIEnv *, jclass, jlong, jobject);


/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    DetachAllDisks
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_DetachAllDisks
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    DetachIdeDisk
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_DetachIdeDisk
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    MergeHyperVSnapshots
 * Signature: (JLjava/lang/String;ILjava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_MergeHyperVSnapshots
  (JNIEnv *, jclass, jlong, jstring, jint, jobject);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetLastSnapshot
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetLastSnapshot
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    GetLastErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_GetLastErrorMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    MountVHDGetWinSysBootVol
 * Signature: (JLjava/lang/String;Ljava/util/List;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_MountVHDGetWinSysBootVol
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    getVHDDirForSpecificSnapshot
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_getVHDDirForSpecificSnapshot
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    RemoveAllVMNetworks
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_RemoveAllVMNetworks
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ca_ha_webservice_jni_HyperVJNI
 * Method:    getHyperVDestInfo
 * Signature: (Ljava/util/List;Lcom/ca/arcflash/webservice/data/HyperVDestinationInfo;)V
 */
JNIEXPORT void JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_getHyperVDestInfo
  (JNIEnv *, jclass, jobject, jobject);

/*
* Class:     com_ca_arcflash_webservice_jni_HyperVJNI
* Method:    checkHyperVVMToolVersion
* Signature: (I)Ljava/lang/String();
*/
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_checkHyperVVMToolVersion
(JNIEnv *, jclass, jlong, jstring);

/*
* Class:     com_ca_arcflash_webservice_jni_HyperVJNI
* Method:    getHyperVIPAddresses
* Signature: (I)Ljava/lang/String;
*/
JNIEXPORT jlong JNICALL Java_com_ca_ha_webservice_jni_HyperVJNI_getHyperVIPAddresses
(JNIEnv *, jclass, jlong, jstring, jobject);

// TODO: consider to move DoRVCMInjectServiceForHyperV to com_ca_arcflash_webservice_jni_WSJNI.h since it doesn't belong to ARCserve\D2D\Server\VCM\AFJob\src\com\ca\ha\webservice\jni\HyperVJNI.java
/*
 * Class:     com_ca_arcflash_webservice_jni_WSJNI
 * Method:    DoRVCMInjectServiceForHyperV
 * Signature: (Ljava/lang/String;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_com_ca_arcflash_webservice_jni_WSJNI_DoRVCMInjectServiceForHyperV
  (JNIEnv *, jclass, jstring, jstring, jobject, jboolean, jstring);



#ifdef __cplusplus
}
#endif
#endif
