
package com.ca.arcserve.edge.app.base.webservice.sync.arcserve.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SyncServiceImpl", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Documents%20and%20Settings/wanwe13/Local%20Settings/Temp/tempdir9170772737626550324.tmp/metadata_1.wsdl")
public class SyncServiceImpl
    extends Service
{

    private final static URL SYNCSERVICEIMPL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ca.arcserve.edge.app.base.webservice.sync.arcserve.client.SyncServiceImpl.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ca.arcserve.edge.app.base.webservice.sync.arcserve.client.SyncServiceImpl.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Documents%20and%20Settings/wanwe13/Local%20Settings/Temp/tempdir9170772737626550324.tmp/metadata_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Documents%20and%20Settings/wanwe13/Local%20Settings/Temp/tempdir9170772737626550324.tmp/metadata_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SYNCSERVICEIMPL_WSDL_LOCATION = url;
    }

    public SyncServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncServiceImpl() {
        super(SYNCSERVICEIMPL_WSDL_LOCATION, new QName("http://tempuri.org/", "SyncServiceImpl"));
    }

    /**
     * 
     * @return
     *     returns ISyncService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISyncService")
    public ISyncService getBasicHttpBindingISyncService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISyncService"), ISyncService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISyncService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISyncService")
    public ISyncService getBasicHttpBindingISyncService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISyncService"), ISyncService.class, features);
    }

}
