#pragma once

#define WM_APM_STATUS_CHANGED (WM_USER + 100)

#define APM_STATUS_BEGIN					0
#define APM_STATUS_DOWNLOAD_FINISHED		1
#define APM_STATUS_INSTALL_FINISHED			2
#define APM_STATUS_ERROR					3
#define APM_STATUS_PROCESS_PERCENT			4
#define APM_STATUS_BACKEND_MESSAGE			5

#define FILE_APM_RESOURCE_DLL				L"APMSetupUtilityRes.dll"