//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.24 at 11:02:26 AM GMT+08:00 
//


package com.ca.arcserve.edge.app.base.webservice.srm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ca.arcserve.edge.app.base.srm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HardwareInformationFiberCardDriverVersion_QNAME = new QName("AgentInfoProbe", "DriverVersion");
    private final static QName _HardwareInformationCPUNumberOfCores_QNAME = new QName("AgentInfoProbe", "NumberOfCores");
    private final static QName _HardwareInformationOSOtherTypeDescription_QNAME = new QName("AgentInfoProbe", "OtherTypeDescription");

	private final static QName _SoftwareInformationInstalledProgramEdition_QNAME = new QName("AgentInfoProbe", "Edition");
    private final static QName _SoftwareInformationInstalledProgramInstallDate_QNAME = new QName("AgentInfoProbe", "InstallDate");
    private final static QName _SoftwareInformationAppDataInfoInstanceName_QNAME = new QName("AgentInfoProbe", "InstanceName");
	/**
	 *   For hardware information
	 */
	
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ca.arcserve.edge.app.base.srm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HardwareInformation.DiskDrive }
     * 
     */
    public HardwareInformation.DiskDrive createHardwareInformationDiskDrive() {
        return new HardwareInformation.DiskDrive();
    }

    /**
     * Create an instance of {@link HardwareInformation.LogicalDisk }
     * 
     */
    public HardwareInformation.LogicalDisk createHardwareInformationLogicalDisk() {
        return new HardwareInformation.LogicalDisk();
    }

    /**
     * Create an instance of {@link HardwareInformation.NIC }
     * 
     */
    public HardwareInformation.NIC createHardwareInformationNIC() {
        return new HardwareInformation.NIC();
    }

    /**
     * Create an instance of {@link HardwareInformation.Volume }
     * 
     */
    public HardwareInformation.Volume createHardwareInformationVolume() {
        return new HardwareInformation.Volume();
    }

    /**
     * Create an instance of {@link HardwareInformation.Volume.DiskInfo.Disk }
     * 
     */
    public HardwareInformation.Volume.DiskInfo.Disk createHardwareInformationVolumeDiskInfoDisk() {
        return new HardwareInformation.Volume.DiskInfo.Disk();
    }

    /**
     * Create an instance of {@link HardwareInformation.OS }
     * 
     */
    public HardwareInformation.OS createHardwareInformationOS() {
        return new HardwareInformation.OS();
    }

    /**
     * Create an instance of {@link HardwareInformation.DiskPartition.LogicalDiskName }
     * 
     */
    public HardwareInformation.DiskPartition.LogicalDiskName createHardwareInformationDiskPartitionLogicalDiskName() {
        return new HardwareInformation.DiskPartition.LogicalDiskName();
    }

    /**
     * Create an instance of {@link HardwareInformation.Volume.DiskInfo }
     * 
     */
    public HardwareInformation.Volume.DiskInfo createHardwareInformationVolumeDiskInfo() {
        return new HardwareInformation.Volume.DiskInfo();
    }

    /**
     * Create an instance of {@link HardwareInformation.DiskPartition }
     * 
     */
    public HardwareInformation.DiskPartition createHardwareInformationDiskPartition() {
        return new HardwareInformation.DiskPartition();
    }

    /**
     * Create an instance of {@link HardwareInformation.Volume.Fragment }
     * 
     */
    public HardwareInformation.Volume.Fragment createHardwareInformationVolumeFragment() {
        return new HardwareInformation.Volume.Fragment();
    }

    /**
     * Create an instance of {@link HardwareInformation }
     * 
     */
    public HardwareInformation createHardwareInformation() {
        return new HardwareInformation();
    }

    /**
     * Create an instance of {@link HardwareInformation.FiberCard }
     * 
     */
    public HardwareInformation.FiberCard createHardwareInformationFiberCard() {
        return new HardwareInformation.FiberCard();
    }

    /**
     * Create an instance of {@link HardwareInformation.NIC.IPList.IPAddress }
     * 
     */
    public HardwareInformation.NIC.IPList.IPAddress createHardwareInformationNICIPListIPAddress() {
        return new HardwareInformation.NIC.IPList.IPAddress();
    }

    /**
     * Create an instance of {@link HardwareInformation.CPU }
     * 
     */
    public HardwareInformation.CPU createHardwareInformationCPU() {
        return new HardwareInformation.CPU();
    }

    /**
     * Create an instance of {@link HardwareInformation.NIC.IPList }
     * 
     */
    public HardwareInformation.NIC.IPList createHardwareInformationNICIPList() {
        return new HardwareInformation.NIC.IPList();
    }

    /**
     * Create an instance of {@link HardwareInformation.Memory }
     * 
     */
    public HardwareInformation.Memory createHardwareInformationMemory() {
        return new HardwareInformation.Memory();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AgentInfoProbe", name = "DriverVersion", scope = HardwareInformation.FiberCard.class)
    public JAXBElement<String> createHardwareInformationFiberCardDriverVersion(String value) {
        return new JAXBElement<String>(_HardwareInformationFiberCardDriverVersion_QNAME, String.class, HardwareInformation.FiberCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AgentInfoProbe", name = "NumberOfCores", scope = HardwareInformation.CPU.class)
    public JAXBElement<String> createHardwareInformationCPUNumberOfCores(String value) {
        return new JAXBElement<String>(_HardwareInformationCPUNumberOfCores_QNAME, String.class, HardwareInformation.CPU.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AgentInfoProbe", name = "DriverVersion", scope = HardwareInformation.NIC.class)
    public JAXBElement<String> createHardwareInformationNICDriverVersion(String value) {
        return new JAXBElement<String>(_HardwareInformationFiberCardDriverVersion_QNAME, String.class, HardwareInformation.NIC.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AgentInfoProbe", name = "OtherTypeDescription", scope = HardwareInformation.OS.class)
    public JAXBElement<String> createHardwareInformationOSOtherTypeDescription(String value) {
        return new JAXBElement<String>(_HardwareInformationOSOtherTypeDescription_QNAME, String.class, HardwareInformation.OS.class, value);
    }
    

	
	//////////////////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////////////////////////////////////////
	/**
	 *  For software information
	 */
	/**
     * Create an instance of {@link SoftwareInformation.InstalledProgram.Patches.ServicePatch }
     * 
     */
    public SoftwareInformation.InstalledProgram.Patches.ServicePatch createSoftwareInformationInstalledProgramPatchesServicePatch() {
        return new SoftwareInformation.InstalledProgram.Patches.ServicePatch();
    }

    /**
     * Create an instance of {@link SoftwareInformation.InstalledProgram.Patches }
     * 
     */
    public SoftwareInformation.InstalledProgram.Patches createSoftwareInformationInstalledProgramPatches() {
        return new SoftwareInformation.InstalledProgram.Patches();
    }

    /**
     * Create an instance of {@link SoftwareInformation.InstalledProgram }
     * 
     */
    public SoftwareInformation.InstalledProgram createSoftwareInformationInstalledProgram() {
        return new SoftwareInformation.InstalledProgram();
    }
    
    /**
     * Create an instance of {@link SoftwareInformation.AppDataInfo }
     * 
     */
    public SoftwareInformation.AppDataInfo createSoftwareInformationAppDataInfo() {
        return new SoftwareInformation.AppDataInfo();
    }
    
    /**
     * Create an instance of {@link SoftwareInformation }
     * 
     */
    public SoftwareInformation createSoftwareInformation() {
        return new SoftwareInformation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AgentInfoProbe", name = "Edition", scope = SoftwareInformation.InstalledProgram.class)
    public JAXBElement<String> createSoftwareInformationInstalledProgramEdition(String value) {
        return new JAXBElement<String>(_SoftwareInformationInstalledProgramEdition_QNAME, String.class, SoftwareInformation.InstalledProgram.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AgentInfoProbe", name = "InstallDate", scope = SoftwareInformation.InstalledProgram.class)
    public JAXBElement<String> createSoftwareInformationInstalledProgramInstallDate(String value) {
        return new JAXBElement<String>(_SoftwareInformationInstalledProgramInstallDate_QNAME, String.class, SoftwareInformation.InstalledProgram.class, value);
    }
	
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AgentInfoProbe", name = "InstanceName", scope = SoftwareInformation.AppDataInfo.class)
    public JAXBElement<String> createSoftwareInformationAppDataInfoInstanceName(String value) {
        return new JAXBElement<String>(_SoftwareInformationAppDataInfoInstanceName_QNAME, String.class, SoftwareInformation.AppDataInfo.class, value);
    }
    
	//////////////////////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
	 *   For server PKI information
	 */	
	/**
     * Create an instance of {@link ServerPKIInformation.CPUUtil }
     * 
     */
    public ServerPKIInformation.CPUUtil createServerPKIInformationCPUUtil() {
        return new ServerPKIInformation.CPUUtil();
    }

    /**
     * Create an instance of {@link ServerPKIInformation.NetworkUtil }
     * 
     */
    public ServerPKIInformation.NetworkUtil createServerPKIInformationNetworkUtil() {
        return new ServerPKIInformation.NetworkUtil();
    }

    /**
     * Create an instance of {@link ServerPKIInformation.MemoryUtil }
     * 
     */
    public ServerPKIInformation.MemoryUtil createServerPKIInformationMemoryUtil() {
        return new ServerPKIInformation.MemoryUtil();
    }

    /**
     * Create an instance of {@link ServerPKIInformation.DiskUtil }
     * 
     */
    public ServerPKIInformation.DiskUtil createServerPKIInformationDiskUtil() {
        return new ServerPKIInformation.DiskUtil();
    }

    /**
     * Create an instance of {@link ServerPKIInformation }
     * 
     */
    public ServerPKIInformation createServerPKIInformation() {
        return new ServerPKIInformation();
    }



}
