//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.27 at 04:13:44 PM GMT+08:00 
//


package com.ca.arcserve.edge.app.base.webservice.srm;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstalledProgram" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="InstallDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SP" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Patches" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ServicePatch" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="InstallDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="attrName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AppDataInfo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="MajorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="MinorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="InstanceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AppDataSizeMB" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="MachineName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Virtualization" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "SoftwareInformation")
public class SoftwareInformation {

    @XmlElement(name = "InstalledProgram")
    protected List<SoftwareInformation.InstalledProgram> installedProgram;
    @XmlElement(name = "AppDataInfo")
    protected List<SoftwareInformation.AppDataInfo> appDataInfo;
    @XmlAttribute(name = "MachineName", required = true)
    protected String machineName;
    @XmlAttribute(name = "Virtualization", required = true)
    protected int virtualization;

    /**
     * Gets the value of the installedProgram property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the installedProgram property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstalledProgram().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoftwareInformation.InstalledProgram }
     * 
     * 
     */
    public List<SoftwareInformation.InstalledProgram> getInstalledProgram() {
        if (installedProgram == null) {
            installedProgram = new ArrayList<SoftwareInformation.InstalledProgram>();
        }
        return this.installedProgram;
    }

    /**
     * Gets the value of the appDataInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appDataInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppDataInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoftwareInformation.AppDataInfo }
     * 
     * 
     */
    public List<SoftwareInformation.AppDataInfo> getAppDataInfo() {
        if (appDataInfo == null) {
            appDataInfo = new ArrayList<SoftwareInformation.AppDataInfo>();
        }
        return this.appDataInfo;
    }

    /**
     * Gets the value of the machineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * Sets the value of the machineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMachineName(String value) {
        this.machineName = value;
    }

    /**
     * Gets the value of the virtualization property.
     * 
     */
    public int getVirtualization() {
        return virtualization;
    }

    /**
     * Sets the value of the virtualization property.
     * 
     */
    public void setVirtualization(int value) {
        this.virtualization = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="MajorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="MinorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="InstanceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AppDataSizeMB" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    public static class AppDataInfo {

        @XmlElement(name = "CategoryID", required = true, type = Integer.class, nillable = true)
        protected Integer categoryID;
        @XmlElement(name = "MajorVersion", required = true, type = Integer.class, nillable = true)
        protected Integer majorVersion;
        @XmlElement(name = "MinorVersion", required = true, type = Integer.class, nillable = true)
        protected Integer minorVersion;
        @XmlElementRef(name = "InstanceName", namespace = "AgentInfoProbe", type = JAXBElement.class)
        protected JAXBElement<String> instanceName;
        @XmlElement(name = "AppDataSizeMB", required = true, type = Long.class, nillable = true)
        protected Long appDataSizeMB;

        /**
         * Gets the value of the categoryID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCategoryID() {
            return categoryID;
        }

        /**
         * Sets the value of the categoryID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCategoryID(Integer value) {
            this.categoryID = value;
        }

        /**
         * Gets the value of the majorVersion property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMajorVersion() {
            return majorVersion;
        }

        /**
         * Sets the value of the majorVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMajorVersion(Integer value) {
            this.majorVersion = value;
        }

        /**
         * Gets the value of the minorVersion property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMinorVersion() {
            return minorVersion;
        }

        /**
         * Sets the value of the minorVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMinorVersion(Integer value) {
            this.minorVersion = value;
        }

        /**
         * Gets the value of the instanceName property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getInstanceName() {
            return instanceName;
        }

        /**
         * Sets the value of the instanceName property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setInstanceName(JAXBElement<String> value) {
            this.instanceName = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the appDataSizeMB property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getAppDataSizeMB() {
            return appDataSizeMB;
        }

        /**
         * Sets the value of the appDataSizeMB property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setAppDataSizeMB(Long value) {
            this.appDataSizeMB = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="InstallDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SP" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Patches" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ServicePatch" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="InstallDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="attrName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    public static class InstalledProgram {

        @XmlElement(name = "CategoryID", required = true, type = Integer.class, nillable = true)
        protected Integer categoryID;
        @XmlElement(name = "Name", required = true, nillable = true)
        protected String name;
        @XmlElement(name = "Version", required = true, nillable = true)
        protected String version;
        @XmlElementRef(name = "InstallDate", namespace = "AgentInfoProbe", type = JAXBElement.class)
        protected JAXBElement<String> installDate;
        @XmlElement(name = "Language", required = true, type = Integer.class, nillable = true)
        protected Integer language;
        @XmlElement(name = "SP", required = true, type = Integer.class, nillable = true)
        protected Integer sp;
        @XmlElementRef(name = "Edition", namespace = "AgentInfoProbe", type = JAXBElement.class)
        protected JAXBElement<String> edition;
        @XmlElement(name = "Patches")
        protected List<SoftwareInformation.InstalledProgram.Patches> patches;
        @XmlAttribute(required = true)
        protected String attrName;

        /**
         * Gets the value of the categoryID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCategoryID() {
            return categoryID;
        }

        /**
         * Sets the value of the categoryID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCategoryID(Integer value) {
            this.categoryID = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the installDate property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getInstallDate() {
            return installDate;
        }

        /**
         * Sets the value of the installDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setInstallDate(JAXBElement<String> value) {
            this.installDate = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLanguage(Integer value) {
            this.language = value;
        }

        /**
         * Gets the value of the sp property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSP() {
            return sp;
        }

        /**
         * Sets the value of the sp property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSP(Integer value) {
            this.sp = value;
        }

        /**
         * Gets the value of the edition property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getEdition() {
            return edition;
        }

        /**
         * Sets the value of the edition property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setEdition(JAXBElement<String> value) {
            this.edition = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the patches property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the patches property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPatches().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SoftwareInformation.InstalledProgram.Patches }
         * 
         * 
         */
        public List<SoftwareInformation.InstalledProgram.Patches> getPatches() {
            if (patches == null) {
                patches = new ArrayList<SoftwareInformation.InstalledProgram.Patches>();
            }
            return this.patches;
        }

        /**
         * Gets the value of the attrName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrName() {
            return attrName;
        }

        /**
         * Sets the value of the attrName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrName(String value) {
            this.attrName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ServicePatch" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="InstallDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "servicePatch"
        })
        public static class Patches {

            @XmlElement(name = "ServicePatch", required = true)
            protected List<SoftwareInformation.InstalledProgram.Patches.ServicePatch> servicePatch;

            /**
             * Gets the value of the servicePatch property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the servicePatch property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getServicePatch().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SoftwareInformation.InstalledProgram.Patches.ServicePatch }
             * 
             * 
             */
            public List<SoftwareInformation.InstalledProgram.Patches.ServicePatch> getServicePatch() {
                if (servicePatch == null) {
                    servicePatch = new ArrayList<SoftwareInformation.InstalledProgram.Patches.ServicePatch>();
                }
                return this.servicePatch;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="InstallDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "version",
                "installDate"
            })
            public static class ServicePatch {

                @XmlElement(name = "Name", required = true, nillable = true)
                protected String name;
                @XmlElement(name = "Version", required = true, nillable = true)
                protected String version;
                @XmlElement(name = "InstallDate", required = true, nillable = true)
                protected String installDate;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the version property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVersion() {
                    return version;
                }

                /**
                 * Sets the value of the version property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVersion(String value) {
                    this.version = value;
                }

                /**
                 * Gets the value of the installDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInstallDate() {
                    return installDate;
                }

                /**
                 * Sets the value of the installDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInstallDate(String value) {
                    this.installDate = value;
                }

            }

        }

    }

}
