package com.ca.arcserve.edge.app.base.webservice.contract.node;

public enum DiscoveryOperatingSystem {
	EDGE_DISCOVERY_NODE_OS_ALL,
	EDGE_DISCOVERY_NODE_OS_SERVER_ALL,
	EDGE_DISCOVERY_NODE_OS_SERVER_2000,
	EDGE_DISCOVERY_NODE_OS_SERVER_2003,
	EDGE_DISCOVERY_NODE_OS_SERVER_2008,
	EDGE_DISCOVERY_NODE_OS_DESKTOP_ALL,
	EDGE_DISCOVERY_NODE_OS_DESKTOP_XP,
	EDGE_DISCOVERY_NODE_OS_DESKTOP_VISTA,
	EDGE_DISCOVERY_NODE_OS_DESKTOP_WIN7
}
