package com.ca.arcserve.edge.app.base.webservice.contract.node;

public enum DiscoveryServiceStatus {
	DISCOVERY_SERVICE_UNKNOWN,
	DISCOVERY_SERVICE_STOPPED,
	DISCOVERY_SERVICE_START_PENDING,
	DISCOVERY_SERVICE_RUNNING,
	DISCOVERY_SERVICE_STOP_PENDING,
	DISCOVERY_SERVICE_PAUSE_PENDING,
	DISCOVERY_SERVICE_PASUED
}
