package com.ca.arcserve.edge.app.base.webservice.contract.node;

public enum DiscoveryPhase {
	DISCOVERY_PHASE_NONE,
	DISCOVERY_PHASE_NODE,
	DISCOVERY_PHASE_D2D,
	DISCOVERY_PHASE_ARCSERVE,
	DISCOVERY_PHASE_RHA,
	DISCOVERY_PHASE_RPS,
	DISCOVERY_PHASE_SQL,
	DISCOVERY_PHASE_EXCHANGE,
	DISCOVERY_PHASE_SPS,
	DISCOVERY_PHASE_UPDATE_DATA,
	DISCOVERY_PHASE_END
}
