package com.ca.arcserve.edge.app.base.webservice.contract.arcserve;

public enum ResultCode {
	SYNC_SUCCESS_WITHOUT_EXCEPTION,
	PRIMARY_ROLE_CHANGE_AND_NO_PLAN_USE_SERVER,
	PRIMARY_ROLE_CHANGE_AND_HAS_PLAN_USE_SERVER,
	MEMBER_ROLE_CHANGE_AND_HAS_PLAN_USE_SERVER,
	SYNC_SUCCESS_WITH_MEMBER_SERVERS_DELETED,
	ASBU_SERVER_HAS_BEEN_CONTROLED_BY_OTHER_CONSOLE,
}
